### ISSUE TITLE
Spindle humming due to low frequency PWM

### ISSUE THREAD

**Issue by fornellas** [gnea/grbl#1026]
The PWM frequency is set [here](https://github.com/gnea/grbl/blob/master/grbl/cpu_map.h#L147) to ~980Hz. This makes the motor resonate at the same frequency. Some motors (eg: the one from [Sainsmart 3018 PROVer](https://www.sainsmart.com/collections/cnc-machines/products/sainsmart-genmitsu-cnc-router-3018-prover-kit)) produces a constant loud annoying humming at this very same frequency, independent of the RPM.

Is there any rational to keep the default value to 980Hz? It seems that this could run at 62.5kHz which's above what humans can hear, which should take away most of the noise.

I'm no expert on driving DC motors with PWM, but some boards have some inductors & capacitors to smooth things out, running at higher frequencies should also make the PWM signal more smooth, thus reducing noise further.

CC @chamnit who [added](https://github.com/gnea/grbl/commit/cb916a9) this ~4 years ago.

**Comment by chamnit** [comment]
It was a request from a laser manufacturer. Laser frequency is otherwise arbitrary.
