### ISSUE TITLE
Reported status (response for <?>) behaviour 

### ISSUE THREAD

**Issue by luben111** [gnea/grbl#103]
When sending the status polling command <?> the GRBL returns the status.

My question is - if I send the <?> command and if the GRBL controller at this particular moment is outputting some data what will happen?

A. The currently active data output will complete and then will execute the <?> to output the status. In this case CR LF at the end of the status data makes sense.

B. The status will be inserted/injected into the currently outputted message (tokens < & > are unique and can be tracked in the outputs). In this case there should be no CR LF at the end of the status data.

From what I see I'm more inclined to think about case A.

Thank you

**Comment by chamnit** [comment]
@luben111 : Grbl clears real-time command flags after they have been set to execute. They can be set once they are cleared. Any double commands that tries to set an already set command will be ignored. This should be all be explained in the interface documentation.
