### ISSUE TITLE
Grbl-1.1e svn1347 : Precision ?

### ISSUE THREAD

**Issue by LETARTARE** [gnea/grbl#107]
Here is a sequence of weird  responses in mm  (on a terminal) :

Grbl 1.1e ['$' for help]     
send : **$I**                                                                        
[VER:1.1e.20170114:]                                                          
[OPT:VNMZ]                                                                    
ok                                                                            
ok                                                                            
send : **$#**                                                                         
[_G54:131.057,150.652,20.153_]                                                  
[G55:40.000,50.000,30.000]                                                    
[G56:0.000,0.000,0.000]                                                       
[G57:30.000,50.000,20.000]                                                    
[G58:130.000,150.000,40.000]                                                  
[G59:500.000,500.000,25.000]                                                  
[G28:0.000,0.000,0.000]                                                       
[G30:0.000,0.000,0.000]                                                       
[G92:0.000,0.000,0.000]                                                       
[TLO:0.000]                                                                   
[PRB:0.000,0.000,0.000:0]                                                     
ok                                                                            
ok                                                                            
send : **G90 G54 X0 Y0 Z0**                                                              
ok                                                                            
ok                                                                            
send : **?**                                                                             
<Idle|WPos:-0.002,-0.002,0.002|Bf:35,253|FS:0,0|WCO:131.057,150.652,20.153>   
ok                                                                           
ok  

Normally one should have ;
**WPos:0.000,0.000,0.000** and not **WPos:-0.002,-0.002,0.002**

Do you see that ?

The same observation with  'GrblPanel-1.09.12' and 'Candle-1.1.7'.

**Comment by chamnit** [comment]
@LETARTARE : Grbl tracks position in terms of steps. When it reports a position, it converts those steps to floating point. True position will be accurate to within the step/mm setting.
