### ISSUE TITLE
How Can i lock the motor?

### ISSUE THREAD

**Issue by FabriLeo** [gnea/grbl#1090]
I need to lock the motors after work because otherwise the z axis starts to fall when the machine is at rest.

PD: Sorry for my bad english, i speak spanish.

**Comment by ashish8284** [comment]
Set $1=255 will keep all stepper  enabled.
It will  hold all 3 steppers whenmachineis idle. & Motors get warmer too.

**Comment by FabriLeo** [comment]
Thanks, Here is the explication https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#1---step-idle-delay-milliseconds.
