### ISSUE TITLE
Bug in gcode.c?

### ISSUE THREAD

**Issue by terjeio** [gnea/grbl#1098]
A grblHAL user has reported [an issue](https://github.com/grblHAL/core/issues/87) when G28G91Z0 is following G80 it results in error 31 beeing raised.
I believe this is a bug and will correct it in grblHAL, details about where it is and how to correct it can be found in the linked issue.

Since this "bug" has been inherited from this repo, and as it seems be present in other ports as well, I decided to report it here.

**Comment by ooxi** [comment]
I would suggest reporting this as a pull request. Nevertheless, be aware that this repository does not seem to be maintained.
