### ISSUE TITLE
CNC stops randomly

### ISSUE THREAD

**Issue by jhnwmr** [gnea/grbl#1100]
Hello,
I have a CNC 1419 with the supplied controller in use. It has GRBL v0.9 on it.
I use the GRBL Control software supplied to control it.
When I start a G-code program it runs for a while and then breaks the process. It resets all the coordinates to 0 0 0 and in the terminal window comes the welcome message with GRBL v0.9.

What is the reason that it just stops and the board resets? The reset does not always come at the same time.

In addition, it outputs two errors:
```
Serial port error 7: Access
denied
Serial port error 2: Access denied
denied
```

I would be very grateful for any advice!

**Comment by GrahamJB** [comment]
That error is coming from your PC not Grbl. Check any sleep settings on your computer, Windows can and will turn off the Serial port if it thinks it is not in use, PC going to sleep will also do this.

The Access denied almost certainly means another program has the serial port opened.
