### ISSUE TITLE
GRBL Commands / Comments Question

### ISSUE THREAD

**Issue by synman** [gnea/grbl#1103]
I maintain a plug-in for OctoPrint that extends GRBL to that platform (https://github.com/synman/Octoprint-Bettergrblsupport).

I've noticed quite a bit of variability from laser / CNC slicers when it comes to comments.

https://github.com/synman/Octoprint-Bettergrblsupport/issues/23

I'm guessing GRBL is choking over the % character being passed in via the logged gcode.   It responds with `Recv: error: Expected command letter`

I have existing logic to strip lines beginning with "(" and ";".   I'm wondering if it is appropriate to also strip %.  I have no idea at present why it would be included in (supplied) gcode.  Perhaps a slicer is using it as delimiter for marking "begin" and "end" of gcode.

```
%
(Header)
(Generated by gcodetools from Inkscape.)
(Using default header. To add your own header create file "header" in the output dir.)
M3
(Header end.)
G21 (All units in mm)

(Start cutting path id: path595)
(Change tool to Default tool)

G00 Z35.000000
G00 X-491.779890 Y-122.049310

G01 Z-1.000000 F800.0(Penetrate)
G02 X-490.116910 Y-125.322640 Z-1.000000 I-0.343640 J-2.233677 F800.000000
G02 X-492.648940 Y-127.698140 Z-1.000000 I-4.631748 J2.399763
G02 X-499.796749 Y-126.487713 Z-1.000000 I-2.654200 J6.036252
G02 X-503.077560 Y-120.311210 Z-1.000000 I7.295371 J7.834722
G02 X-499.430246 Y-109.549923 Z-1.000000 I12.101184 J1.897290
G02 X-489.172740 Y-105.102810 Z-1.000000 I11.170787 J-11.712721
G02 X-474.733751 Y-111.086223 Z-1.000000 I1.015228 J-17.963653
G02 X-469.184560 Y-125.525510 Z-1.000000 I-16.306012 J-14.552550
G02 X-477.472486 Y-143.668194 Z-1.000000 I-23.732349 J-0.122992
G02 X-496.125130 Y-150.293480 Z-1.000000 I-17.935954 J20.926672
G02 X-517.984062 Y-139.714657 Z-1.000000 I0.766229 J29.456126
G02 X-525.672890 Y-116.835020 Z-1.000000 I25.550664 J21.318197
G02 X-512.810249 Y-91.252855 Z-1.000000 I35.155714 J-1.651462
G02 X-485.696550 Y-82.507480 Z-1.000000 I24.699480 J-30.173337
G02 X-456.386877 Y-97.649806 Z-1.000000 I-2.533458 J-40.841038
G02 X-446.589220 Y-129.001700 Z-1.000000 I-34.794026 J-28.080205
G02 X-464.008627 Y-162.041697 Z-1.000000 I-46.517274 J3.412977
G02 X-499.601330 Y-172.888810 Z-1.000000 I-31.460554 J39.412880
G02 X-536.373594 Y-153.194088 Z-1.000000 I4.290612 J52.187397
G02 X-548.268220 Y-113.358820 Z-1.000000 I44.030192 J34.840685
G02 X-526.299424 Y-72.852883 Z-1.000000 I57.853254 J-5.166820
G02 X-482.220350 Y-59.912150 Z-1.000000 I38.220659 J-48.646209
G02 X-437.979696 Y-84.154109 Z-1.000000 I-6.041905 J-63.515983
G02 X-423.993890 Y-132.477900 Z-1.000000 I-53.261231 J-41.600566
G00 Z35.000000

(End cutting path id: path595)

(Start cutting path id: rect10)
(Change tool to Default tool)

G00 Z35.000000
G00 X-330.136360 Y-85.549170

G01 Z-1.000000 F800.0(Penetrate)
G01 X-112.873540 Y-85.549170 Z-1.000000 F800.000000
G01 X-112.873540 Y-125.525530 Z-1.000000
G01 X-330.136360 Y-125.525530 Z-1.000000
G01 X-330.136360 Y-85.549170 Z-1.000000
G00 Z35.000000

(End cutting path id: rect10)

(Footer)
M5
G00 X0.0000 Y0.0000
M2
(Using default footer. To add your own footer create file "footer" in the output dir.)
(end)
%
```

**Comment by synman** [comment]
I also have zero details as to how this gcode was generated, beyond the comment` (Generated by gcodetools from Inkscape.)  `Perhaps this is an output issue where a consumer / user copy/pasted the resulting gcode into a file and failed to remove these delimiters.

**Comment by GrahamJB** [comment]
As I understand it % is the command to rewind the paper tape to the start.

**Comment by synman** [comment]
I would have never guessed that.  I'm assuming this is out of bounds when it comes to GRBL or is it a function I should allow to pass-through to the engraver?

Thank you for the super fast response and my apologies for the hassle.

**Comment by GrahamJB** [comment]
Grbl recognises some commands to prevent errors but ignores them like line numbers and G40.

Gcode has many options which increase day by day.

Look for the supported commands, I think the readme has a list.

**Comment by synman** [comment]
yeah, I try to keep up with the list.  I'll poke around for it... it's how I figured out Reset (CTRL-X)

**Comment by synman** [comment]
well, it is listed here

https://wiki.shapeoko.com/index.php/G-Code#List_of_all_G-codes.5B44.5D

I'm gonna chalk this up to firmware / build variability given how easy it is to build and redistribute grbl.

**Comment by GrahamJB** [comment]
But that is for Shapeoko routers and it's not quite accurate. You could add support for the % command but as it basically does nothing what's the point.

**Comment by synman** [comment]
it is referenced from the official GRBL wiki though lol

but not here:  https://linuxcnc.org/docs/html/gcode.html

which is also linked from the wiki
