### ISSUE TITLE
Are limit switches respected when jogging?

### ISSUE THREAD

**Issue by MarkHerhold** [gnea/grbl#1104]
I'm running a protoneer cnc board (v2.6) on a RPI. The X,Y,Z limit switch pins are pulled high by default. When I pull them low while jogging, the machine continues to jog. Is there something I need to configure to ensure the machine would not crash?

**Comment by langwadt** [comment]
you have hardlimits enabled? $21 as far as I remember

**Comment by MarkHerhold** [comment]
That was it. Thank you!

I also found this which is immensely helpful:

https://www.diymachining.com/downloads/GRBL_Settings_Pocket_Guide_Rev_B.pdf
