### ISSUE TITLE
How to ensure GRBL is really IDLE?

### ISSUE THREAD

**Issue by naikymen** [gnea/grbl#1115]
I was wondering what is the best way to ensure that the machine has stopped moving.

The objective is to ensure an idle machine, before a different machine will perform an independent but coordinated action (which requires all GRBL moves to complete, and an idle machine).

So far:

* I was able to count 'ok' responses (which do not ensure the end of movements, but was a first step) of every move gcode.
* I was also able to monitor GRBL's status, by continuously sending '?' commands and parsing the outputs.

Because receiving all 'ok' responses ensures that the serial interface is not messing with me (right?), I had imagined that a subsequent "idle" status response would ensure the machine was not moving, and would not move afterwards. In this moment, the second machine would start it's action.

However, though infrequently, the machine was not actually IDLE, and would continue to move, messing up the coordination with the second machine.

I was wondering if there is a fool-proof way of ensuring that a GRBL machine has finished moving, and will not move (unless more gcode is sent to the serial interface).

So far, my best strategy has been to require three consecutive IDLE status reports, instead of just one.

Thanks in advance!

**Comment by langwadt** [comment]
afair a dwell command (something like G4 P0.01) won't reply 'ok' until the buffers are empty and grbl is idle

**Comment by naikymen** [comment]
Thanks for the quick reply!

G4 commands seem adequate, I was unaware of them. Closing!

For anyone who failed to find it, a [list of supported commands](https://github.com/gnea/grbl#update-summary-for-v11) is in the main readme :)
