### ISSUE TITLE
X limit switch triggers XYZ limits

### ISSUE THREAD

**Issue by NilsNippe** [gnea/grbl#1116]
Setup: Dual Y-Axis, CAT7 cables going to stepper drivers and NC limit switches, external stepper drivers.

Problem: z and y limit switches don't trigger. When triggering x limit switch it triggers all limit switches at once.

When using $5=1 "?" always shows the x limit as triggered, when actually triggering the x switch it hangs and outputs: "
<Alarm|MPos:0.000,0.000,0.000|Bf:15,128|FS:0,0"

Settings not jet tuned, but the z axis moves when trying to home:
`$0=10
$1=255
$2=0
$3=0
$4=0
$5=0
$6=0
$10=19
$11=0.010
$12=0.002
$13=0
$20=1
$21=0
$22=1
$23=0
$24=100.000
$25=500.000
$26=250
$27=5.000
$30=1000
$31=0
$32=0
$100=80.000
$101=80.000
$102=2500.000
$110=10000.000
$111=5000.000
$112=500.000
$120=500.000
$121=100.000
$122=10.000
$130=500.000
$131=500.000
$132=200.000`

**Comment by Pethical** [comment]
Hi,
Please check your wiring.

**Comment by NilsNippe** [comment]
Do you have a concrete wiring error to check? The switches are connected to the corresponding pins as referenced here: https://github.com/gnea/grbl/wiki/Connecting-Grbl with the modification of adding one of the y-axis limits in series with the z limit.

There are no shorts between the switches.

When the arduino reads the switches with a dedicated program that does nothing else, the limits work as expected.

**Comment by NilsNippe** [comment]
In my case it was the typo in the report.c grbl file. https://github.com/gnea/grbl/issues/712
After I redownloaded all of the grbl files my router worked in single y axis mode, and compiling grbl for dual axis gave the corrosponding error.
