### ISSUE TITLE
Wiring optical endstop

### ISSUE THREAD

**Issue by ScottFal** [gnea/grbl#1149]
when i wire up the optical endstop like the picture, it works the opposite as I would like, it gets detected with nothing blocking it, and isn't detected with something in the way, how would I go around changing it
![image](https://user-images.githubusercontent.com/72571206/177010129-8b130d0a-d687-4e2b-a457-f836932f0db4.png)

optical endstop used: https://www.amazon.co.uk/gp/product/B077X8XL56/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

**Comment by langwadt** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#5----limit-pins-invert-boolean

**Comment by ScottFal** [comment]
> https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#5----limit-pins-invert-boolean

this does work but, it gives me a new problem, the pins without limit stops(z) now always alarm, is there a way I can ignore the x axis alarm?
