### ISSUE TITLE
Homing fails for small travel resolution

### ISSUE THREAD

**Issue by dan21dan** [gnea/grbl#1152]
Hello dear forum,

I upload firmware GRBL v1.1 custom, XY Homing 30.8.2019 (which is included LaserGRBL v4.8.3) into Arduino Uno. First homing worked properly. The homing started to fail during my calibration (when changed GRBL configuration). I found that it depends on X-axis and Y-axis travel resolution (parameters $100 and $101). I have found that it fails for small travel resolution. I evaluated my engraver resolution as 80.058 step/mm. But with this settings homing fail. Homing start to work when I change resolution to 100 (or 200 or 250). And homing fails again when I return resolution back to 80.058 step/mm. Do you have any idea what I should change to homing works with X,Y-travel resolution set to 80.058 step/mm? Of course – I have tested also with X,Y-travel resolution set to 80.000 step/mm to avoid that the problem is decimal numbers but it fails too. Except for homing, all other functions work without any problems. My configuration:

```
$0=10 (Step pulse time)
$1=25 (Step idle delay)
$2=0 (Step pulse invert)
$3=0 (Step direction invert)
$4=0 (Invert step enable pin)
$5=0 (Invert limit pins)
$6=0 (Invert probe pin)
$10=1 (Status report options)
$11=0.010 (Junction deviation)
$12=0.002 (Arc tolerance)
$13=0 (Report in inches)
$20=1 (Soft limits enable)
$21=1 (Hard limits enable)
$22=1 (Homing cycle enable)
$23=3 (Homing direction invert)
$24=20.000 (Homing locate feed rate)
$25=200.000 (Homing search seek rate)
$26=250 (Homing switch debounce delay)
$27=1.000 (Homing switch pull-off distance)
$30=1000 (Maximum spindle speed)
$31=0 (Minimum spindle speed)
$32=1 (Laser-mode enable)
$100=80.058 (X-axis travel resolution)
$101=80.058 (Y-axis travel resolution)
$102=250.000 (Z-axis travel resolution)
$110=5000.000 (X-axis maximum rate)
$111=5000.000 (Y-axis maximum rate)
$112=500.000 (Z-axis maximum rate)
$120=20.000 (X-axis acceleration)
$121=20.000 (Y-axis acceleration)
$122=10.000 (Z-axis acceleration)
$130=310.000 (X-axis maximum travel)
$131=406.000 (Y-axis maximum travel)
$132=200.000 (Z-axis maximum travel)
```

**Comment by MARIOBASZ** [comment]
try $27 =5. If it works, you can try a lower value that is safe

**Comment by dan21dan** [comment]
It works. It also works for $27 = 4; 3 and 2 but not for 1:) Thanks!
