### ISSUE TITLE
machine coordinates not displayed

### ISSUE THREAD

**Issue by sanooka** [gnea/grbl#117]
After upgrading to grbl 1.1f the grbl controller 3.6.1 doesn't show machine coordinates when program is running or in axis control.
The x,y,z shows 0 at all time

**Comment by gerritv** [comment]
Grbl Controller is a GUI for Grbl, it is not Grbl so this is not the best place to get support for it . Grbl Controller hasn't been updated since 2014 and is considered a dead project. You will need to pick a more current GUI.
