### ISSUE TITLE
PWM output to inverter

### ISSUE THREAD

**Issue by poesel** [gnea/grbl#118]
Caveat: this may not be related to grbl at all. Please close the issue if you think it's in the wrong place.

I've connected D11 to the 5v input on my Huanyang inverter. This works until you go below 50Hz. Then the spindle starts to jerk (no load). I guess this is caused by the PWM output of the Arduino and the inverter interpreting the 'long' 0v phases as stop. So I added a RC filter and now the spindle works down to 14Hz without jerking. 
Problem: when I use PWM control and move the gantry together then all axis start to rattle like crazy. Moving without spindle is ok, spindle without moving is ok but not botch. 

Im at a loss how the RC could influence grbl? How do you connect the Arduino to an inverter?

Thanks

**Comment by jahnj0584** [comment]
Your inverter should be set to 400HZ at all times.

**Comment by poesel** [comment]
Why would I do that? It is the point of using an inverter and grbls pwm output to have variable speeds. If I wanted only one speed I just need a switch.

**Comment by chamnit** [comment]
@poesel: Not sure if this will help you or not, because I'm not quite sure what you are asking. You can alter the spindle PWM output frequency in cpu_map.h. It's currently at 1kHz for lasers. It can be altered to 2 other higher frequencies, if I remember right. Also, if you just want a switch, you can disable VARIABLE_SPINDLE which will move the pin to D12 from D11 (or you can alter this in cpu_map.h to stay the same).

**Comment by poesel** [comment]
I wanted to control the spindle speed with the inverter and I found the solution in the meantime:
![bildschirmfoto 2017-02-05 um 18 55 40](https://cloud.githubusercontent.com/assets/20629637/22629123/96446984-ebe0-11e6-9eb6-41c184ac321a.png)
![bildschirmfoto 2017-02-05 um 18 55 52](https://cloud.githubusercontent.com/assets/20629637/22629128/9d7ec5f0-ebe0-11e6-8304-9a573a1d5ad9.png)
R2 4.7 kohm
R3 180 ohm
Rpot1 310 Ohm
C1 47 uF, 16 V
That may be useful for the wiki because the pwm output is not only useful for a laser.

**Comment by Harvie** [comment]
Now there seems to be quite elegant solution integrating Huanyang RS485 communication directly to GRBL, i would be happy if you can help with testing:
https://github.com/terjeio/grblHAL/issues/68
