### ISSUE TITLE
height map for PCB

### ISSUE THREAD

**Issue by Zdenekr** [gnea/grbl#1185]
Hello,
i use candle to make pcb and i started to make pcb with metallized holes.
First I drill all the holes, do the plating and then I need to mill the paths.
For that I need a height map.
Sometimes I hit a hole while scanning and the map is corrupted.
Is there any way to scan the bond paths outside the holes?
Thank you for answer.
Regards
Zdenek

**Comment by GrahamJB** [comment]
I would try a probe with a flat base of a larger diameter than the holes first and see how that goes.

 

Just an idea, not necessarily a good one.

 

From: Zdenekr ***@***.***> 
Sent: 22 December 2022 7:06 PM
To: gnea/grbl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gnea/grbl] height map for PCB (Issue #1185)

 

Hello,
i use candle to make pcb and i started to make pcb with metallized holes.
First I drill all the holes, do the plating and then I need to mill the paths.
For that I need a height map.
Sometimes I hit a hole while scanning and the map is corrupted.
Is there any way to scan the bond paths outside the holes?
Thank you for answer.
Regards
Zdenek

**Comment by Zdenekr** [comment]
thanks for the tip, i'll try it

**Comment by pmbrown141** [comment]
Zdenekr

I would love to know your process for plating through holes. 

Would you care to share?
