### ISSUE TITLE
xLoader instructions lead to a trojan

### ISSUE THREAD

**Issue by skruger** [gnea/grbl#1186]
I followed the windows instructions to load a grbl binary on to my arduino using xLoader.
https://github.com/gnea/grbl/wiki/Flashing-Grbl-to-an-Arduino#for-windows

The xLoader didn't actually work and windows identified a Trojan and named xLoader as being related to it's installation.

![xloader-trojan](https://user-images.githubusercontent.com/201151/209455154-a957f565-34f1-4c3e-89c5-54735171759d.png)

**Comment by AlexHolden** [comment]
I've deleted the link, just in case. I've never used xLoader myself so I'm not sure what is the official site to download it from.

**Comment by X3msnake** [comment]
XLoader is a sourceless wrapper to avrdude and since the author never released the sourcecode and his website disappered from the web, the copies around the web can not be trusted

It is better to use avrdudess gui instead. It is opensource and updated. Download only from the source GitHub

https://github.com/ZakKemble/AVRDUDESS

**Comment by harryberlin** [comment]
BTW:
Laser GRBL has a Dialog for uploading Firmware.

**Comment by arrsoft312** [comment]
You can give a try to my small and simple utility for flashing HEX-files to Arduino UNO and Nano boards.

Source code: https://github.com/arrsoft312/update
Compiled binary for Windows: https://github.com/arrsoft312/update/releases/latest

**Comment by skruger** [comment]
I followed the CLI instructions so I was able to get the image flashed. I just wanted to make sure this was reported to raise awareness. Thanks for all your suggestions, I may incorporate them when I have more arduinos to flash.

**Comment by per1234** [comment]
>I'm not sure what is the official site to download it from.

This is the XLoader download link that was in the wiki before the chain of malicious edits:

http://www.hobbytronics.co.uk/download/XLoader.zip

You can see it in the wiki commit history here:

https://github.com/gnea/grbl/wiki/_compare/bf8da25354e311faaafc15ffae4819c59b3b7b2f

---

Related: https://github.com/gnea/grbl/issues/1053
