### ISSUE TITLE
error 22: Feed rate has not yet been set or is undefined.

### ISSUE THREAD

**Issue by hackqiang** [gnea/grbl#119]
I'm using v1.1f Grbl and v3.6.1 Grbl controller.
when I try to move X or Y, I got error22. Z has no such error.
what should I do to fix this?
Thanks

**Comment by vMeph** [comment]
I dont think grbl controler is compatible with grbl 1.1 version

**Comment by gerritv** [comment]
Grbl Controller is an abandoned project, Zapmaker hasn't been heard from since 2014

**Comment by hackqiang** [comment]
Oops...
is there any free software to replace Grbl Controller?

**Comment by vMeph** [comment]
https://winder.ci.cloudbees.com/job/UGS/

**Comment by Shahid-lateef** [comment]
I'm using v1.1f Grbl on arduino mega 2560 and Grbl controller.
when I try to move X or Y, I got error22. Z has no such error.
what should I do to fix this?
Thanks
