### ISSUE TITLE
D11 no put with UNO on v1.1f

### ISSUE THREAD

**Issue by hackqiang** [gnea/grbl#120]
Dear Developer,
I follow the wiki got Grbl control software,
and now X,Y works.
But I meet another issue, the D11 has no output when I send:
`M3`
I tested in GrblPanel(I think it's not this software issue).
And I also test D11 pin via my custom code, it also works.
Did I miss something?
thanks for help!

**Comment by chamnit** [comment]
You have to send a Sxxx spindle speed word, where xxx is greater than 0.
