### ISSUE TITLE
Gtbl v1.1 report request "?" only responds with "ok"

### ISSUE THREAD

**Issue by FaysalAriss** [gnea/grbl#1200]
I've tried using this command on UGS and Candle, I type in "?" no carriage return or spaces or anything and send it and the only response is ok.
![222062459-a867d7ff-b300-4896-b12d-14d55d8d6ed8](https://user-images.githubusercontent.com/40504311/222069445-90859ad5-96da-402f-b635-0de590a5a0bc.png)

**Comment by psyhlo** [comment]
type $ for help
it is written on the line 3

**Comment by FaysalAriss** [comment]
![image](https://user-images.githubusercontent.com/40504311/222178844-86e97220-103d-4ce1-9a36-9ad59e3661dd.png)
"$" just gives me a list of commands I'm able to use, I've reviewed all of them but they don't fix my problem.

**Comment by FaysalAriss** [comment]
The output is supposed to be hidden to the user, to enable verbose output in UGS: Tools>Settings>UGS>Sender Options>Show verbose output
