### ISSUE TITLE
Cycle start after Toggle spindle stop

### ISSUE THREAD

**Issue by amrish1222** [gnea/grbl#124]
In the discription of Extended-ASCII Realtime Command for Toggle Spindle Stop -
'When motion restarts via cycle start, the last spindle state will be restored and wait 4.0 seconds (configurable) before resuming the tool path. This ensures the user doesn't forget to turn it back on.'

I am using - grbl v1.1f.20170131
After the spindle is toggled off using the Toggle spindle stop command and cycle start command is sent, the toolpath starts instantaneously without the 4 seconds delay that was mentioned.
 Is the feature enabled? And if so where can i change the delay time?

**Comment by chamnit** [comment]
@amrish1222 : Do you have laser mode enabled? This removes the delay time, which is configurable if you familiarize yourself with the options in the config.h file.
