### ISSUE TITLE
jog command unavailable

### ISSUE THREAD

**Issue by fre010** [gnea/grbl#1240]
hello,

I am using GRBL 1.1 and when I try to use the jog command $J=X100Y0Z0 it returns error 22. what can i do to solve this?

Kind regards

**Comment by breiler** [comment]
Error 22:
https://github.com/gnea/grbl/blob/bfb67f0c7963fe3ce4aaf8a97f9009ea5a8db36e/doc/csv/error_codes_en_US.csv#L21

You need to add a feedrate, ie `F1000`.

**Comment by fre010** [comment]
> Error 22:
> 
> https://github.com/gnea/grbl/blob/bfb67f0c7963fe3ce4aaf8a97f9009ea5a8db36e/doc/csv/error_codes_en_US.csv#L21
> 
> You need to add a feedrate, ie `F1000`.

oh what a stupid mistake, I thought it would be like the G0 command. just one more question, do you happen to know the 'jog cancel' command? so i can cancel it and start another jog for example?

**Comment by mar0x** [comment]
See [Extended-ASCII Realtime Command Descriptions](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands#extended-ascii-realtime-command-descriptions):

> 0x85 : Jog Cancel
