### ISSUE TITLE
Machine Status dont update

### ISSUE THREAD

**Issue by Rubyrohd** [gnea/grbl#128]
Hi,

Iam using GBRL controller v1.0.9. with latest version of GBRL 1.1f

I have tryed setting to $10=1, $10=2, $10=3... but nothing is send back to the controller.

Regards
Lars

**Comment by gerritv** [comment]
Hi Lars, when you go to the GrblController web site it clearly states that Zapmaker hasn't been doing any modifications since 2014. So his controller sw will not work with Grbl 1.1 :-(
