### ISSUE TITLE
firmware explanation

### ISSUE THREAD

**Issue by Eric-Hsia** [gnea/grbl#129]
hi, everyone
     who can help me to explain below code: in planner.c line 433
     junction_unit_vec[idx] = unit_vec[idx]-pl.previous_unit_vec[idx];

thanks

**Comment by MechaSteve** [comment]
This is calculating the difference in velocity at the junction. By taking the new segment vector and subtracting the previous vector, we get the vector pointing in the direction of acceleration. This is the acceleration that will change the previous velocity into the new velocity. (see diagram) The loop iterates over each axis to perform the complete vector math. 

![vectors](https://cloud.githubusercontent.com/assets/1733361/23044154/0461d48a-f46d-11e6-8a67-4f746b6c4e04.png)

This value is then used on line 445 where it is normalized (scaled to unit magnitude) and 446 to calculate the unit vector of the acceleration (scaled to remain under axis limits).

**Comment by chamnit** [comment]
@Eric-Hsia : See [this](https://onehossshay.wordpress.com/2011/09/24/improving_grbl_cornering_algorithm/).

**Comment by Eric-Hsia** [comment]
@MechaSteve @chamnit Thanks very much
