### ISSUE TITLE
How Set Slowly ramp to pwm setpoint? 

### ISSUE THREAD

**Issue by a-sheng** [gnea/grbl#13]
How Set Slowly ramp to pwm setpoint? Most PWM motor controllers will faithfully attempt to instantaneously start or stop a motor, causing massive current inrush.

**Comment by chamnit** [comment]
@a-sheng : There is no specific command to control this inside Grbl. Depending on your application, you may want to put current limiting on your PWM controller instead. It's a much more robust solution. If you can't, then you can do a series of increasing S spindle speed followed by a short delay. A simple macro could monitor for any M3 spindle enable and insert this code for you.

**Comment by a-sheng** [comment]
@chamnit :thank you! I Try
