### ISSUE TITLE
.cnc file format

### ISSUE THREAD

**Issue by Sajjadkhalil** [gnea/grbl#135]
Hi, as I know the .cnc file contains supported gcode files grbl, so simply, I have changed the extension to .nc
and opened it with gcode sender, named, bCNC, Candle and winder, all of them visuales the file correctly, but after few gcodes sent it stopped, in the same location so I suspect that the problem in the gcode streamer.
the file I have used is attached
[test gcode.zip](https://github.com/gnea/grbl/files/796961/test.gcode.zip)

the problem that I want to use existing files that I am using which is in the extension of .cnc

**Comment by gerritv** [comment]
Actually the fact that 3 GUI's stop in the same place means it is likely your gcode. What error is displayed in the Status response from Grbl? You can also try enabling Check Mode and seeing what error Grbl sends back without the steppers moving etc.

**Comment by BlueOrangeLive** [comment]
@ Sajjadkhalil I have the file in bCNC looked at. But you must have a very large CNC because in the X direction the part is over 1140mm and in the Y direction 2360mm.
I have the file since about 20 minutes on bCnc and grbl 1.1 ... just instaliert without CNC machine further run time still about 1 stune and 40 minutes.

Greeting Jürgen from Germany I go to altweiber carnival, Helau.

**Comment by Sajjadkhalil** [comment]
thanks friends for help,
In check mode the gcode works flawlessly, but when the program sending the gcode to the arduino it stops after few lines, I think that the gcode sender did not receive a message from the arduino to go further.
about my CNC I am trying to use it in stander CNC with dimensions of 2500 mm by 14000 mm, because I am tired of using desktop PC as it uses the NC studio.
no error is displayed, and will attach a picture of the test run.
 the only message I have got recently is Alarm:64 in bCNC app when performing scan edges
![test 1](https://cloud.githubusercontent.com/assets/16021688/23296730/79bbc98c-fa87-11e6-8aae-cce9f1bc558e.jpg)
![test 2](https://cloud.githubusercontent.com/assets/16021688/23296735/7c890fe4-fa87-11e6-8916-525b8e1adde3.jpg)
![test 3](https://cloud.githubusercontent.com/assets/16021688/23296745/887bdf98-fa87-11e6-9989-ed85a6621655.jpg)
![check mode 1](https://cloud.githubusercontent.com/assets/16021688/23296748/8ad3b0e0-fa87-11e6-9cff-2df1c26573c1.jpg)
![scan edges](https://cloud.githubusercontent.com/assets/16021688/23296749/8d0a46a8-fa87-11e6-8364-054bf2f27adf.jpg)
![settings](https://cloud.githubusercontent.com/assets/16021688/23296751/8f4bdbd4-fa87-11e6-8566-019f9c7d4697.jpg)

I have searched the meaning of alarm:64 in bCNC but I could not find any thing yet.

**Comment by gerritv** [comment]
The message you received (Grbl 1.1 etc) is because your Grbl reset itself. You have electrical noise issues which is why it worked in Checkmode but not with motors and spindle running.

**Comment by chamnit** [comment]
You are exceeding the max 30kHz step rate Grbl supports. Your y settings produce 66kHz. Reduce your max rate. 

Also your step pulse time is unusually large. Reduce that as well.

**Comment by Sajjadkhalil** [comment]
thanks friends,
I have reuploaded the grbl to arduino using the precompiled .hex file instead of arduino IDE and it is now working
thanks chamnit for this note.
