### ISSUE TITLE
Laser mode - Laser On during jogging

### ISSUE THREAD

**Issue by 1Metalguru** [gnea/grbl#136]
Seems that in Laser Mode, if the Laser was inadvertently left enabled by the g-code, ie in motion mode M4 or if the Spindle speed is left non -zero, the motion algorithm will turn on the laser when the machine is jogged using any of the jog buttons as a result of the movement sensing algorithm.

This is potentially an unsafe situation where the laser could turn on when the user is not expecting it and damage the work or the users eyes.  This also could be a potential hazard when switching back to routing mode if $32 is still set to 1, the spindle could turn on during a jog operation.

Issuing an M5 before jogging is a potential workaround, but the laser/spindle should be automatically disabled during jogging.

**Comment by chamnit** [comment]
@1Metalguru : This was intentional and a request from other laser users. See the [wiki](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode). It explains that it does this there.
