### ISSUE TITLE
trunk svn1353 : Error in 'report_build_info(char *line)'

### ISSUE THREAD

**Issue by LETARTARE** [gnea/grbl#137]
Hello,
#ifndef HOMING_INIT_LOCK   // -> #ifdef HOMING_INIT_LOCK  
    serial_write('L');
  #endif

I propose 
#ifdef LIMITS_TWO_SWITCHES_ON_AXES
    serial_write('T'); // ->  serial_write('L');
  #endif

**Comment by chamnit** [comment]
@LETARTARE : Thanks. Will push an update shortly.
