### ISSUE TITLE
Error if disable VARIABLE_SPINDLE definition

### ISSUE THREAD

**Issue by prezeskk** [gnea/grbl#14]
If VARIABLE_SPINDLE definition is commented the make is failed with this error:
**gcode.c: In function 'gc_execute_line'**
**gcode.c:1102:9: too many arguments to function 'spindle_set_state' spindle_set_state(SPINDLE_DISABLE,0.0);**

In code definition  **spindle_set_state** is
```
#ifdef VARIABLE_SPINDLE
  void spindle_set_state(uint8_t state, float rpm)
#else
  void spindle_set_state(uint8_t state)
#endif
```
I attach a zipped patched files
[patch.zip](https://github.com/gnea/grbl/files/541743/patch.zip)

**Comment by chamnit** [comment]
Fixed. Thanks Will!
