### ISSUE TITLE
I want to connect Arduino Mega   [4 pins / stepper / per axis]  (look image) how ?!!! 

### ISSUE THREAD

**Issue by savosik** [gnea/grbl#143]
![untitled-2](https://cloud.githubusercontent.com/assets/16825666/23376502/650054f0-fd3d-11e6-8f63-b89e431860cb.jpg)

**Comment by 109JB** [comment]
Grbl only supports drivers that have step and direction inputs.

**Comment by anonimou0** [comment]
I know this is a closed issue, but 2 and a half years have passed and I want to know if this is still valid.


Can I only use drivers with step/direction? Or can I use 4 pins, as previously asked?

**Comment by Norwegian-Gadgetman** [comment]
GRBL doesn't have a way to keep the 'pin state' needed to run directly.
In fact, GRBL doesn't even know how many microsteps that each step is divided into.

If you want direct control, you will either have to rewrite GRBL, search for another package that does what you want, or write your own.
