### ISSUE TITLE
SPI malfunction when steppers are moving slow

### ISSUE THREAD

**Issue by heise** [gnea/grbl#144]
Hello Chamnit,

I'm about to finish my GRBL 1.1f port to ATmega644, along with some nice additions (CNC handwheel/dial and analog joystick connection for jogging, realtime SPI transfer of XYZ position data to external 16x2 display, 32 additional I/Os through shift registers connected to SPI, button interface for overrides etc,). Everything works now, thanks to your great efforts in documentation of the source code.

BUT: I had to implement a workaround for the classic SPI transfer (write SPDR, poll for SPIF transmission complete flag to be set). 

When steppers move very slow, SPIF will (randomly) not be set by processor core, although transfer is complete long ago (checked with logic analyzer). So I made up a timeout loop to prevent freezes when polling SPIF.  There is absolutely no ISR involved and yes, I set SS port bit DDR to output. I also checked if SPI registers are used anywhere in your code. Nope.

This also happens on ramp start/end for faster moves. For testing, I removed all my firmware additions just to test only the SPI issue, SPI tx and SPIF poll loop directly in protocol_main_loop(), just after for(;;) . Still there, it happens even on a plain GRBL. Maybe because of interrupt nesting (sei(); in stepper ISR)? Any idea?

For sure I will publish my sources when I'm finished with my project.

BTW: is it allowed to pass gc_state.position to mc_line? This eases up my handwheel code:

<pre><code>
gc_state.position[dial_axis] += dial_delta_f; // update selected axis pos.   
mc_line(gc_state.position, pl_data); 
if (sys.state == STATE_IDLE) {  ...
  if (plan_get_current_block() != NULL) { ...
</code></pre>
Same applies to my joystick code, where I pass the ADC value to feed override in order to continuously control jog speed after move started by mc_line():
<pre><code>
loop...
 if (adc_value_has_changed) {
   sys.f_override = adc_value_scaled;
   plan_update_velocity_profile_parameters();
   plan_cycle_reinitialize();
  ...
..until joystick released
</code></pre>

Greetings, Carsten

**Comment by chamnit** [comment]
@heise : Sorry can't help you with this. I'm not familiar enough with how SPI works on AVRs to give you any advice. Given that this is related to a port with custom features, I'm closing this issue since it's not related to the main Grbl code. If you figure out what is causing the failed trigger, please let me know.
