### ISSUE TITLE
Missing config description/ Missing Lim in Status report

### ISSUE THREAD

**Issue by SteBuTOS** [gnea/grbl#148]
I recently switched from 9f to 1.1f to solve some issues with z-limit switch, but struggled by missing discription when issune $$ and also missing Limit Switch status withing status report.
I explecitely set the $10=19 before:
-----------------------------------------------------
Grbl 1.1f ['$' for help]
ok
ok
$0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=19
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=250.000
$101=250.000
$102=250.000
$110=500.000
$111=500.000
$112=500.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000
ok
ok
<Idle|MPos:0.000,0.000,0.000|Bf:15,126|FS:0,0|WCO:0.000,0.000,0.000>
ok
ok

**Comment by chamnit** [comment]
@SteBuTOS : Please read the Wiki. These changes have been outlined there.
