### ISSUE TITLE
svn1355 : $I=text => TEXT 

### ISSUE THREAD

**Issue by LETARTARE** [gnea/grbl#154]
I use
`$I=text`
and after 
`$I`
I get

> TEXT
always uppercase !
Is this normal ?

**Comment by JBSchueler** [comment]
Yes, all chars are converted to uppercase.
See [protocol.c](https://github.com/gnea/grbl/blob/master/grbl/protocol.c) line 144

**Comment by LETARTARE** [comment]
@JBSchueler
Thank you for the answer. 
But here it is information provided by the user and normally it would respect its text.

**Comment by chamnit** [comment]
I updated the $I description explaining capitalization, white space removed, etc.
