### ISSUE TITLE
Broken image links in Wiki.

### ISSUE THREAD

**Issue by Nandox7** [gnea/grbl#158]
Hi,

Spotted a couple broken image links in the wiki pages.

i.e: https://github.com/gnea/grbl/wiki/Connecting-Grbl

Would try and fix it but I can't find the images in github repo.

Cheers

**Comment by chamnit** [comment]
Nandox7: Most pics in the Wiki were linked to various Dropbox accounts through their public links, but Dropbox just removed them all this weekend. Which was awesome. I opened a new repo called gnea-Media, which will host all of the media content. People can issue pull requests to have it stored there. I fixed what I have access to.
