### ISSUE TITLE
Error.22 then using G1 command G0 works fine

### ISSUE THREAD

**Issue by akrauthammer** [gnea/grbl#167]
Hi

I get an error.22 when using the "G1" command! I get that it is somthing with the Feed rate, but how do I set that?

I am using gShield v5b, an Arduino Uno and have updated to Grbl v1.1.

**Comment by chamnit** [comment]
@akrauthammer : With an 'F' word, like 'G1 F100.0' in mm/min. It's modal and only needs to set once at initialization or when you want it to change.
