### ISSUE TITLE
What is the feedrate limit (lowest stepping rate)

### ISSUE THREAD

**Issue by samitray** [gnea/grbl#169]
I understand that on the high side grbl can pump out about 30khz, What about the lower limit?
I am running into feed rate issue for very a coarse setup. The requirement is to output step pulses
at few 2-10 Hz.. what is the lowest frequency that grbl can pump out reliably? 
Around 30Hz from rough observation, though i would like to know the precise value....

I have a timing belt setup (single axis) with steps per mm at 5.556
Belt is 8mm pitch on a 18 sprocket pulley attached to a nema 34 stepper
the stepper driver is at 800 steps/rev  800/(18X8) = 5.556

$100=5.556
$101=250.000
$102=250.000
>>>>>
$120=15.000
All other settings at default
when i send a jog command
$J=G91 G21 X20 F30.00 N1
the motion completes in under 4 seconds ( should take 40 seconds)
This is about 111 pulses in 40 seconds which is about 2.775 Hz

another jog command
$J=G91 G21 X10 F30.00 N2
completes in under 2 seconds ( should take about 20 sec)

So i give constant distances at different feed rates, till i get
proper time for travel... at about F360 and beyond i start getting
correct duration, this corresponds to about 30Hz as the lower limit

Cheers

**Comment by chamnit** [comment]
About 240 Hz with AMASS enabled (default) and 4 Hz without it. This is limited by the 16-bit timer.
