### ISSUE TITLE
How to wire for Stop/Start?

### ISSUE THREAD

**Issue by jahnj0584** [gnea/grbl#170]
Is there a way to hardwire a switch to send a STOP command? Thinking of my E-stop button, which has NO AND a NC terminal pair on it. When you close the switch, it opens the circuit (ie: Power in to the drivers) and closes the NO circuit, so my idea is that path is closed and would send the signal to the arduino/GUI to stop sending commands. The power shut off will physically stop the machine. After the switch is flicked back to normal, the GUI could just be in an alarm state and require a set up.

**Comment by chamnit** [comment]
Closing. Duplicate post.
