### ISSUE TITLE
Support for XYUV hotwire foam cutters

### ISSUE THREAD

**Issue by dsbeach** [gnea/grbl#174]
I'm in the process of constructing a hotwire foam cutter for building model airplane wings. @skwee has a port of grbl-0.8 at [https://github.com/skwee/grbl-xyuv](https://github.com/skwee/grbl-xyuv).

I'd like to take advantage of ongoing grbl enhancements for new boards and potential bug fixes.

Is there interest in adding 'official' support for XYUV hardware? I'm in a position to possibly contribute, and definitely test.

David

**Comment by chamnit** [comment]
@dsbeach : The next Grbl project will support multiple axes beyond XYZ. It's a trivial feature to add if the axes are not dynamically coupled (most are). But, Grbl on the Arduino Uno is completely maxed out and will not support more than 3 axes. The next project will support the Arduino Zero's SAMD21-compatible boards and will have some support on the Mega2560.
