### ISSUE TITLE
$20 - Soft limits, boolean not working?

### ISSUE THREAD

**Issue by patgadget** [gnea/grbl#177]
Hi,
i am using GRBL in Laser Mode
i also have remove the homing sequence for the Z-Axis.
and i also have comment out the HOMING_FORCE_ORIGIN to have a 0,0 in my lower left corner.

My Homing sequence work find, but i can ask to go over my soft limit without any alarm?
any idea?

Thanks
Pat

**Comment by chamnit** [comment]
@patgadget : Not sure what you are asking. The point of soft limits is to stop you from crashing your machine, so an alarm is the correct response. If you are asking how to jog without exceeding soft limits, Grbl v1.1 new jogging mode will not throw an alarm when you command a motion outside of it. It'll just return an error. This new feature is outlined in the documentation.

**Comment by patgadget** [comment]
Thanks i found my problem, i reverse the X and Y in the $130 and $131 parameter.
Pat
