### ISSUE TITLE
Some general discussion about programming language and coding style

### ISSUE THREAD

**Issue by jsb1** [gnea/grbl#18]
This is a bit off topic but might be useful when starting a version 2.0 in far future.
I'm not really fan of plain c programming. But on controllers it is ok. Especially with that clean coding style we find in grbl.
I thing using C++ in Arduino style is absolutely a no-go. Performance and flexibility of most libraries ist simply :-1: 
But recently I discovered C++ templates for controller programming. They are basically "macros on steroids".
You can keep all code in headers and instantiate it in a single main.cpp. 
That makes less files, less hassle with declarations and less global variables.
GCC (AVR-GCC too) can do amazing optimizations on that kind of code. Nearly all small functions and all those called from only one place get inlined and globally optimized. I'm often surprized by very small binary output.
Biggest problem with C++ is not language but programmers. C++ programmers tend to make code overly abstract and and complicated - just because the language allows that.

**Comment by chamnit** [comment]
@jsb1 : I'm a aerospace researcher by trade, and I use C/Fortran whenever I need to create high performance code that things like Python or Matlab can't do. For the most part, I've never had the need to use C++ nor needed to learn it in any great depth, mainly for the overly abstract and complicated reasons you gave.

I can see how C++ can be useful for larger software projects with abstractions and classes, but I never do large projects. I tend to keep things small and modular, which micro controller programs are usually. For that, C is fine. I also try to stick to the NASA-JPL rules for mission-critical coding, whenever I can (http://lars-lab.jpl.nasa.gov). They explicitly only use C.

I don't particular like to deal with large and complex pieces of software. They can be very hard to maintain and can easily be inflexible or impossible to alter. I don't intend to make v2.0 large or bloated, so I plan on sticking with C until there is a good reason to change it.
