### ISSUE TITLE
Resetting Mpos coordinates

### ISSUE THREAD

**Issue by ghartc** [gnea/grbl#182]
Hi - I am looking for a command/method to change MPosition coordinates - e.g. M position has some non-zero values, and I would like to zero them - x0y0z0 w/o moving the machine. Thanks.

**Comment by chamnit** [comment]
@ghartc : Grbl intentionally does not allow this due the high likelihood of misuse and would make homing useless. You will want to learn how to use work coordinate systems to set multiple origins in your machine.

**Comment by Harvie** [comment]
I am not sure if that is reliable approach, but when i do hard reset, it also resets my MPos...

**Comment by Harvie** [comment]
It is important for me, because i have machine without limit switches, but i still occasionaly need to debug g-code using G53...

**Comment by chamnit** [comment]
@Harvie : This is a very old thread you've resurrected. The answer is the same.

**Comment by Harvie** [comment]
I know. I fully agree with fact that people should not be allowed to reset MPos.
But just for the record i've added that there is legitimate reason to do so and that it can be done by hard reseting if someone ever needs it.

Will hard reset always reset MPos? Or there are some cases in which it will fail?

**Comment by chamnit** [comment]
A hard reset will always reset MPos.
