### ISSUE TITLE
Inconsistent format in csv files

### ISSUE THREAD

**Issue by 109JB** [gnea/grbl#186]
The format in the comma-delimited files for error codes, alarm codes, etc., have an inconsistent format.  In particular, the error code file differs from the others in that quotation marks are not used. For example, a line from the error code .csv is as follows:

1,Expected command letter,G-code words consist of a letter and a value. Letter was not found.

whereas a line from the alarm code csv is:

"1","Hard limit","Hard limit has been triggered. Machine position is likely lost due to sudden halt. Re-homing is highly recommended."

where each field is surrounded by quotes. The other csv files use this same format.

In order to make the files consistent, I would recommend that the error code csv be modified to this same format. 

Thanks,

John B

**Comment by chamnit** [comment]
Finally cleaned up in tonight's push.
