### ISSUE TITLE
Arduino is crashed when setting position by G-Code.

### ISSUE THREAD

**Issue by TsubokuLab** [gnea/grbl#189]
I'm used Grbl v0.9 in my application and now updated to v1.1f.
but, my Arduino is crashed when setting position by G-Code.
I tried simple test using Arduino serial monitor.
Do I have any mistakes?

Left: sent messages.
Right: receive messages.(Arduino Serial Monitor)
![com3 arduino_genuino uno 2017-05-06 03 05 24](https://cloud.githubusercontent.com/assets/1589819/25758886/2c98c694-320b-11e7-8f43-4c2ac853a453.png)

When tested again, it received error with garbled characters.
![com3 arduino_genuino uno 2017-05-06 03 06 41](https://cloud.githubusercontent.com/assets/1589819/25758896/31f07f24-320b-11e7-97b4-7bd5433a4a14.png)

This is version and config info. (from $i and $$ commands)
![com3 arduino_genuino uno 2017-05-06 03 14 08](https://cloud.githubusercontent.com/assets/1589819/25758899/35711a00-320b-11e7-8ae6-fb2d6e9b7d13.png)

**Comment by chamnit** [comment]
You are exceeding the maximum step rate supported by nearly 3x. Grbl can do up to 30kHz, as stated on the front page and the wiki. You are at about 84kHz (250step/mm * 20000 mm/min / 60 sec/min). This is limited by how fast the Arduino CPU is.

**Comment by TsubokuLab** [comment]
Thank you so much.
You were right. and sorry for my poor question.
