### ISSUE TITLE
Spindle accessory state is not always reported

### ISSUE THREAD

**Issue by winder** [gnea/grbl#19]
If I send the command `M3G1X1F1S1` the override status report gives me:
`<Idle|MPos:1.000,0.000,0.000|Bf:15,128|FS:0,1|Ov:100,100,100>`

Sending a `0x9E` still toggles the spindle speed between 1/0 as expected.

**Comment by chamnit** [comment]
@winder : Thanks Will. Fixed it. It was due to setting the minimum PWM value to zero, when it should have been 1.  It caused an error in the PWM calculation when near the minimum rpm.
