### ISSUE TITLE
Real-time position tracking with grbl

### ISSUE THREAD

**Issue by cedricjeanty** [gnea/grbl#190]
I am sorry if this is the wrong place to post this question, but I hoped someone may be able to help me add some interesting functionality to the grbl motion control, which could be applicable to multi-axis robots (but probably not CNC).
I am using the grbl-MEGA fork to control a delta robot like this: https://youtu.be/Gv5B63HeF1E
I can issue path-based motion control, but I would like to incorporate a way to follow a target position updated in real-time. The goal is to tell the robot to track an object, whose position is changing constantly. I have prototyped the robot and tracking system, using the jog commands in grbl, but I cannot get the performance I need by issuing rapid, short jog commands, as there is too much latency, and the robot follows the path in the buffer rather than taking a short-cut directly to the updated position. I have tried the jog cancel commands, but it issues a EXEC_MOTION_CANCEL, resulting in jerky motion. I think a jog_update() command, or similar that clears the planner buffer, and calls planner_recalculate() may be enough, or go one level deeper and clear the stepper segment buffer, and re-calculate within the last block, which could improve performance.
Am I going in the right direction? Does anyone have any advice for me?
Thank you so much for your help. I am very impressed with the grbl code so far!

**Comment by chamnit** [comment]
@cedricjeanty : Robotics path control is a different problem. The path isn't critical as it is in CNC. Grbl is built to have deterministic path and motion control, which isn't the same. You can hack Grbl to do what you want, but its not going to be an optimal way to do it.

If you still want to use Grbl, you either need to hack the source code to do what you want or use the jogging commands in the way that is laid out in the jogging wiki page for joysticks. If you do it right, you should have fairly low latency and no jerkiness. I can vouch for this behavior from bench tests of a simple analog joystick controlling 3-axes simultaneously.
