### ISSUE TITLE
Laser focus mode

### ISSUE THREAD

**Issue by thawkins** [gnea/grbl#191]
When operating with a laser, it would be very usefull to be able to switch the laser on at a low power setting so that it can be adjusted for focus, position etc. Possibly a $variable for the power level, defaulting to 1%,  and a command to turn it on and off in focus mode.

**Comment by electrokean** [comment]
@thawkins there are instructions in the laser mode docs on how to acheive this
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode
