### ISSUE TITLE
Error:17  Laser Mode cannot be enabled

### ISSUE THREAD

**Issue by charleswho** [gnea/grbl#192]
Hi, I tried using $32=1 to enable Laser Mode. ( GRBL V1.1 / Arduino Uno) But GRBL responded "Error: 17 ". I have  VARIABLE_SPINDLE enabled. I cannot find the explanation for that in "GRBL Interface". Please help me! Thank you so much!

**Comment by chamnit** [comment]
@charleswho : I've updated the wiki page with error 17. Not sure why it wasn't there. (https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#grbl-response-messages)

This means that you don't have VARIABLE_SPINDLE enabled. Make sure you are editing the correct config.h file in the Arduino library folder.

**Comment by Samlokihel** [comment]
boa noite não consigo resolver este problema do error 17
