### ISSUE TITLE
Microstep problems with high settings of steps/mm

### ISSUE THREAD

**Issue by oMtQB4** [gnea/grbl#194]
Hi,

I'm facing a problem that I cannot choose 1600 steps/mm for x, y and z axis. If I set them to 1600 steps/mm (even without connecting anything except the Arduino UNO), I cannot move the axes for the amount I want them to move. After one try, I have to reset GRBL.

This is the setup that does not work:
> $0 = 10    (Step pulse time, microseconds)
> $1 = 25    (Step idle delay, milliseconds)
> $2 = 0    (Step pulse invert, mask)
> $3 = 0    (Step direction invert, mask)
> $4 = 0    (Invert step enable pin, boolean)
> $5 = 0    (Invert limit pins, boolean)
> $6 = 0    (Invert probe pin, boolean)
> $10 = 1    (Status report options, mask)
> $11 = 0.010    (Junction deviation, millimeters)
> $12 = 0.002    (Arc tolerance, millimeters)
> $13 = 0    (Report in inches, boolean)
> $20 = 0    (Soft limits enable, boolean)
> $21 = 0    (Hard limits enable, boolean)
> $22 = 0    (Homing cycle enable, boolean)
> $23 = 0    (Homing direction invert, mask)
> $24 = 25.000    (Homing locate feed rate, mm/min)
> $25 = 500.000    (Homing search seek rate, mm/min)
> $26 = 250    (Homing switch debounce delay, milliseconds)
> $27 = 1.000    (Homing switch pull-off distance, millimeters)
> $30 = 1000    (Maximum spindle speed, RPM)
> $31 = 0    (Minimum spindle speed, RPM)
> $32 = 0    (Laser-mode enable, boolean)
> $100 = 1600.000    (X-axis travel resolution, step/mm)
> $101 = 1600.000    (Y-axis travel resolution, step/mm)
> $102 = 1600.000    (Z-axis travel resolution, step/mm)
> $110 = 2000.000    (X-axis maximum rate, mm/min)
> $111 = 2000.000    (Y-axis maximum rate, mm/min)
> $112 = 800.000    (Z-axis maximum rate, mm/min)
> $120 = 300.000    (X-axis acceleration, mm/sec^2)
> $121 = 200.000    (Y-axis acceleration, mm/sec^2)
> $122 = 100.000    (Z-axis acceleration, mm/sec^2)
> $130 = 200.000    (X-axis maximum travel, millimeters)
> $131 = 200.000    (Y-axis maximum travel, millimeters)
> $132 = 200.000    (Z-axis maximum travel, millimeters)

Is there any problem I do not see?

I tried:
- different g code senders
- connected and disconnected stepper drivers
- different USB cables
- two different Arduino UNOs (one original)
- GRBL 1.1f, 1.1e, 0.9j
- different configurations for steps/mm (800 works, 1000 works, 1200 works, 1400 does not work, 1600 does not work)

I encountered a strange error. If I set y to 800, x to 800 and z to 1600, everything works fine (grbl 1.1f). The only differences for the z-axis are the acceleration and the speed. So, I tried different accelerations and it worked for the following setting:
> $0 = 10    (Step pulse time, microseconds)
> $1 = 25    (Step idle delay, milliseconds)
> $2 = 0    (Step pulse invert, mask)
> $3 = 0    (Step direction invert, mask)
> $4 = 0    (Invert step enable pin, boolean)
> $5 = 0    (Invert limit pins, boolean)
> $6 = 0    (Invert probe pin, boolean)
> $10 = 1    (Status report options, mask)
> $11 = 0.010    (Junction deviation, millimeters)
> $12 = 0.002    (Arc tolerance, millimeters)
> $13 = 0    (Report in inches, boolean)
> $20 = 0    (Soft limits enable, boolean)
> $21 = 0    (Hard limits enable, boolean)
> $22 = 0    (Homing cycle enable, boolean)
> $23 = 0    (Homing direction invert, mask)
> $24 = 25.000    (Homing locate feed rate, mm/min)
> $25 = 500.000    (Homing search seek rate, mm/min)
> $26 = 250    (Homing switch debounce delay, milliseconds)
> $27 = 1.000    (Homing switch pull-off distance, millimeters)
> $30 = 1000    (Maximum spindle speed, RPM)
> $31 = 0    (Minimum spindle speed, RPM)
> $32 = 0    (Laser-mode enable, boolean)
> $100 = 1600.000    (X-axis travel resolution, step/mm)
> $101 = 1600.000    (Y-axis travel resolution, step/mm)
> $102 = 1600.000    (Z-axis travel resolution, step/mm)
> $110 = 2000.000    (X-axis maximum rate, mm/min)
> $111 = 2000.000    (Y-axis maximum rate, mm/min)
> $112 = 800.000    (Z-axis maximum rate, mm/min)
> $120 = 10.000    (X-axis acceleration, mm/sec^2)
> $121 = 10.000    (Y-axis acceleration, mm/sec^2)
> $122 = 10.000    (Z-axis acceleration, mm/sec^2)
> $130 = 200.000    (X-axis maximum travel, millimeters)
> $131 = 200.000    (Y-axis maximum travel, millimeters)
> $132 = 200.000    (Z-axis maximum travel, millimeters)`

If I change the accerations to 100 instead of 10, another strange bug appears. When I move one axis, another moves with it. Even with no axes connected, the position of two axes changes.

Is it a common problem? I couldn't find any documentation of microsteps.

**Comment by chamnit** [comment]
Grbl officially supports up to 30kHz step rates, as described on the front page of the site and wiki. Unfortunately, checks to warn you that your settings exceed the max step rate is disabled by default in config.h. Mainly to save precious flash space. Currently you are running at 53.3 kHz. Way above what the Arduino MCU can do.
