### ISSUE TITLE
grbl with AVR studio

### ISSUE THREAD

**Issue by digoenes** [gnea/grbl#200]
How can I compile grbl version 1.1 without a runtime error? Version 0.9 is OK.
Compiling verion 1.1 is OK too, but running the firmware always restarts processor
by calling certain commands. Example: $$

**Comment by chamnit** [comment]
Closing since this is an unsupported way of compiling Grbl. I dont use AVR studio so I can't help you there. Hopefully someone that has had experience with it will post a response for you.
