### ISSUE TITLE
volatile uint8_t sys_rt_exec_debug definition missing in main.c ?

### ISSUE THREAD

**Issue by mentyl** [gnea/grbl#203]
Can't compile in DEBUG "volatile uint8_t sys_rt_exec_debug" definition is missing.

**Comment by swarfer** [comment]
it is defined in system.h
are you sure you have all of the current code?

**Comment by mentyl** [comment]
Yes, simple search this repository "sys_rt_exec_debug" only " extern volatile uint8_t sys_rt_exec_debug;" in system.h i us Visual Studio Release works fine

**Comment by chamnit** [comment]
@mentyl : Thanks. Verified the missing line and added to the next push.
