### ISSUE TITLE
Not working on mini pro 8Mhz

### ISSUE THREAD

**Issue by akiAbtahi** [gnea/grbl#207]
I was trying to run grbl on a mini pro running at 8 MHz (3.3V). The response is strange, for instance it requires two CR after $ to respond. For $$ it responds with error 3 ...... , responds to ? correctly. Anybody have any ideas on how to resolve this?
Thanks

**Comment by JBSchueler** [comment]
8Mhz will decrease performance but the uart communication should be ok.
What kind of uart chip does it have (e.g. FTDI)?

**Comment by akiAbtahi** [comment]
It's a FTDI. You're right it's probably a problem with serial comms. Other sketches with lower baud work fine so I should try to reduce the baud rate in grbl. I'll try this evening,
Thank You!

**Comment by chamnit** [comment]
8Mhz builds are not supported, nor have been tested. Theoretically it should work. If you are using the Makefile, you'll need to edit it to denote 8 MHz.
