### ISSUE TITLE
Arduino duemilanove and Binary sketch size

### ISSUE THREAD

**Issue by izeldur** [gnea/grbl#212]
Try build and upload grbl 1.1f to my Arduino duemilanove and have error of big sketch size:

`avr-objcopy -O ihex -R .eeprom /tmp/build5586395876159723766.tmp/grblUpload.cpp.elf /tmp/build5586395876159723766.tmp/grblUpload.cpp.hex 
Binary sketch size: 31,046 bytes (of a 30,720 byte maximum)`

`processing.app.debug.RunnerException: Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.`

**Comment by chamnit** [comment]
The default build will fit on a Duemilanove. IF you add things like CoreXY or parking, you can exceed this. Otherwise, you can burn the Uno boot loader on your Duemilanove to free up 1KB. See Wiki FAQ on this.
