### ISSUE TITLE
Max/Min limit switches

### ISSUE THREAD

**Issue by komradebob** [gnea/grbl#217]
It appears, based on the board I have (Woodpecker CNC) that max and min limit switches can be supported. Is this in fact the case? 

If not, could it be?

Additionally, what would the impact be of changing the hard limit message to say which axis/end was triggered?

**Comment by jahnj0584** [comment]
You just wire them in series to the same pin. No way or saying which end because they both trigger the same port on the arduino. It should be pretty obvious which side it is though....

**Comment by komradebob** [comment]
The woodpecker CNC board uses separate pins for max/min, which can make things like figuring out how big the workspace is much easier.

**Comment by chamnit** [comment]
There are not enough pins on the 328p to support max/min limit switches. If your woodpecker board has a 328p processor, then they are tied to the same pin.
