### ISSUE TITLE
Port for ATmega64 ?

### ISSUE THREAD

**Issue by voltlab** [gnea/grbl#222]
It is possible ? Looks ok, twice as many SRAM/ROM/EEPROM. Only 8 ext.interupts and 1 SPI, can it be an issue?

**Comment by chamnit** [comment]
No reason why it shouldn't work. External interrupts are only used for hard limit switch detection and input command buttons, while SPI isn't used. I don't plan on supporting this chipset though, since it's not commonly available for hobbyists, unlike the Mega2560.
