### ISSUE TITLE
GRBL 1.1 burns not all.

### ISSUE THREAD

**Issue by UmkaAP** [gnea/grbl#227]
Good afternoon. Prompt where to dig. Firmware GRBL 0.9 small details
grbl burns, and 1.1 ignores them. Why is there a difference of $32=1 or $32=0.
![grbl](https://user-images.githubusercontent.com/30045643/28020311-96a722e2-658c-11e7-876e-5b9c33ba8c33.jpg)

**Comment by chamnit** [comment]
Make sure your $30 and $31 rpm settings are the same as Grbl v0.9. And see the [wiki laser page](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Laser-Mode). It explains what $32 does.

**Comment by UmkaAP** [comment]
The problem was the PWM frequency. Version 0.9 uses 8 kilohertz, and in version 1.1 the default is 1 kHz.
