### ISSUE TITLE
Comment Mistake and added PWM speed

### ISSUE THREAD

**Issue by McNugget6750** [gnea/grbl#23]
In cpu_map.h I added the no prescaler pwm speed and corrected the prescaler description in the comments according to the AVR datasheet. The last two lines are 1/64 and 1/256.
I DID NOT CALCULATE THE NEW ACTUAL FREQUENCIES!

```
// Prescaled, 8-bit Fast PWM mode
#define SPINDLE_TCCRA_INIT_MASK   ((1<<WGM20) | (1<<WGM21))  // Configures fast PWM mode
#define SPINDLE_TCCRB_INIT_MASK   (1<<CS20)                  // no prescaler! Used for K40 CO2 Laser
// #define SPINDLE_TCCRB_INIT_MASK   (1<<CS21)                  // 1/8 prescaler -> 7.8kHz (Used in v0.9)
// #define SPINDLE_TCCRB_INIT_MASK   ((1<<CS21) | (1<<CS20)) // 1/64 prescaler -> 1.96kHz
// #define SPINDLE_TCCRB_INIT_MASK   (1<<CS22)               // 1/256 prescaler -> 0.98kHz
```

**Comment by chamnit** [comment]
@McNugget6750 : Thanks, but I think you may have looked at the Timer1 pre-scalers, not the Timer2 pre-scalers. They look similar but they are indeed different. How it is written in the source code now is correct.

I'll add your line for disabling the prescaler for your K40 machine. Not sure why you need that high of a frequency. In my conversations with other laser OEMs, it's better to have a lower frequency, but I think that may depend on how the electronic circuitry works.
