### ISSUE TITLE
Micro not compiling ?

### ISSUE THREAD

**Issue by HypericumPerforatum** [gnea/grbl#24]
GRBL 1.1 did compile fine for the Uno and the Nano but did not compile for the Arduino Micro.
Should it compile ? The Micro has an ATmega 32U4.
Am I doing something wrong ?
Is it possible ? Can you push me in the right direction ?

P.S. This is the error the Arduino IDE gave :

[GRBL problems.txt](https://github.com/gnea/grbl/files/553296/GRBL.problems.txt)

Thank You !

**Comment by chamnit** [comment]
@HypericumPerforatum : Grbl is designed to work on a 328p processor only. Not a 32U4. I don't plan on supporting this chip. Sorry!
