### ISSUE TITLE
G28 Homing only Z

### ISSUE THREAD

**Issue by yoshinator13** [gnea/grbl#240]
On my CNC, I have a tool that impacts the work surface instead of drilling into it. As a result, my Z axis occasionally becomes uncalibrated. I could home after every impact, but it would increase the time significantly. I did some research, and I believe the G28 command is typically used for homing only the Z axis. This would significantly reduce time.

**Comment by chamnit** [comment]
G28 has multiple definitions, sometimes homing and other times moving to a pre-defined position. Grbl defines it as the latter. Not as homing. It follows the LinuxCNC standard, as clearly stated in the wiki. 

I would invest time into preventing your machine from getting uncalibrated instead. It'll save you a lot of time and energy by doing so. If you can't or won't, you can always use G38.x probing cycles and set a tool length offset by the uncalibrated distance.

**Comment by chamnit** [comment]
Also, look in config.h for the line `#define HOMING_SINGLE_AXIS_COMMANDS`. I installed this relatively recently, but have not seen anyone use it yet. But, I would still invest time in ensuring your machine stay calibrated from impacts with a better drive system.

**Comment by langwadt** [comment]
connect the z limit switch to the probe input and do a g38.2...  G10... instead?

**Comment by yoshinator13** [comment]
> Also, look in config.h for the line #define HOMING_SINGLE_AXIS_COMMANDS. I installed this relatively recently, but have not seen anyone use it yet. But, I would still invest time in ensuring your machine stay calibrated from impacts with a better drive system.

@chamnit This looks like it will work perfectly. I was did not see this in the config file last time I looked.
