### ISSUE TITLE
Constant Error 22 since updating

### ISSUE THREAD

**Issue by cawoodm** [gnea/grbl#255]
Just updated to Grbl 1.1 and keep getting error 22 with G01.

Once I manually do a G01 with F it works from then on... and then the same issue starts with G02.

So what is up? Does GRBL 1.1 really have no default feed rate? How would I set it once without doing G01?

**Comment by jahnj0584** [comment]
What sender are you using

**Comment by gerritv** [comment]
1.1 no longer has a default Feed Rate. Set one in your gcode file, or better yet use a post that does this for you.
A line at top of file with just F<speed> is enough

**Comment by PicEngraver** [comment]
You can also just set a feed rate in a startup block $N=.
ex: $N1=Fxxxx, when xxx = your desired feed rate.
This way works when you want to jog with no file loaded upon startup.

**Comment by cawoodm** [comment]
Grbl Controller 3.6.1
It doesn't allow any preamble so it's a bit of a pain but I've had more success with it than UGS or Chrome's gcode-sender.

**Comment by cawoodm** [comment]
$N1=180 returns error:1

**Comment by PicEngraver** [comment]
You forgot to include the "F"  -  F180
