### ISSUE TITLE
compile error Homing

### ISSUE THREAD

**Issue by markotime** [gnea/grbl#258]
Compile errors grbl 1.1 "Required HOMING_CYCLE_0 not defined."  in grbl.h.
IDE 1.6....
I have no idea what this means....   any ideas? thanks / mark in BC

**Comment by chamnit** [comment]
Have you edited your config.h file? If so, please re-read the section about setting up your homing cycle again.

**Comment by markotime** [comment]
Thanks - sorry, but where is that section?

**Comment by chamnit** [comment]
If you didn't alter any files, then make sure you have removed all prior Grbl installations from the arduino library folder, as the instructions state. The arduino ide will get confused if you don't.

**Comment by markotime** [comment]
Got it.  Had missed the part about upload, under examples.  Thanks.  Sign on forehead - rtfm
