### ISSUE TITLE
CoreXY homing wrong direction

### ISSUE THREAD

**Issue by chamnit** [gnea/grbl#26]
https://github.com/grbl/grbl/issues/1107#issuecomment-256955403

Works on v0.9j, but not v1.1. Need to do a diff.

**Comment by LCPINAGE** [comment]
@chamnit can I help here somehow?

**Comment by chamnit** [comment]
@LCPINAGE : Yes. You can help by testing it when I issue the fix, but I'm pretty busy with work at the moment. Hoping to address all remaining issues later this week.

**Comment by LCPINAGE** [comment]
Great, thanks!

**Comment by chamnit** [comment]
@LCPINAGE : I'm having trouble finding anything wrong with the code, or rather any significant differences between the CoreXY in v0.9j and v1.1, that would cause the end of your homing cycle to move the other direction at the end of it. Do you have any startup lines active? Are you certain that your setting are identical between v0.9j and v1.1?

**Comment by LCPINAGE** [comment]
@chamnit  working on it at this momment, will double check and let you know!

**Comment by chamnit** [comment]
@LCPINAGE : I ended up bench testing this issue and was able to reproduce the problem. I found the bug and have fixed it. It'll be in the next push. Thanks for being patient.

**Comment by LCPINAGE** [comment]
@chamnit great!!!!!!! Thank you for this awesome job overall!!!
