### ISSUE TITLE
Acceleration Profile

### ISSUE THREAD

**Issue by StrictlyTech** [gnea/grbl#262]
I am trying to completely understand how to acceleration profile is calculated and being called.  I have read through the entire source code for motion_control.c and stepper.c.  However, I am still not completely understand how the acceleration is calculated.  

Can anyone give me a clear understanding as to what's going on?

**Comment by chamnit** [comment]
Everything is laid out in the source files, especially stepper.c and planner.c. Please study them thoroughly. In short, Grbl computes constant acceleration profiles and solving for an optimal plan in real-time is not as simple as you may think.
