### ISSUE TITLE
Arc acceleration

### ISSUE THREAD

**Issue by StrictlyTech** [gnea/grbl#263]
When going from a straight line into an arc, does GRBL slow down, speed up, or maintain the acceleration?  In other words, does the acceleration increase, decrease, or neither when the tool comes out of the straight line movement into an arc movement, such as when cutting a slot?

Thanks in advance

**Comment by chamnit** [comment]
All of the above. Grbl converts the arc into small line segments and executes them that way. It'll always try to maintain the maximum speed depending whats in the planner at any given point.
