### ISSUE TITLE
why M5 couldn't turn off the spindle

### ISSUE THREAD

**Issue by mopplayer** [gnea/grbl#267]
0.9a version could work with M3(on),M5(off)
But 1.1 version didn't work...

**Comment by chamnit** [comment]
Depends on if you had variable spindle enabled in your very old v0.9a version, which was never a master version and only a developmental one. In the actual v0.9 release and later, pins D11 and D12 swapped to access the hardware PWM on D11, so spindle speed can be output as various voltage levels. See the configuration page and config.h on how to revert it to the old way.
