### ISSUE TITLE
Cycle start/hold buttons only have effect while file is already sent 

### ISSUE THREAD

**Issue by jahnj0584** [gnea/grbl#269]
Should A2 not start a file as long as it's loaded? As it stands it only works as a "resume" button and not a "cycle start" button. 

Hold makes sense obviously. A0 reset works no matter what state its in.

**Comment by langwadt** [comment]
grbl can't start running a file before the PC starts sending it

**Comment by jahnj0584** [comment]
Why is that?

**Comment by terjeio** [comment]
limited memory (RAM) - files are streamed to grbl not loaded
