### ISSUE TITLE
error: 'N_AXIS' was not declared in this scope

### ISSUE THREAD

**Issue by dbprof** [gnea/grbl#270]
While compiling...
In file included from /home/user/Arduino/laser-engraver-2/laser-engraver-2.ino:5:0:
/home/user/Arduino/libraries/grbl/planner.h:41:18: error: 'N_AXIS' was not declared in this scope
   uint32_t steps[N_AXIS];    // Step count along each axis

**Comment by chamnit** [comment]
There is no laser-engraving-2.ino file in the Grbl source. Grbl only uses the Arduino IDE to facilitate easy compiling and uploading. It is not compatible with INO code.
