### ISSUE TITLE
Cannot flash with arduino IDE

### ISSUE THREAD

**Issue by jahnj0584** [gnea/grbl#271]
![20170918_203428](https://user-images.githubusercontent.com/17396492/30570111-4dae20ee-9cb5-11e7-9330-e5c6e832e888.jpg)

Tried flashing for 2 axis homing (no Z) and 250% over rides. I only edited the config file and those two relevant lines but it gives other errors. I had cleaned out the IDE libraries so it's not contaminated by old files

**Comment by neilferreri** [comment]
@jahnj0584 How did you modify the config?  Looks like you don't have a `#define HOMING_CYCLE_0`

**Comment by chamnit** [comment]
This happens be if you don't clear out the files or if you add the wrong folder. Please follow the directions exactly.

**Comment by jahnj0584** [comment]
i opened config.h in notepad++ and commented the first homing cycle, then changed the 1 to a 0 on the next line (for x y axis). Saved

Then added THAT grbl folder to the arduino IDE and tried flashing it.

**Comment by neilferreri** [comment]
@jahnj0584 What are you uploading?  It looks like you have your own sketch.  Are you running the example, "GrblUpload"?  That is what you should be doing.  The grbl folder, with the modifications you made, should go in your "libraries" folder. Make sure there are no other instances of grbl in that folder.  The only thing you need open in the IDE is "grblUpload".

**Comment by jahnj0584** [comment]
It's all fixed now. I was not doing step 4. It flashed properly and does home now with two axis. There were some errors in the arduino but all from files I never opened or touched.
