### ISSUE TITLE
Cannot change configurations

### ISSUE THREAD

**Issue by MWBO1** [gnea/grbl#273]
Dear GitHub-ers,

I just started a project and was implementing grbl. I was trying to change the configurations to make my motors turn the right amount of degrees. I opened the file defaults.h and made a profile for my machine. I am using a 1.8 deg/step motor, so I set the steps_per_mm variable to 200 on all three axis. I changed the DEFAULTS_GENERIC to my configuration and also tried changing changing the generic defaults
with the following configurations:
  #define DEFAULT_X_STEPS_PER_MM 200.0
  #define DEFAULT_Y_STEPS_PER_MM 200.0
  #define DEFAULT_Z_STEPS_PER_MM 200.0

When I tried jogging my x motor 1 mm it still turns around 450 deg, corresponding to 250 steps.
When I typed typing $$ in my command software (I use Universal G-Code Sender) it returns the parameters:
$100=250.000
$101=250.000
$102=250.000
corresponding to the steps per mm for x, y and z.

How can I change these values?

Thank you in advance

**Comment by chamnit** [comment]
Please read the wiki [page](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration) on how to setup Grbl. There, it will explain how to program your settings and restore the EEPROM to defaults as well.
