### ISSUE TITLE
WIKI Homing Cycle 

### ISSUE THREAD

**Issue by WAMason** [gnea/grbl#280]
I'm not sure if this is the correct way to raise this question.  I'm reading the "Set up the Homing Cycle" WIKI page [https://github.com/gnea/grbl/wiki/Set-up-the-Homing-Cycle](url).

In the "Homing Cycle Steps" and "Homing speed" sections it references $24 as the fast rate and $25 as the slower rate.

From the "Grbl v1.1 Configuration" page [https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration](url), $24 (Homing feed) "... is that slower feed rate."   and $25 (Homing seek) seems to be the faster rate.

Am I misreading the documents? (Not unheard of....)

Thanks,
WAMason

**Comment by chamnit** [comment]
Fixed. I was unaware of this 'Setup the Homing Cycle" wiki page. It looks like it was added by a couple of users. The values were changed to be in line with the configuration page.
