### ISSUE TITLE
Z-Limit supervising problem 

### ISSUE THREAD

**Issue by frankkaktus** [gnea/grbl#283]
There seems to be a problem using several times the probe command G38.2. At first time it works fine and find the switch at -36.5 mm. Repeating exactly the same steps "ALARM: 2" message is received (see trace). The limit of the maschine is -69 mm.

It is not happens if the probe is located in a high position (about >-20 mm). It could be depend on the setting of the PartZero setting for Z. 

[Z-Probe-Issue.log](https://github.com/gnea/grbl/files/1346318/Z-Probe-Issue.log)

**Comment by chamnit** [comment]
You have a work coordinate offset. The alarm code thrown was Alarm:2, which is a soft limit alarm. Your probe commands operate in the work coordinate frame and the last one exceed the machine volume.
