### ISSUE TITLE
modifying 30khz step rate limit (20mhz uno)

### ISSUE THREAD

**Issue by samitray** [gnea/grbl#285]
currently running grbl compiled with FCPU 20000000 on 328p with 20mhz crystal.
grbl has the max rates capped to 30khz, however i could only locate commented 
out defines for MAX_STEP_RATE_HZ. There are DEFAULT_X_MAX_RATE 
defines but they are rate for individual axis.
If max step rate is to be set around 40k, what needs to be changed?

Cheers

**Comment by 109JB** [comment]
There is no default coded limit. The step limit is set by your maximum rate and steps/mm settings. If you have changed the crystal then you should be able to increase your maximum rate without any code changes. Only changes to the $ settings should be needed.

**Comment by chamnit** [comment]
The 30kHz is a primarily a function of how quickly the AVR processor can service a step interrupts and the amount of processing Grbl needs to do when under maximum streaming conditions.. Grbl does not actively check for the 30kHz step limit. It's a recommended limit that I've tested to cover most foreseeable circumstances.
