### ISSUE TITLE
Gcode G81 works great with grbl/bCNC

### ISSUE THREAD

**Issue by sergio1b** [gnea/grbl#290]
Hi all,
one month ago I was very surprise to see that grbl1.1/bCNC0.9/arduino Uno+cnc shield v.3  did a very nice holes and work with Gcode using G81...?..!
This Gcode was generated by Freecad 0.17 set with Linuxcnc as post processor
tool : driller 5mm for hole 5mm 
....
....
G0 F50.000000 Z6.000000
G0 F150.000000 X11.430000 Y-8.630000
G0 F50.000000 Z6.000000
G81 F25.000000 R1.000000 X11.430000 Y-8.630000 Z-8.000000
G81 F25.000000 R1.000000 X58.570000 Y-8.630000 Z-8.000000
....
for a total of 15 holes  on this work.
Before this test to drill  holes I transformed the G81 like this:
G0Z10
G0 X112.5 Y-15.0
G0Z0.5
G1 Z-7 F25
G0 Z12

in fact with G81 grbl/bcnc it does exactly the same thing (speed for G0 and G1...).
I tested the same thing with a lot of software (like grblpanel, candle panel, universal Gcode it 's not work

since I did near 500 holes  on aluminium (from 2mm to 15mm depth) with not any problems

Does someone have an idea about that ?
I can tell you that for me it's fantastic I save a lot of time

Best

**Comment by swarfer** [comment]
G81 is a canned drill cycle.
The memory in the chip that runs GRBL is too small to do canned cycles internally.
That is why only bCNC willrun the G81, it converts it to  a series of commands tht GRBL does support.
and that is why all the other GUI's will give an error on G81, they don't translate it and GRBL considers it an error.
