### ISSUE TITLE
grbl config

### ISSUE THREAD

**Issue by bwg16** [gnea/grbl#303]
I am very new to cnc so please bear with me. I just got my cnc built and the electronics set up and everything is communicating just fine (at least I think it is).
So I thought I would at first use a pen to draw a picture of a basic shape produced through Inkscape and gcodetools.
Then I had ugs send the gcode to grbl through a cncsheild connected to arduino.
It produced a picture but it was downsized from about 6 x 6 inches to about a half inch square.
I spent the afternoon trying to track down where the problem is but am having no luck. I thought it might have something to do with my firmware settings but I don't know.
Can anyone recognize where I have erred?
Thks
Bruce

**Comment by neilferreri** [comment]
@bwg16 If you jog the machine, does it move the correct distance on each axis?

**Comment by chamnit** [comment]
Grbl's distance units are millimeters. Make sure that you have configured Grbl correctly. Also, check your g-code to see if it sets inches or millimeters mode (G20 / G21) depending on what it was generated for.

**Comment by bwg16** [comment]
At first only x and y moved correctly.  Z was backwards.  I fiddled with $3 and it worked it i set it to $3=4. Then all three moved in the right direction

**Comment by bwg16** [comment]
g20 or g21 seem to have the same results

**Comment by neilferreri** [comment]
Is $13=1?

**Comment by jahnj0584** [comment]
youll want to use this to make your parts on size
https://nathan7.eu/stuff/RepRapCalculator/RepRapCalculator.html#MotorStuffPrecise

**Comment by bwg16** [comment]
No. $13 is 0

**Comment by neilferreri** [comment]
Can you post or share a link to your Gcode?

**Comment by bwg16** [comment]
[spiral_0003.txt](https://github.com/gnea/grbl/files/1448310/spiral_0003.txt)

**Comment by neilferreri** [comment]
Ok, you're gCode's extents are less than 10mm square. The G21 at the start
of your code specifies that all units are millimeters.
That said, if you change that to a G20, preview your code before you send
it. Didn't look like a pen plotter code to me.

**Comment by bwg16** [comment]
Thanks but I need to ask.  Are those gcode extents set by inkscape or gcodetools or ugs.  I don't wnat you to do all the work but if I could just get a start, I'll take it from there.

**Comment by neilferreri** [comment]
That's coming from inkscape/gcodetools. I haven't used gcodetools, but I've
checked it out. I believe there's a scale that shows up on the page when
you run it. Your design might have been too small for you to see the scale.

**Comment by bwg16** [comment]
Thanks to you I have a starting point.  Gcodetools operates kind of crazily (to me, anyway) but I'll go back and work from there.  Thanks again.

**Comment by neilferreri** [comment]
No problem.  If you're just getting started, you might want to look at Easel
<http://easel.inventables.com/>from Inventables.  It is super easy to
generate basic gcode.  Their forums are a great place to get help too.

**Comment by bwg16** [comment]
I looked at that but didnt find a driver for linux

**Comment by neilferreri** [comment]
The driver is only necessary to communicate with the machine.  You can
export the gCode and use whatever sender you want.  I recommend CNCjs as
its UI is the most intuitive..

**Comment by bwg16** [comment]
that makes sense . if i can get it to export gcode i can use ugs to send it to grbl

**Comment by neilferreri** [comment]
Correct

**Comment by bwg16** [comment]
thanks again neil.  you have been a BIG help.

**Comment by biasedlogic** [comment]
I found using either Grbl-plotter or f-engrave (both free software) to get plotter-like g code based on svg picture (f-engrave can also do bitmaps) and Candle to preview it/send to machine to be easiest debugging combo, as each of these programs shows live how big the expected / generated code in real world units will be. 

Gcodetools i found to be very temperamental and it's got it's own scaling settings which are completely independent of inkscape dimension units.
