### ISSUE TITLE
Spindle switch problem

### ISSUE THREAD

**Issue by jm-king** [gnea/grbl#307]
Hello
I come from China.
English is poor
I'm sorry
A switch signal is needed to control the spindle frequency converter

**Comment by biasedlogic** [comment]
If I understand correctly, 'spindle enable'is what you want.
Spindle enable = enable power to spindle
Spindle speed = pwm to control speed

**Comment by jm-king** [comment]
YES

**Comment by biasedlogic** [comment]
Look on the wiki page.
You can set this up in options, if I remember correctly in the config.h file.
You will likely need to flash grbl again to set it up.

**Comment by jm-king** [comment]
Thank you 
I'll try

**Comment by jm-king** [comment]
启用两条代码：
#define INVERT_SPINDLE_ENABLE_PIN
#define USE_SPINDLE_DIR_AS_ENABLE_PIN
M3、M4开主轴D13有正电压，M5关主轴D13无电压。
