### ISSUE TITLE
Spindle speed measurement

### ISSUE THREAD

**Issue by goloplo** [gnea/grbl#308]
Can pin A4 on Arduino be used with an it sensor to count RPM of the spindle?

Thank you.

**Comment by chamnit** [comment]
It sure could, but it won't be on the 328p version of Grbl due to flash, RAM, and even performance constraints. The interrupt has to be serviced every sensor tick and would quickly eat up cycles at high rpms.

**Comment by goloplo** [comment]
Can STM32 handle it? If yes is just using the probe script as reference?

**Comment by graphtjb** [comment]
I agree with the though about spindle speed eating up clock cycles, but frequency divider could slow up the that speed. 
https://www.electronics-tutorials.ws/counter/count_1.html
So the reading would be 2^n. We could account for this 2^n factor in programming. 10 d flip flop circuits could slow up the rpm reading from a encoder about a 1000 times. Make a Mhz signal into a khz signal.
