### ISSUE TITLE
Why limit switch automatic Worked without pressing any limit switch in GRBL?

### ISSUE THREAD

**Issue by lantechbd** [gnea/grbl#316]
Why limit switch automatic Work without pressing any limit switch, Please help me to solve this problem.

**Comment by dungjk** [comment]
You may got noise issue.
1. Keep limit switch cable away noise source (stepper motor wires, fan wire, power wire, laser pwm or other pwm source).
2. Check if limit circuit has noise filter (common PI filter). If not you may build one for each limit switch, it's very simple.
![pi filter](https://user-images.githubusercontent.com/5106786/33708973-8663552e-db6e-11e7-9c82-79e7f26f961b.gif)

**Comment by lantechbd** [comment]
dungjk// Thanks

**Comment by lantechbd** [comment]
TP1 and Detect whats that...
Detect means = Optocupler???

**Comment by chamnit** [comment]
Please read the wiki page on limit switches.

**Comment by lantechbd** [comment]
Ok, Thank you.

**Comment by wlaw** [comment]
Md Kawser Ahmed,

There is soooo much information on this false tripping of the limit
switches.

It usually comes down electrical static noise suppression.

here is a link to start you in the correct direction.

https://github.com/gnea/grbl/issues/96

Kind Regards

**Comment by lantechbd** [comment]
Great! Thanks from my heart for your help.

**Comment by lantechbd** [comment]
![7640a26c-eba7-11e6-9a5a-7d5e521488d8](https://user-images.githubusercontent.com/25710256/33781902-a373be66-dc80-11e7-80bd-36d3ade07f9a.jpg)


is this true circuit...
