### ISSUE TITLE
Woodpecker Board Connecting Z-Axis Touch Probe

### ISSUE THREAD

**Issue by lateefm** [gnea/grbl#321]
Hi, I am new to CNC and GRBL just purchased 3018 engraver which came with Woodpecker 2.8 Board, also purchased Z-axis Touch Probe and was wondering any body can share the instructions to connect this to the Woodpecker Board. I have included the pictures for the board and the z plate.

Thanks!
Lateef

![33813966-11d4ab84-ddf5-11e7-8fbc-3ca0a66807f7](https://user-images.githubusercontent.com/34285786/33839858-57213d12-de61-11e7-9e61-6caa82102c31.JPG)

![33814017-5a2965f0-ddf5-11e7-8cc0-ed82544304eb](https://user-images.githubusercontent.com/34285786/33839874-60da8340-de61-11e7-8447-9b6be123c239.png)

**Comment by chamnit** [comment]
Your answer is [here](https://github.com/gnea/grbl/wiki/Connecting-Grbl) in the wiki. A5.
