### ISSUE TITLE
laser shifts on the x-axis outside the figure

### ISSUE THREAD

**Issue by ha7r3d** [gnea/grbl#324]
Hi. After flashing my Arduino + CNCshield, I have a problem. While burning the image at a random time, the cursor in the program synchronously with the laser shifts on the x-axis outside the figure, and continues to the end. after stopping the program, or the completion of its laser(and the cursor) is returned exactly to 0! I have re-checked everything 10 times, the brain explodes, come to the rescue!
![mxvkofx3e6g](https://user-images.githubusercontent.com/34546765/33999170-cec06c58-e0fa-11e7-8c56-a3a28e6c57b6.jpg)
![robtzvjtygg](https://user-images.githubusercontent.com/34546765/33998974-39aabf24-e0fa-11e7-9f4d-e4caf8a5da7f.jpg)

**Comment by chamnit** [comment]
If the problem is due the cursor, then it’s your laser program. Not Grbl. Grbl just takes gcode and executes it.
