### ISSUE TITLE
What are hard and soft requirements for the pinout?

### ISSUE THREAD

**Issue by oyvindkinsey** [gnea/grbl#325]
I'm building a hybrid CNC/3D Printer using the Arduino Nano with grbl and Teacup as respective firmwares. These have different pinouts, so I'm looking into the possibilities of landing on a common pinout compatible with both firmwares.

grbl has a few requirements defined in cpu_map.h, most notably a few comments such as  

`// NOTE: All direction pins must be on the same port.`

These seem like clear invariants, but there's also a few such as 

`// // NOTE: All limit bit pins must be on the same port, but not on a port with other input pins (CONTROL).`

These are less clear. Does this mean that while the limit switches *must* be on the same port, there's no such requirement across limit and control switches, or does this mean that limits and control *must not* be on the same port?

The arduino supports using the analog ports as digital; what flexibility exists in e.g. moving the limit switches to the analog PORTB in order to free up the digital pins for an extra stepper?

**Comment by chamnit** [comment]
It has to do with the pin change interrupts. They operate per PORT and provides no information on which pin triggered or how. Grbl does not check the pin state within a pin change interrupt, because there is a very small chance it can be misread. For hard limits and user safety, Grbl interprets a pin change as a hard limit event.

**Comment by chamnit** [comment]
Also the direction pins are on the same port because it's easier and faster to setup the IO in the stepper interrupt with one 8-bit variable. If they were on different ports, there would need to be a lot more code to set these various pins in an ISR that is very time sensitive.

**Comment by chamnit** [comment]
I suppose, but it hasn't been a problem given the number of shields available for Grbl these days. The Grbl project was intentionally designed to simple to facilitate the advanced parts of its development, i.e. realtime overrides. It's never been advertised to be a complete solution for everything. Don't worry, it's all part of a grand plan.
