### ISSUE TITLE
When [Connect] is completed, there is an error that red [HOME] and Overrides are missing!

### ISSUE THREAD

**Issue by viewsat** [gnea/grbl#328]
When [Connect] is completed, there is an error that red [HOME] and Overrides are missing, but [HOME] and Overrides appear after pressing Settings- [Get Grbl Settings] or [Disconnect / Connect] several times.

My cnc machine has a home limit switch.

I use the candle and ugsplatform G-Code-Sender to do the test, when [Connect] is completed, [Home] and Overirdes are not wrong.

<1> [HOME] and Overrides are missing
![err](https://user-images.githubusercontent.com/15762267/34098414-3622d470-e417-11e7-84cb-a2d1304886bf.jpg)

<2>[HOME] and Overrides appear after pressing Settings- [Get Grbl Settings] or [Disconnect / Connect] several times.
![ok](https://user-images.githubusercontent.com/15762267/34098422-3d453252-e417-11e7-9795-9e9f9ddf12da.jpg)

**Comment by chamnit** [comment]
@viewsat : This is a GUI issue. Not a Grbl firmware issue. Please post in the appropriate place.

**Comment by viewsat** [comment]
This is a GUI issue,My problems have been solved.
