### ISSUE TITLE
Serial behavior 

### ISSUE THREAD

**Issue by ilie321** [gnea/grbl#329]
Hello i notice that compared to 0.9j if i turn off power and after some time i do power on it not get in consideration the commands from pc only if i send reset command. It is possible to adjust?  Thank you.

**Comment by chamnit** [comment]
No. There has been no changes on how Grbl connects. This is from the Arduino boot loader and your computer.

**Comment by ilie321** [comment]
I used same bootloader for 0.9j and 1.1f and the same software . this is why i suspected something in  grbl because of new real time commands or idk

**Comment by chamnit** [comment]
Grbls comm protocol has changed, as outlined in the wiki. Not the serial handling or how it operates as a whole.  Your GUI may have two different ways of handling each version. This may be what you are seeing as a difference.

**Comment by ilie321** [comment]
Thanks for quick answers i will check.  I use candle. I have used for tests the old one for 0.9 which can't identify 1.1 but it sends the commands .

**Comment by biasedlogic** [comment]
I'm personally on a fence with candle. I love some parts of how it's designed, but it's bug ridden in the serial department. It seems machine dependant, i have a laptop where it just works and i have a PC where candle will skip gcode commands and end up crashing the complete computer down to bsod. Long story short, try another sender

**Comment by ilie321** [comment]
For me it works great except autoleveling

**Comment by biasedlogic** [comment]
Except *"Hello i notice that compared to 0.9j if i turn off power and after some time i do power on it not get in consideration the commands from pc only if i send reset command."* - i mean, do try other sender!

**Comment by ilie321** [comment]
I did with other 2 same result. Same bootloader. On 0.9j i get connected after power off power on in few seconds.  On 1.1 i need to press the reset from software to get connected again.  But is not  big issue i will live with it

**Comment by biasedlogic** [comment]
A long shot: it sounds like the reset circuit of your Arduino might not get reliably reinitialised between power down and power up. To some extent it depends on the configuration (number of active pull ups and active outputs).

**Comment by ilie321** [comment]
On 1.1 it should be the short noise at power up from motors?
