### ISSUE TITLE
Howto setup the working area size?

### ISSUE THREAD

**Issue by srul** [gnea/grbl#333]
hi there, great project thanks for the effort
how can i setup the machine endpoint or engarving limit size?
thanks

**Comment by JBSchueler** [comment]
You have to adjust some settings.

Set [Soft limits, boolean](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#20---soft-limits-boolean) to `1`
Set [X Max travel, mm](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#130-131-132--xyz-max-travel-mm)
Set [Y Max travel, mm](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#130-131-132--xyz-max-travel-mm)
Set [Z Max travel, mm](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#130-131-132--xyz-max-travel-mm)


```
$20=1
$130=350
$131=500
$132=40
```
