### ISSUE TITLE
Trouble with G4 command...... probably

### ISSUE THREAD

**Issue by fxrnando** [gnea/grbl#343]
Long story short: theres a problem big problem on "G4 P..." command

Short story long: Hi, I've downloaded, configured and tested the program on my system and everything went perfect with Gcodes from internet, but when I tried with one of my own (inkscape 0.92 made), results that the system stopped before thrusting the mill for quite a while, and time later continued with the operations.

After checking the programs (bCNC 0.9.11 and inkscape 0.92), everything looked normal, so I compared my gcodes generated and downloded and I found something, the internet G-codes doesn't have "G4 P100" before thrusting the mill.

Now if I understand this command should make the cnc wait for 100 microseconds, so I take my chronometer and opened the console of bCNC and surprise, the cnc was waiting for 100 seconds after each "G4 P100" command (that was sent after thrusting the mill).

Maybe Im missconfiguring or understanding something wrong but, theres any way to correct this issue? (other than eliminating each G4 command?)

Here's an example of my Gcode and in bold where my cnc stays waiting 100 seconds.

G1 Z3.0 S0
G1 F200
G1  X28.5063 Y-27.2591
G4 P0 
G1 Z-0.3 S256
**G4 P100**
G1 F10.000000
G3 X28.6779 Y-27.6124 I1.7881 J0.6502

Thanks for your time.

**Comment by chamnit** [comment]
Grbl follows the LinuxCNC g-code standard. See the description of [G4](http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g4). Note P is in seconds. Not micro or milli seconds like some other firmwares incorrectly do.
