### ISSUE TITLE
REPORT_ECHO_LINE_RECEIVED as a $ setting rather than compile-time option?

### ISSUE THREAD

**Issue by andrewismoody** [gnea/grbl#345]
Would it be possible to make REPORT_ECHO_LINE_RECEIVED a configurable $ setting rather than a compile-time option?  It would make switching back and forth between troubleshooting and production runs much simpler (without having to re-flash the Arduino between).

**Comment by chamnit** [comment]
Nope. No flash space or memory left for general release. Future ARM version will allow it to be configured at a console.

**Comment by andrewismoody** [comment]
Awww.  Thanks for the consideration, anyway.
