### ISSUE TITLE
Question about planner

### ISSUE THREAD

**Issue by rsc9421** [gnea/grbl#346]
Hi, I think only you can help me
how the planner's work? I readed planner.c but not full understand how it works, my question is about coordinated movement
suppose that motor X moves 10 steps and motor Y moves 5 steps, and the maximum velocity is v_max(if v_max is higher velocity is slow, if v_max is less  velocity is high), then motor X moves with v_max and motor Y moves at minor velocity, I calculate it as k= v_max*(motorX/motorY)=v_max*10/5 = v_max*2 then motor Y moves more slow than motor X
and it moves at coordinated movement because motorX/motorY = 10/5 is a natural number, but if motorX/motorY is a rational number(for ex. 1/3) then a phase shift occurs (one of the motor will end before the other) and it's not coordinated movement and it traduce as inertia problem, how can I fix it? I tryed to modify v_max in such way that k= v_max*(motorX/motorY) be a natural number (doing v_max a minimum common multiple of motor X and motor Y ) but, it change the v_max constantly and I be unable to set velocity at desired value, such as 10mm/s as grbl 
best regards

**Comment by chamnit** [comment]
Everything is explained in the comments inside the source code.
