### ISSUE TITLE
errors during loading

### ISSUE THREAD

**Issue by mlo300** [gnea/grbl#349]
when i loading grbl arduino the monitor displays  this: and complete loading but don't work $
In file included from C:\Users\Admin\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\Admin\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\Admin\Documents\Arduino\libraries\grbl/nuts_bolts.h:25:0: warning: "false" redefined

 #define false 0

 ^

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:24:0,

                 from sketch\grblUpload.ino.cpp:1:

c:\program files (x86)\arduino\hardware\tools\avr\lib\gcc\avr\4.9.2\include\stdbool.h:42:0: note: this is the location of the previous definition

 #define false false

 ^

In file included from C:\Users\Admin\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\Admin\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\Admin\Documents\Arduino\libraries\grbl/nuts_bolts.h:26:0: warning: "true" redefined

 #define true 1

 ^

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:24:0,

                 from sketch\grblUpload.ino.cpp:1:

c:\program files (x86)\arduino\hardware\tools\avr\lib\gcc\avr\4.9.2\include\stdbool.h:43:0: note: this is the location of the previous definition

 #define true true

 ^

In file included from C:\Users\Admin\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\Admin\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\Admin\Documents\Arduino\libraries\grbl/nuts_bolts.h:51:0: warning: "max" redefined

 #define max(a,b) (((a) > (b)) ? (a) : (b))

 ^

In file included from sketch\grblUpload.ino.cpp:1:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:93:0: note: this is the location of the previous definition

 #define max(a,b) ((a)>(b)?(a):(b))

 ^

In file included from C:\Users\Admin\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\Admin\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\Admin\Documents\Arduino\libraries\grbl/nuts_bolts.h:52:0: warning: "min" redefined

 #define min(a,b) (((a) < (b)) ? (a) : (b))

 ^

In file included from sketch\grblUpload.ino.cpp:1:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:92:0: note: this is the location of the previous definition

 #define min(a,b) ((a)<(b)?(a):(b))

 ^

In file included from C:\Users\Admin\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\Admin\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\Admin\Documents\Arduino\libraries\grbl/nuts_bolts.h:55:0: warning: "bit" redefined

 #define bit(n) (1 << n) 

 ^

In file included from sketch\grblUpload.ino.cpp:1:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:123:0: note: this is the location of the previous definition

 #define bit(b) (1UL << (b))

 ^

**Comment by chamnit** [comment]
Please follow the wiki directions and GrblUpload comments exactly. If you don’t, you’ll have compile issues.
