### ISSUE TITLE
Timer1 prescaler

### ISSUE THREAD

**Issue by Strooom** [gnea/grbl#35]
@chamnit Sonny, could you briefly explain where the Timer1 is being started in stepper.c in (default) case of using AMASS ?

I can only see  `TCCR1B = (TCCR1B & ~((1<<CS12) | (1<<CS11))) | (1<<CS10); // Reset clock to no prescaling.` but according to the ATmega datasheet (pg 173) this STOPS the Timer1

I can also see `TCCR1B = (TCCR1B & ~(0x07<<CS10)) | (st.exec_segment->prescaler<<CS10);` but that is only for the case with no AMASS...

Thanks!

**Comment by jeffmd** [comment]
Look closer at the parentheses.  CS12 and CS11 are cleared but CS10 is being set.

**Comment by Strooom** [comment]
ok, now I understand. Thanks for helping me out!
