### ISSUE TITLE
Overrides Panel does not always display

### ISSUE THREAD

**Issue by dre3rd** [gnea/grbl#351]
Is there some reason for the overrides panel (lower right corner) not to display everytime the program is being used.  Sometimes it's there and sometimes not.  It is handy for use with my laser and I have used it in the past. Running latest version from 11-13-2017 on a Win7 Pro Dell Laptop. Will experiment with my Linux unit and see if it does the same.  Haven't used it enough to know one way or the other.

**Comment by chamnit** [comment]
Grbl is not a GUI. It’s only firmware. Please post your issue on the GUI site.

**Comment by dre3rd** [comment]
Thank you.
