### ISSUE TITLE
checksum algorithm returns boolean instead of byte

### ISSUE THREAD

**Issue by ChristianRinn** [gnea/grbl#355]
Typical use of a boolean operator ('||') where the bitwise operator was meant ('|'). Fortunately there are compiler warnings.
```
grbl/eeprom.c:133:26: warning: '<<' in boolean context, did you mean '<' ? [-Wint-in-bool-context]
     checksum = (checksum << 1) || (checksum >> 7);
                ~~~~~~~~~~^~~~~
grbl/eeprom.c: In function 'memcpy_from_eeprom_with_checksum':
grbl/eeprom.c:144:26: warning: '<<' in boolean context, did you mean '<' ? [-Wint-in-bool-context]
     checksum = (checksum << 1) || (checksum >> 7);
                ~~~~~~~~~~^~~~~
```
Affected are the functions memcpy_to_eeprom_with_checksum() and memcpy_from_eeprom_with_checksum() here:  https://github.com/gnea/grbl/blob/master/grbl/eeprom.c#L130

PS:
To fix this bug we would have to wipe every EEPROM again because otherwise the checksum would be "wrong".

**Comment by chamnit** [comment]
Yep. I found this a couple years ago and came to the same conclusion that it would wipe every EEPROM since the checksum would be wrong. Decided to leave it alone until the next major version.

**Comment by micromouseonline** [comment]
Perhaps a comment in the source code pointing to this issue would help others (like me) from 're-discovering' this error periodically?
