### ISSUE TITLE
Cnc V3? shield for very noobs

### ISSUE THREAD

**Issue by sp2567** [gnea/grbl#361]
Hi guys, I bought a cnc v3? (I dont know exactly) from there:
https://sienci.com/product/cnc-v3-0-shield/
The shield is  compatible with GRBL 1.1f (it's tested and works)
The question is: I can use ttl/pwm laser or only a ttl?

Also I have order a very cheap ttl laser just for test.
https://www.ebay.com/itm/Focusable-500mw-808nm-Infrared-IR-Laser-Diode-Dot-Module-12V-TTL-Fan-Cooling/332508405593?hash=item4d6b0b9f59:g:3iEAAOSwicpaaZVv
Where to connect it? In SprEn pins I thing? 
Last one: Until it comes, I can test the output to see how it works by connecting sth else or a polymeter?

Thank you

**Comment by chamnit** [comment]
There are wiki pages for Grbl that will tell you what you need to know. Otherwise, you'll need to contact your CNC manufacturer for help.
