### ISSUE TITLE
Compiling done wrong?

### ISSUE THREAD

**Issue by freerpg1** [gnea/grbl#363]
so I followed the guide to install the library by going to add zip/ library all the stuff stated. when compiling I get heap of issues
`
In file included from C:\Users\freer\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\freer\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\freer\Documents\Arduino\libraries\grbl/nuts_bolts.h:25:0: warning: "false" redefined

 #define false 0

 ^

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:24:0,

                 from sketch\grblUpload.ino.cpp:1:

c:\program files (x86)\arduino\hardware\tools\avr\lib\gcc\avr\4.9.2\include\stdbool.h:42:0: note: this is the location of the previous definition

 #define false false

 ^

In file included from C:\Users\freer\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\freer\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\freer\Documents\Arduino\libraries\grbl/nuts_bolts.h:26:0: warning: "true" redefined

 #define true 1

 ^

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:24:0,

                 from sketch\grblUpload.ino.cpp:1:

c:\program files (x86)\arduino\hardware\tools\avr\lib\gcc\avr\4.9.2\include\stdbool.h:43:0: note: this is the location of the previous definition

 #define true true

 ^

In file included from C:\Users\freer\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\freer\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\freer\Documents\Arduino\libraries\grbl/nuts_bolts.h:56:0: warning: "max" redefined

 #define max(a,b) (((a) > (b)) ? (a) : (b))

 ^

In file included from sketch\grblUpload.ino.cpp:1:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:93:0: note: this is the location of the previous definition

 #define max(a,b) ((a)>(b)?(a):(b))

 ^

In file included from C:\Users\freer\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\freer\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\freer\Documents\Arduino\libraries\grbl/nuts_bolts.h:57:0: warning: "min" redefined

 #define min(a,b) (((a) < (b)) ? (a) : (b))

 ^

In file included from sketch\grblUpload.ino.cpp:1:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:92:0: note: this is the location of the previous definition

 #define min(a,b) ((a)<(b)?(a):(b))

 ^

In file included from C:\Users\freer\Documents\Arduino\libraries\grbl/grbl.h:43:0,

                 from C:\Users\freer\Documents\Arduino\libraries\grbl\examples\grblUpload\grblUpload.ino:27:

C:\Users\freer\Documents\Arduino\libraries\grbl/nuts_bolts.h:61:0: warning: "bit" redefined

 #define bit(n) (1 << n)

 ^

In file included from sketch\grblUpload.ino.cpp:1:0:

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:123:0: note: this is the location of the previous definition

 #define bit(b) (1UL << (b))

 ^

Sketch uses 30562 bytes (94%) of program storage space. Maximum is 32256 bytes.
Global variables use 1633 bytes (79%) of dynamic memory, leaving 415 bytes for local variables. Maximum is 2048 bytes.
Low memory available, stability problems may occur.
`
I have uninstalled arduino, the library everything and still not working. Arduino version is 1.8.5. downloaded hex was grbl-1.1f.20170801

**Comment by chamnit** [comment]
You have to follow instructions exactly. Common issues are other Grbl libraries in the Arduino path and not using/altering the GrblUpload example file.
