### ISSUE TITLE
Trinamic TMC2130 Stepper Driver support

### ISSUE THREAD

**Issue by Blaisun** [gnea/grbl#365]
Has there been any discussion on support for the TMC2130s? 

 In my brief research, they seem to have a number of benefits over the 4988 and 8825 drivers. The ones i am most interested in are dynamic current control and stall detection.  i am not sure how well the "virtualized endstops" will function in a CNC application but they seem to work well for homing in a 3D Printing application.

The biggest downside i can see for use in grbl is the pin shortage on the Uno. Would it be feasible to implement on the mega branch?

This is more of a question of feasibility directly related to grbl as it currently seems the project doesnt support anything other than Step/Dir for driver control....

**Comment by lslewis901** [comment]
Here is a link where a guy used another Nano to integrate the features with the TMC2130 drivers:

https://youtu.be/ZzO9skEYqwY
Wiring and code page: https://reps.cc/?p=5

**Comment by chamnit** [comment]
Support may show up on the Mega branch at some point, but it's not a priority right now.

**Comment by Schildkroet** [comment]
watterott offers some replacement modules for A4988 etc. with TMC chips.
https://github.com/watterott/SilentStepStick

**Comment by Blaisun** [comment]
@chamnit  ok thanks. i was just wondering if the requirement to talk to the chips via SPI would mess with the way grbl currently works....

**Comment by Rotzbua** [comment]
The TMC2130 supports 3 modes how the chip can be run.
One mode is the "standalone mode" which can be configured via pins and require no SPI. In standalone mode the TMC2130 can replace a A4988 without any software modification.

Result:
It is possible to use 2 features of the TMC2130 with this library: stealthChop and spreadCycle. Basically this are the features of the TMC2100 because we do not use the SPI.

**Comment by dudman** [comment]
Sorry for the late reply, been searching everywere else. 

So the 3rd feature of TMC2130 SPI is not implemented in Grbl ? Is there any plan to support this ?
