### ISSUE TITLE
homing does not work

### ISSUE THREAD

**Issue by cecconilorenzo** [gnea/grbl#372]
Hi, I'm trying to put the limit switches for homing but nothing works.
the problem is not the wiring but the software, I have enabled $ 22 = 1 and when I send the command $ H the motors x y are blocked.
I do not have a Z axis because it's a laser cnc, is this a problem?

**Comment by chamnit** [comment]
@cecconilorenzo : Yes. Grbl is setup of 3-axis. Not 2-axis. If you did a search for this, you would have found lots of issues threads detailing how you would alter Grbl to home for 2-axes. In short, you need to edit your Grbl config.h in the Arduino library. There are instruction in there.

**Comment by cecconilorenzo** [comment]
OK thank you very much

**Comment by montakhab** [comment]
HI. I began to UGS  platform  v2 nightly setup wizard but in home settings when i press the homing button
occurs error. Whats the problem?
![error](https://user-images.githubusercontent.com/53232033/61736949-6efba600-ad9c-11e9-9a27-30a5a8a332d7.PNG)
