### ISSUE TITLE
Edit config.h -- Compile/Generate hex on Atmel328p grbl 1.1f

### ISSUE THREAD

**Issue by FirewAB** [gnea/grbl#382]
Dear all,

I was trying Homing for 2 axes only. X-Axis and Y-Axis.

I edited config.h in grbl 1.1f as recommended in it. Commented out Z-Axis homing 
// #define HOMING_CYCLE_0 (1<<Z_AXIS)
and set  #define HOMING_CYCLE_1 ((1<<X_AXIS)|(1<<Y_AXIS)) to
#define HOMING_CYCLE_0 ((1<<X_AXIS)|(1<<Y_AXIS))
I have yet to do other settings like; Homing direction, max travel etc.

But I decided to check the outcome of the above change first. I have followed the compiling guide and I am presented with the following errors. 

1. Required HOMING_CYCLE_0 not defined.
2. WCO refresh must be greater than one.
3. Override refresh must be greater than zero.

I have included the grbl folder in Arduino library (Only containing the example and source codes).

My objective is to be able to edit config.h and other necessary files and, compile and generate hex file to flush it on to Atmel328p.

Has anyone been successful compiling generating .hex file after editing files like config.h please?

**Comment by chamnit** [comment]
In short, you are editing the config.h file correctly, but have to follow the compiling instructions exactly. The Grbl compiling instructions state to check to make sure any previous installations of Grbl have been removed from the Arduino library paths. Also, make sure to add the correct folder and edit the correct config.h file. The instructions explain which is which. If you are still confused, there are a bazzilion closed issues threads just like yours that you can search and read.
