### ISSUE TITLE
How to save machine coordinates after power off

### ISSUE THREAD

**Issue by houguang** [gnea/grbl#387]
I am in the carving of a large pattern of power outages, call back after the knife can not be guaranteed with the last pair of knife exactly the same location, resulting in obvious dislocation at the interface. How to save power when mechanical coordinates and engraving line number, then it may be perfect The solution to this problem. How to achieve?

**Comment by chamnit** [comment]
Yes. It’s called work coordinate systems. You need homing enabled to reference a fixed position. See LinuxCNC docs for how they work.
