### ISSUE TITLE
homing and limit switch issue

### ISSUE THREAD

**Issue by Scatman96** [gnea/grbl#391]
Hi,
iam new to cnc and grbl. i bought a chinese cnc2417 with laseraxe-controller on amazon.
First i wired my Limit switches/endstops in NC (2 on Y, 2 on X, 1 on Z). Then setup the homing settings etc.

My problem is that iam getting this ERROR after homing and start a file/job:
[CTRL+X] < ALARM:2
Grbl 1.1e ['$' for help]
[MSG:'$H'|'$X' to unlock]
S9600 < error:9

**This is the position after homing**
![whatsapp image 2018-03-04 at 13 48 50](https://user-images.githubusercontent.com/25407989/36945960-c5cd9946-1fb5-11e8-942f-4836eccd715f.jpeg)

**Here is my homing and start routine in pictures**
# [https://imgur.com/a/ftyj5](url)

**My Settings:**
### $$ < $0=10
$1=25
$2=0
$3=6
$4=0
$5=1
$6=0
$10=3
$11=0.010
$12=0.002
$13=0
$20=1
$21=0
$22=1
$23=1
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=1000
$31=0
$32=0
$100=400.000
$101=400.000
$102=400.000
$110=1500.000
$111=1500.000
$112=1500.000
$120=10.000
$121=10.000
$122=10.000
$130=235.000
$131=145.000
$132=60.000
ok

Thank you in advance for your help :)

**Comment by chamnit** [comment]
The wiki explains what the error and alarm code are. Alarm 2 is when you exceed machine travel. This is due to you enabling soft limits and the program moving beyond machine space. You need to learn about work coordinate systems and how to set your work origin.
