### ISSUE TITLE
grbl pendant 1mm/min

### ISSUE THREAD

**Issue by electric1236** [gnea/grbl#392]
so i used to use grbl 0.9 and ugs newest version with their pendant web server when i upgraded to grbl 1.1 the pendant still worked but it had a feed rate of 1 mm/minute which makes it pretty much useless, can find any setting to change it.

thank you for the help

**Comment by electric1236** [comment]
*(grammer fix, sorry)
so I used to use grbl 0.9 and ugs (2.0) with their pendant web server when I upgraded to grbl 1.1 the pendant still worked but it had a feed rate of 1 mm/minute which makes it pretty much useless, can't find any setting to change it.

**Comment by petmakris** [comment]
This isn't relative to GRBL, 

The Pendant sends

`$J=G91X-10F1`

so the feedrate is defined by UGS (pendant plugin).
