### ISSUE TITLE
Spindle Speed Questions

### ISSUE THREAD

**Issue by adigitaldj1** [gnea/grbl#393]
I can't seem to get my spindle Speed to go anymore than 1000rpm. I have changed it in the firmware settings through UGS Platform and saved it. Changed my Gcode to S3000 and still didn't change. What am I doing wrong or need to do?

**Comment by adigitaldj1** [comment]
It also has the laser option on the board if that makes any difference.

**Comment by 109JB** [comment]
The spindle is just a DC motor, so it would need some kind of controller if RPM is to be adjustable.  It could be the Woodpecker board has this, but I am not familiar with that board so cannot say.  I have read some posts about it and it seems that many problems relate to the pin changes from Grbl 0.8 to 0.9.

**Comment by chamnit** [comment]
What are your Grbl $$ settings? We need to verify that they were set correctly.

**Comment by adigitaldj1** [comment]
I have set my spindle max speed from 1000 to 7000 and minimum still at 0.

**Comment by chamnit** [comment]
Please show the print out of your Grbl $$ settings.

**Comment by adigitaldj1** [comment]
I can do that tonight after work. Can I post a screen shot on here? I tried but didn't see where to attach a file. I can post settings and a pic of the controller board.

**Comment by chamnit** [comment]
Drag and drop, like it says in the bottom of the window where you type a response. 

I also did a quick search for Woodpecker schematics (which are quickly becoming the bane of my existence). It does look like its just an on off relay. If you can try testing the voltage at your spindle power port to verify this.

**Comment by adigitaldj1** [comment]
Here s my firmware settings. Voltgae on the motor is 23.6volts

Grbl 1.1f ['$' for help]
[HLP:$$ $# $G $I $N $x=val $Nx=line $J=line $SLP $C $X $H ~ ! ? ctrl-x]
ok
ok
$0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=1
$20=0
$21=0
$22=0
$23=0
$24=100.000
$25=500.000
$26=250
$27=1.000
$30=7000
$31=1000
$32=0
$100=800.000
$101=800.000
$102=880.000
$110=500.000
$111=500.000
$112=500.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000
ok
ok

Thanks,
Kevin

**Comment by chamnit** [comment]
There is nothing wrong with your settings. Grbl will setup the D11 pin to 0v when off, 0.02V at 1000 rpm minimum, and 5V at 7000 rpm max. Outside of that, this seems to be a problem of your cheap CNC controller board being not as capable than what you think it is. A woodpecker looks to just have an on-off relay.

**Comment by biasedlogic** [comment]
First, post a picture of your present board. There are a few Woodpecker boards out there, so picture is best. You can use a service like imgur.com to upload a picture if you can't attach it to your post.
While there are issues with the woodpecker boards, most I have heard of are due to there being many various boards by the same name out there, and not really quality issues as such. So mostly just docs not matching the board.
If the board has a relay to control your motor, you will need some sort of pwm controller to control your motor. The only cheap boards I know of, that are grbl compatible and have a dc power stage integrated, are the woodpecker boards with irf540n power MOSFET on them...

**Comment by biasedlogic** [comment]
... So if you go for a different board you will likely need a pwm controller anyway.

**Comment by adigitaldj1** [comment]
Here is the pic of the control board

![cnc control board](https://user-images.githubusercontent.com/31939308/37225284-1ed98472-23a4-11e8-84dc-f1d889fd6ba7.JPG)

**Comment by biasedlogic** [comment]
There are good news and bad news.
Bad news is, this board can't provide pwm control to a 24V motor.
Good news is you can grab the pwm signal for an external pwm unit off the middle pin of the selection jumper laser/cnc (remove the jumper for that). Take ground from any ground pin on the top right connector.
This board also has a pwm power stage for the laser output, but it is wired for 12V. It may be possible to use that output for the motor directly, but you'd have to figure out that part of board schematic as it might need adding some protective circuitry
