### ISSUE TITLE
GRBL mistreats cancelled jobs

### ISSUE THREAD

**Issue by jahnj0584** [gnea/grbl#397]
Look at how the Z axis behaves if you cancel a job. It happens EVERY time. Wilder says its not a UGS issue. 

https://www.youtube.com/watch?v=WpiIB9ml-og

**Comment by chamnit** [comment]
It’s not clear what you are referring to as a problem. You seem to probe, play with overrides, then cancel the job. I see the z value change but don’t see what happens to the machine. It doesn’t sound like anything happens.

**Comment by jahnj0584** [comment]
Cancelling a job after running a probe cycle causes the probed axis'
current location to change. G53 remains the same if memory serves correct.
The over rides where to just show that it was moving beforehand anyways.

**Comment by chamnit** [comment]
So after a probe cycle? The dynamic tool length offset was likely appropriately cleared.

**Comment by jahnj0584** [comment]
Why would the offset be changed when a job is cancelled but remain when the
job is sent to completion?

**Comment by chamnit** [comment]
It depends on what UGS does when the job is cancelled. If it automatically soft resets Grbl, it’ll clear all temporary offsets. 

As you said G53 or machine coordinates are fine, only the work position shifts. This means something in the work offsets is altered. Again likely the tool length offset. Grbl doesn’t do anything to that offset unless there is a reset. If you print the $# parameters and $g gcode state before and after, you can see if anything changed.

**Comment by biasedlogic** [comment]
> Why would the offset be changed when a job is cancelled but remain when the job is sent to completion?

@Chamnit told you why does that happen, as in 'what leads to the effect', as to the reason: reset is a state that has no known duration, grbl can't know why it was in reset, how long and what happened there. Note, that homing is assumed lost too.

**Comment by jahnj0584** [comment]
If I use a G10 P0 L20 Z14.91 instead of G92 Z14.92 it should work and stay after a reset, right? Its the same as hitting the reset Z zero button.

**Comment by chamnit** [comment]
G10 saves to eeprom so yes. G92 is defined as temporary in the gcode standard. So it resets with a reset.

**Comment by jahnj0584** [comment]
Great. I'll just so that then. Why do people suggest G92 then?
