### ISSUE TITLE
problem with classic mode

### ISSUE THREAD

**Issue by quangvi** [gnea/grbl#40]
Dear @chamnit in file report.c line 298 : 

printPgmString(PSTR(" (homing dir invert mask\r\n$24=")); 

bug fix add " ) " :

printPgmString(PSTR(" (homing dir invert mask)\r\n$24=")); 

it's had problem to setting in Grbl 3.6.1 control
and in file defaults.h line 50 : can change if use classic mode in Grbl 3.6.1 control
#ifdef USE_CLASSIC_GRBL_INTERFACE
  #define DEFAULT_STATUS_REPORT_MASK ((BITFLAG_RT_STATUS_MACHINE_POSITION)|          (BITFLAG_RT_STATUS_WORK_POSITION))//
#else
 #define DEFAULT_STATUS_REPORT_MASK 1 // MPos enabled
#endif
 in file setting.h warning in 3 function:

// Returns the step pin mask according to Grbl's internal axis numbering
uint8_t get_step_pin_mask(uint8_t i);

// Returns the direction pin mask according to Grbl's internal axis numbering
uint8_t get_direction_pin_mask(uint8_t i);

// Returns the limit pin mask according to Grbl's internal axis numbering
uint8_t get_limit_pin_mask(uint8_t i);

--> To do bug fix:

// Returns the step pin mask according to Grbl's internal axis numbering
uint8_t get_step_pin_mask(uint8_t axis_idx);

// Returns the direction pin mask according to Grbl's internal axis numbering
uint8_t get_direction_pin_mask(uint8_t axis_idx);

// Returns the limit pin mask according to Grbl's internal axis numbering
uint8_t get_limit_pin_mask(uint8_t axis_idx);

**Comment by chamnit** [comment]
@quangvi : Thanks, but I'm removing CLASSIC GUI mode with the master release.
