### ISSUE TITLE
[GRBL v1.1] FAQ Typo/Wrong description of function for config.h 

### ISSUE THREAD

**Issue by TilTisback** [gnea/grbl#400]
Hello,
after updating to the new GRBL, i found out that in the the old HOMING_FORCE_ORIGIN from config.h was changed to HOMING_FORCE_SET_ORIGIN.
The FAQ however still has HOMING_FORCE_ORIGIN in it.
This took me quite some time to figure out. So to spare other people the hassle this should be changed or get an addition like (grbl v1.1 --> HOMING_FORCE_SET_ORIGIN)

Thank you.

**Comment by chamnit** [comment]
@TilTisback : Thanks. FAQ is updated.
