### ISSUE TITLE
4th axis slave axis 

### ISSUE THREAD

**Issue by manisaranbala** [gnea/grbl#403]
i need x axis mirror a or u axis  but  separate home switch  it is possible ? pl help

**Comment by chamnit** [comment]
No, unless you modify the source code to do what you want.

**Comment by manisaranbala** [comment]
my machine dual  axis x axis left side, a axis right side  so i need linear axis

**Comment by lalo-uy** [comment]
If both axis move the same will home at the same time.
you can put 2 home switches in paralle or serie .


2018-03-23 13:19 GMT-03:00 manisaranbala <notifications@github.com>:
