### ISSUE TITLE
G92 / G10 L20 P0 in UGS

### ISSUE THREAD

**Issue by trbLeeciN** [gnea/grbl#405]
Hi there,
I am trying to compensate backlash by editing gcode file. I want to know whether G92 or G10 command work while sending gcode file by UGS.
To sum up, I get backlash by G01 command and I want to make my recent pos. to prev. pos. by G92 or G10, I tried too much, but couldn't find the problem.
Also to make things easier are there any commands which moves motors without changing position.

**Comment by langwadt** [comment]
you can't move the motors with out changing the position but you can change the position without moving the motors
