### ISSUE TITLE
homing documentation unclear

### ISSUE THREAD

**Issue by J-Dunn** [gnea/grbl#408]
https://github.com/gnea/grbl/wiki/Set-up-the-Homing-Cycle

> Homing direction
> 
> The homing directions are controlled by setting $23.
> 
>     Default setting ($23=0), the home location is the top right of your work area, with the spindle all the way up.
>     $23=1 Top left home location.
>     $23=2 Bottom of your work area to be the home location.
>     $23=4 Spindle down home location.
> 

This does not seem to be a clear, unambiguous statement of how this works.  ( how do we get bottom right ? ) 

I'm guessing this is bit encoded LSB encodes 1:left  0:right
bit 1 encodes top / bottom, though  "top" on a horizontal axis is probably not the best word. Top and bottom would make more sense used for Z. 

 $23=4 : presumably this gives top , right, spindle down , so the text does not fully state what this value represents. What is given is 4 examples of the 8 possible states , from which we are supposed to guess the real functionality.   A programmer would probably recognise how this is implemented but this may be unclear or confusing to a non-programmer user. 

It should be fully explicit for any example values given and the underlying bit coded nature should be clearly documented.

**Comment by chamnit** [comment]
No need. I’m fleshing out a configuration file for the next version. There is plenty of flash to do this verbosely.
