### ISSUE TITLE
Disable pull off after homing sequence

### ISSUE THREAD

**Issue by jeroenvdbergh** [gnea/grbl#412]
Hi,

I know it is possible to set the pull off distance after hitting a limit switch using $27.

I was wondering if it is possible to disable this feature in total. So when the limit switch is hit, it just stops and stays there.

Thanks in advance.

**Comment by chamnit** [comment]
@jeroenvdbergh : Not sure why you would want that. A switch is usually in an indeterminate state when it triggers, constantly flipping, because its right at the edge of it switching. You can either set the pull-off to a very small value like 0.0001 or modify the source code.
