### ISSUE TITLE
Emergency stop

### ISSUE THREAD

**Issue by Jibeji** [gnea/grbl#424]
Hello,
I have wired an emergency stop button, which sets Reset pin to ground.
When the button is pressed, the GRBL resets, but reboots and starts again.
If gcode is still sent, the router continues to proceed whatever the Reset state..

**Comment by 109JB** [comment]
A proper E-stop switch should cut power to all motors and motor drivers. A switch wired to the reset pin is not an emergency stop. Also, an emergency stop switch should be a latching switch that stays in the de-activate position once released. Most need to have the mushroom head of the switch rotated to unlatch it.
