### ISSUE TITLE
Changing the coordinate system on a laser machine

### ISSUE THREAD

**Issue by iceblu3710** [gnea/grbl#425]
I have a K40 style laser with its default home & origin set at TopLeft. This is convenient because it's easy to load materials and the cutting strength is best in that corner due to alignment issues.

Nearly all software, however, uses the standard cartesian reference frame (0,0) being BottomLeft. This results in my parts being cut mirrored in the x-axis. Moreover if its something like card stock I also need to mirror the stock on the y-axis so the x-mirroring ends up on the correct side of the paper.

This is very confusing to keep track of. How can I configure grbl to have a BL origin but a TL home without only soft limits?

**Comment by chamnit** [comment]
@iceblu3710 : If your parts are mirrored, then your axes directions are misconfigured. It must follow the right hand rule. 

In reality, the location of the machine origin is arbitrary. You can set your work coordinate system easily to be in the bottom left hand corner with a G10 command.

If that is not satisfactory, you can set your machine origin to the bottom left. You need to have homing switches there and enable the define called HOMING_FORCE_ORIGIN (or something like close to that).
