### ISSUE TITLE
Enable I2C for a Spindle control

### ISSUE THREAD

**Issue by SailWithChips** [gnea/grbl#429]
I think it was issued in old GRBL (0.9) but not "solved" at all. I would like to control the rpm of the spindle via i2c DAC since the frequency inverter is sensitive to the PWM frecuency (working with atmega328p) and the setpoint for the rpm's are not so stable. It could be really nice to have the chance to output via i2c the rpm setpoint.

**Comment by Harvie** [comment]
Just add low-pass RC filter to your PWM to filter it?

**Comment by chamnit** [comment]
Adding i2c spindle control was not “solved” because it was never on the development path. This is certainly an idea to add eventuallly but there are plenty of other things that are much higher priority.

**Comment by SailWithChips** [comment]
@Harvie already have a low pass filter but is still not a fixed signal, and as you know it is not as fast as an i2c would be since a low pass filter put a delay into acceleration to setpoint rpm’s.

@chamnit, thanks to answer anyway, hope to have this feature in the future... i can imagine there are some features with higher priority.

**Comment by Harvie** [comment]
why would you need to change spindle speed so rapidly? i think the inertia of spindle is limiting factor anyway...
