### ISSUE TITLE
Slow jog speed

### ISSUE THREAD

**Issue by grbd** [gnea/grbl#435]
Hi,
I'm currently using grbl 1.1f, with what should be the correct version of chillipepr
http://chilipeppr.com/jpadie

But I'm noticing slow speeds while jogging

This command seems to use a very slow feedrate even though F200 has been specified
```
$J=G91G21Y-10.000F200
```

This command I think moves at the correct speed, but isn't jogging mode
```
G91G21Y-10.000F200
```

**Comment by chamnit** [comment]
Given the lack of response, I assume this issue is resolved. Closing.
