### ISSUE TITLE
CNC 2417 arduino Nano

### ISSUE THREAD

**Issue by idorual** [gnea/grbl#439]
Hello! I downloaded grbl-master v1.1 and I read the instructions that says to modify parameters in 3 files (1- config.h, 2- cpu_map.h, 3-defaults.h). all this to adapt it to the input output of the CNC board. I edit as ask, the upload in the Nano is going very well. The program works well, it reviews the messages of the steps that it accomplishes. But the CNC does nothing, there is nothing that moves.
When I ask the program about the parameters, it lists the parameters but not the same ones I wrote before the upload.

I sought the cause without finding it.
If you could help me solve the problem I would like a lot.

**Comment by chamnit** [comment]
Measure the output pins on the Arduino without it connected. With the step pulses, you'll either need an oscilloscope or increase the step pulse time enough to detect the mean voltage with a voltmeter. If that works, then it's something with your electrical connections.
