### ISSUE TITLE
Hardware variable overrides

### ISSUE THREAD

**Issue by niki77** [gnea/grbl#44]
Hi dear,

it's difficult to implement the ability to control the overrides value by a result of an analog input? (ex. withe a potentiometer connected to an analog input can change the spindle speed or feed override in real time)
Thanks in advance.

**Comment by chamnit** [comment]
@niki77 : Yes, it would be difficult to convert an analog input to control overrides. It's not designed to be controlled in this way, but rather through a set of '--', '-', '100%','+', and '++' buttons. I understand it's not optimal, but it's a result of lack of flash space to implement anything more complicated.
