### ISSUE TITLE
REQ_MM_INCREMENT_SCALAR setting?

### ISSUE THREAD

**Issue by PuddingPengChen** [gnea/grbl#447]
Hi,
 I am using the grbl in a STM32 board. 
 when I want change some maroc such as : REQ_MM_INCREMENT_SCALAR and DT_SEGMENT, I can not really unstand what it mean. Hope someone can help me, thank you~

**Comment by chamnit** [comment]
Don’t mess with these if you don’t understand what they do. They are involved with the step generation algorithm.

**Comment by PuddingPengChen** [comment]
OK, I'll try to understand it. Thany you for your reply .
