### ISSUE TITLE
Control ZYX via Keyboard and LCD

### ISSUE THREAD

**Issue by Chip1972** [gnea/grbl#450]
Hi. I manage to add a LCD and Keyboard in GRBL 0.9. I want to control the XYZ coordinates and display, but need help to find the variables to manipulate. I need to finish the project to try to add in GRBL 1.1. Thanks

**Comment by chamnit** [comment]
There is a lot less available flash and memory space in Grbl v1.1 due to the addition of realtime overrides. I doubt you'll be able to get it to fit.
