### ISSUE TITLE
Burning engine of cnc 2447 under grbl v1.1 and on CPU_MAP_ATMEGA328P does not work

### ISSUE THREAD

**Issue by idorual** [gnea/grbl#453]
Hello
Excuse the translator.
i have a cnc 2447 chinese with a arduino Nano she had the grbl v0.9 to intaller.
I want to update it with v1.1f, VERSION_BUILD "20170801".
But with many tries I can not configure to run the burner motor.

I managed to configure the part of the # outputs Dir and Step axes XYZ and their speed of movement which are in my opinion ok. I still have to make the configuration so that the Nano adapts with the card QQ: 807252576 of the CNC to run the burner motor.

I carefully study the QQ card: 807252576 and to operate the burning engine it is necessary that the digital output # 11 is active in positive and variable square wave, it makes change the speed of the engine because it controls an amplifier made three power transistors connected in parallel. For the worse, becoming positive would make the card run the engine. For this card it is impossible to run the engine in the opposite direction.

So I tried several configurations in the file 'cpu_map.h' in the region of # line 79 to 93 but, without success. As I have trouble understanding the effect of some configuration I have not managed to find the right configuration.
At the same time with an electronic VOM I checked the digital output # 11 and nothing changed, it always remained at + 0.023V

 I have exhausted all my ideas, I ask for your help.

thank you very much

idorual

**Comment by chamnit** [comment]
I’m having a very hard time deciphering what your issue is. I suggest contacting your CNC manufacturer for help. Grbl runs on hundreds of different CNC machines. It’s hard to know what exactly your CNC requires.
