### ISSUE TITLE
Add ps2 keyboard support?

### ISSUE THREAD

**Issue by Harvie** [gnea/grbl#454]
PS2 keyboard only needs 2 pins and can be used as cheap pendant. I know this can be connected to PC, but sometimes it's better to have jog controls not dependent on PC. Eg. PC might not be available, might have different window active, or be completely off.

Do you think this could squeeze somewhere in remaining memory? At least as feature optionaly enabled in config.h?

![image](https://user-images.githubusercontent.com/276504/40585607-2e7cfc10-61b6-11e8-9b5a-33d148a367e2.png)

**Comment by chamnit** [comment]
In remaining memory and flash? Highly doubtful. There are literally a few hundred bytes left in the default build and a few dozen in other critical build configurations. FWIW, I’ve always wanted to have keypad control and this is something I’d like to have in the ARM version where there will be plenty of space and pins to do it.
