### ISSUE TITLE
Control XYZ via LCD and Keypad

### ISSUE THREAD

**Issue by Chip1972** [gnea/grbl#456]
HI. I manage to add an LCD and Keypad to GRBL1.1.
The LCD displays the gc_state.position[x] when I use the UGS.
But when I change  the gc_state.position[x], the LCD displays the new value, but nothing happens to the motor.
when I change  the sys_position[x], nothing happens too.
When I call system_execute_line("G91 G0 X1"), the command is not executed.
How move the motor from GRBL code?

**Comment by chamnit** [comment]
@Chip1972 : Please stop opening new issues threads related to seeking help with modifying Grbl. We've addressed this issue at least two times already, where we recommended that you not try to get an LCD to fit into the 328p and to use an external interface instead. The main reason being is that Grbl is tightly integrated and highly optimized. If you make alterations, you'll likely compromise something.
