### ISSUE TITLE
It it possible that grbl could report which hard limit was triggered?

### ISSUE THREAD

**Issue by dhughes** [gnea/grbl#460]
Looking at the [alarm codes csv file](https://github.com/gnea/grbl/blob/master/doc/csv/alarm_codes_en_US.csv), it seems as if any hard limit triggered is simply alarm code "1". Since grbl uses different pins for different axis limit switches, could we not have an alarm code that corresponds to the axis triggered? 

10 = x axis alarm
11 = y axis alarm
12 = z axis alarm

Not knowing which axis triggered makes resolving issues such as interference from steppers more difficult to debug. EG: Is it only one axis' limit that consistently triggers erroneously? If so, maybe the switch is bad. If all of my limit switches trigger erroneously then I probably have a problem with my wiring and need to consider was to resolve that.

**Comment by chamnit** [comment]
@dhughes : Nope. Not reliably. This question has been answered multiple times in the past. Comes down to the AVR not tracking which pin triggered the pin change interrupt. You have to test this and that isn't reliable. Fortunately the target ARM chip for the next version does give you which pin caused an external event.
