### ISSUE TITLE
$C - Check gcode Mode : explicit ON/OFF command, enhancement

### ISSUE THREAD

**Issue by xjnxjnxjn** [gnea/grbl#463]
It would be nice to explicitly set "Check gcode Mode" to ON/OFF.

$C    - Toggle 'Check gcode Mode'

enhancement 

$C 0 - Set 'Check gcode Mode' to OFF, if already OFF, ignore
$C 1 - Set 'Check gcode Mode' to ON, if already ON, ignore

**Comment by chamnit** [comment]
This may happen in the future, but not now.
