### ISSUE TITLE
small bug in commented out source code in config.h L196

### ISSUE THREAD

**Issue by ml-hn** [gnea/grbl#464]
https://github.com/gnea/grbl/blob/master/grbl/config.h#L196
`// #define INVERT_CONTROL_PIN_MASK ((1<<CONTROL_SAFETY_DOOR_BIT) | (CONTROL_RESET_BIT))`
should be:
`// #define INVERT_CONTROL_PIN_MASK ((1<<CONTROL_SAFETY_DOOR_BIT) | (1<<CONTROL_RESET_BIT))`
???

**Comment by chamnit** [comment]
Closing. Applied this fix and will be in the next push.
