### ISSUE TITLE
Homing in X0 Y700 Z0

### ISSUE THREAD

**Issue by Dragtstra** [gnea/grbl#467]
I want to home my machine in the top left corner (X0 Y700 Z0), but i want my X0 Y0 Z0 to me in the bottom left corner. how would i go about this without inverting my X and Y directions?

(Yes i want my machine to think it is at Y700 when it is home).

many thanks,
I

**Comment by chamnit** [comment]
You can't. Just set your G54 work coordinate frame to bottom left corner.

**Comment by Dragtstra** [comment]
I got it to work by punting a G92 x0 y700 z0 command at the end of the homing cycle. When using G54 my machine was moving.

Thanks for pointing me in the right direction.
