### ISSUE TITLE
Failure to restore mist output (M7) after door open event and cycle start

### ISSUE THREAD

**Issue by jandersonfrominventables** [gnea/grbl#468]
**Build:** 1.1f (exists since 1.1e)
**Required build configuration:**
```
#define ENABLE_SAFETY_DOOR_INPUT_PIN
#define` ENABLE_M7
```
**Problem description:** If M7 is active (set by gcode or override) and the door open even occurs both the mist (M7) and flood (M8) outputs are cleared. Once door event has cleared and the cycle start input is cycled the job continues but the mist output is not set although the flood is restored if set.

**Notes:** 
 - This is a regression from previous version such as 1.0c when the restore masking was added to the coolant_set_state argument in [protocol.c line 683](https://github.com/gnea/grbl/blob/master/grbl/protocol.c#L683).
 - A [pull request](https://github.com/gnea/grbl/pull/469) has been created with the mask fixed to include mist.

**Comment by chamnit** [comment]
Thanks. I’ll review this probably this weekend.
