### ISSUE TITLE
No output on D11 when laser mode enabled.

### ISSUE THREAD

**Issue by errno** [gnea/grbl#471]
I'm using GRBL 1.1f. When laser mode is enabled ($32=1) I get no output on D11 after issuing 'M03 S255' ($30=255). If I disable laser mode ($32=0), everything works as expected.

Here is my configuration (almost default):
```
$0=10
$1=25
$2=0
$3=0
$4=0
$5=0
$6=0
$10=1
$11=0.010
$12=0.002
$13=0
$20=0
$21=0
$22=0
$23=0
$24=25.000
$25=500.000
$26=250
$27=1.000
$30=255
$31=0
$32=1
$100=250.000
$101=250.000
$102=250.000
$110=500.000
$111=500.000
$112=500.000
$120=10.000
$121=10.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000
ok
```
Any ideas? Is it a bug, or a missconfiguration?

**Comment by chamnit** [comment]
It’s D11. See th pin configuration diagram in the wiki.

**Comment by chamnit** [comment]
Responded to your email not your corrected post. Laser mode does not turn on automatically for safety reasons. See wiki on conditions when it does turn on.

**Comment by errno** [comment]
Thank you for replies. Sorry for inaccurate data in the first post, I had to check before submitting.
