### ISSUE TITLE
Ading GRBL library to Arduino IDE for compiling GRBL

### ISSUE THREAD

**Issue by HuubBuis** [gnea/grbl#474]
When i follow these instruction (IDE version 1.8.5) for adding the GRBL library to the arduino IDE

"**_IMPORTANT: Select the grbl folder inside the grbl-XXX folder, which only contains the source files and an example directory_**"

I get an error message "**_A subfolder of your sketchbook is not a valid library_**", the library is not added and I can not compile GRBL. When I make a zip file of this folder, the (zip) library is added without errors and I can compile GRBL.

**Comment by chamnit** [comment]
Tested this on 1.8.5. Worked fine. No errors.

**Comment by 109JB** [comment]
Don't add the library from within the idea.  Just copy the grbl folder into the libraries folder using whatever file Management program you use (ie: windows explorer)

**Comment by OptimusPrimer1** [comment]
Same IT wont load no matter what I do..  I had installed grbl on uno before but I have not been able to get anything 4x or 5x.  I even wasted my money on a new desktop win 10... SAME Issues..  

Im losing my mind for 2 months on one damn problem.  Please I have tried everysingle combination of files taken out of left behind in the libraries folder.

IM so stressed right now I am losing all my hair.  This really shouldnt be that hard???  I don't understand?  Thank you for you help!

**Comment by HuubBuis** [comment]
You should be able to compile grbl using the steps described in the [WiKi](https://github.com/gnea/grbl/wiki/Compiling-Grbl)
or use the method from 109JB above. 

Before you add the library, you have to remove all (old) grbl directory(s) in your sketch folder map **libraries**
There may also be conflicting libraries. 
You could start by using a (new) clean sketch map. After removing all old libraries, you have to restart the Arduino IDE.
