### ISSUE TITLE
D13 and enabling a relay 

### ISSUE THREAD

**Issue by LukeBonathan** [gnea/grbl#487]
Hi there

I've just flashed an uno with grbl 1.1

When I have a relay connected to d13 and gnd it triggers on and off a bunch of times then seems to remain on. Is there a correct way to wire the D13 pin to enable a relay?

Thanks

**Comment by chamnit** [comment]
See [this](https://github.com/gnea/grbl/wiki/Frequently-Asked-Questions#my-spindle-turns-on-when-i-boot-up-my-arduino-for-a-second-or-two-why-does-it-do-this).
