### ISSUE TITLE
why me M3 is shutting down the spindle.？

### ISSUE THREAD

**Issue by gadenstar** [gnea/grbl#491]
I can't speak English .sorry

i think Control spindle speed, a like Super-PID 
https://item.taobao.com/item.htm?spm=a230r.1.14.1.6bd531139fLfiF&id=560241574916&ns=1&abbucket=12#detail

now control speed is ok，but M3 is stop ，M5 is run. =。= WHY？
so i need help , thanks

**Comment by neilferreri** [comment]
Without any details on your machine, it sounds like you'll just need to invert the signal. This can be done with a simple circuit using a couple resistors and an npn transistor.

**Comment by gadenstar** [comment]
please close this issues.

in `config.h` line206 

`// Inverts the spindle enable pin from low-disabled/high-enabled to low-enabled/high-disabled. Useful
// for some pre-built electronic boards.
// NOTE: If VARIABLE_SPINDLE is enabled(default), this option has no effect as the PWM output and
// spindle enable are combined to one pin. If you need both this option and spindle speed PWM,
// uncomment the config option USE_SPINDLE_DIR_AS_ENABLE_PIN below.
#define INVERT_SPINDLE_ENABLE_PIN // Default disabled. Uncomment to enable.`

Uncomment is OK
