### ISSUE TITLE
CNC spindle not turning

### ISSUE THREAD

**Issue by WiCh18** [gnea/grbl#494]
Hi everyone,

I'm new here and still learning how your website works.

My DIY cnc and laser engraver is working fine with the 0.5W and 15W laser module so far with lasergrbl.
Today I was trying to set up the cnc spindle (12V, max. 11000rpm) and used grblcontrol for that. 
Moving the axes is working correctly.

However turning the spindle doesn't work. I can hear a click sound on the control board when I use M3 and M5, but the spindle doesn't turn.

Does anyone know how to fix this?

Appreciate your help! 

![tb2oe5zfmcqbknjszfgxxx_kxxa_ 527724047](https://user-images.githubusercontent.com/41591316/43095176-8742e446-8ee7-11e8-8cd3-8f3bbfc0d27f.jpg)
![20180723_233354](https://user-images.githubusercontent.com/41591316/43095197-9a0c4892-8ee7-11e8-97ef-43cff94fbcb6.jpg)

**Comment by svenhb** [comment]
You forgot to connect your spindle:
![image](https://user-images.githubusercontent.com/19973251/43143436-0c2bd136-8f5b-11e8-9c59-906a70649aa9.png)
