### ISSUE TITLE
Probing error ALARM:PROBE

### ISSUE THREAD

**Issue by boesenbe** [gnea/grbl#495]
Hi,

I try to solve this problem now for one and a half days. I designed my own CNC machine and homeing it is no problem. But when I start the **UGS** it gives me an ```ALARM:PROBE``` but my Probe is not probing nor touching anything to close a circuit. 

![image](https://user-images.githubusercontent.com/18379852/43183276-d4fa4fe6-8fe4-11e8-9971-fe3f67e92b11.png)

When I start probing (after homing, repositioning to my workpice and putting the axes to 0) I get a bunch of errors. 

![image](https://user-images.githubusercontent.com/18379852/43183422-61e3de86-8fe5-11e8-91ea-2f6d295f8840.png)

![image](https://user-images.githubusercontent.com/18379852/43183548-ccf514ba-8fe5-11e8-869b-2fb4f5ed185a.png)

I tried different versions of UGS, tried to invert the probe pin. A pull down resistor is not needed (I read it in several forums but maybe I am mistaken?). I am followed this [tutorial](https://www.youtube.com/watch?v=kpz-6x_synE).

I use an STM103 ([source code](https://github.com/usbcnc/grbl))  and no Arduino as a controller for grbl. When I put the Probing pin to Ground the error goes away and I can start probing. 

Here are my settings:

```
$0 = 64    (Step pulse time, microseconds)
$1 = 0    (Step idle delay, milliseconds)
$2 = 7    (Step pulse invert, mask)
$3 = 7    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 0    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 0    (Status report options, mask)
$11 = 0.010    (Junction deviation, millimeters)
$12 = 0.002    (Arc tolerance, millimeters)
$13 = 0    (Report in inches, boolean)
$20 = 0    (Soft limits enable, boolean)
$21 = 1    (Hard limits enable, boolean)
$22 = 1    (Homing cycle enable, boolean)
$23 = 0    (Homing direction invert, mask)
$24 = 25.000    (Homing locate feed rate, mm/min)
$25 = 500.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 4.000    (Homing switch pull-off distance, millimeters)
$30 = 10    (Maximum spindle speed, RPM)
$31 = 0    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 640.000    (X-axis travel resolution, step/mm)
$101 = 640.000    (Y-axis travel resolution, step/mm)
$102 = 640.000    (Z-axis travel resolution, step/mm)
$110 = 600.000    (X-axis maximum rate, mm/min)
$111 = 600.000    (Y-axis maximum rate, mm/min)
$112 = 600.000    (Z-axis maximum rate, mm/min)
$120 = 40.000    (X-axis acceleration, mm/sec^2)
$121 = 40.000    (Y-axis acceleration, mm/sec^2)
$122 = 40.000    (Z-axis acceleration, mm/sec^2)
$130 = 250.000    (X-axis maximum travel, millimeters)
$131 = 150.000    (Y-axis maximum travel, millimeters)
$132 = 90.000    (Z-axis maximum travel, millimeters)
```

MANY Thanks and have a nice day.

**Comment by chamnit** [comment]
Grbl officially supports only the 328p Arduino processor. You’ll need to ask the author of the STM port for a fix.
