### ISSUE TITLE
Enhancement -  Disable Z axis so homing works when there are only two axis in use.

### ISSUE THREAD

**Issue by RWL-69** [gnea/grbl#496]
As I am new to GRBL as I want to use a laser etcher for making circuit boards.  I have a Chinese laser and using a Mega as a controller.  I installed limit switches for safety but when I tried to enable homing, I keep getting errors because there is no Z axis.

I have read some lists that recommend installing a switch to manually fake a limit switch engaging.  I think it would be better if there was a way to ignore the Z axis if there is no Z motor using some flag or modify the homing $22=X  where X is a different mode.

1 - Normal XYZ axis
2 - 2 Axis XY

This may be useful for future when GRBL is capable of handling more axis.

**Comment by biasedlogic** [comment]
Please, read the wiki and search this issue tracker. This has been addressed multiple times, the configuration is there in the config.h file

**Comment by RWL-69** [comment]
Sorry it was late and I was tired.  I read the wiki and there was no mention that I could find.  I also looked through the issues last night before posting.   Didn't see it.

I will search closer now.
