### ISSUE TITLE
different speed on each axis in the same time 

### ISSUE THREAD

**Issue by vany007** [gnea/grbl#505]
Hello ladies and gentlemen
i would like to  control the axis separated and also control the speed of the rotation.
for your imagine:
i wanne say X-axis go to 500 with 100rpm

view moments later (random moment) i wanna ad something
-> i would like to activate the movement  along the Y-axis
 it should go to Y to 100 with 10 rpm

Is this possible?

**Comment by chamnit** [comment]
You'll need to use the jogging interface to do something like that. See the wiki on how to implement real-time jogging input. Jogging doesn't support spindle changes, but you can implement the same process via normal g-code to get what you want.
