### ISSUE TITLE
3 Axis + Laser Control in Laser Mode?

### ISSUE THREAD

**Issue by alfarosarij** [gnea/grbl#506]
Hi every one,
I am designing my laser cut CNC machine. The laser head is: https://www.alibaba.com/product-detail/High-power-150W-200W-500W-auto_60467891657.html

I know that in laser mode it possible to control two axis, but I doubt is it possible to control 3axis+ Laser in laser mode of Grbl?

Please contact me with : farokhi.sarij@gmail.com

**Comment by chamnit** [comment]
Yes you can control Grbl's 3-axes with a laser. That is the default mode.

**Comment by alfarosarij** [comment]
Thank you for your reply.
