### ISSUE TITLE
limit switch problem

### ISSUE THREAD

**Issue by nikki-reprap** [gnea/grbl#507]
I have a problem with my limit switchs on my woodpecker board I have wired them as per the wiki but they dont  work if only one on the axis is pressed. I have switches for the Y maximum and minimum  and X maximum and minimum The only difference is i have wired them NO 
I am using grbl 1.1

thanks

**Comment by biasedlogic** [comment]
The 'only difference' is the 'only problem'. NC in series is effectively OR, NO in series is AND
