### ISSUE TITLE
1.1.e svn 664 : minor bug

### ISSUE THREAD

**Issue by LETARTARE** [gnea/grbl#51]
in '**jog.c::uint8_t jog_execute(plan_line_data_t *pl_data, parser_block_t *gc_block)**'

> #ifdef USE_LINE_NUMBERS
>    // pl_data->line_number =  gc_block.values.n;
>     pl_data->line_number =  gc_block->values.n;
> #endif

**Comment by chamnit** [comment]
@LETARTARE : Thanks! I've updated the code and it'll be included in the next push.
