### ISSUE TITLE
Watchdog?

### ISSUE THREAD

**Issue by oxygenic** [gnea/grbl#512]
Is the watchdog of the MCU used in GRBL? If not where in code are suitable places to re-trigger it?

**Comment by cri-s** [comment]
It is used as  optional software timer for ENABLE_SOFTWARE_DEBOUNCE
Otherwise there is no WDT used.

2018-09-01 19:44 GMT+02:00, oxygenic <notifications@github.com>:

**Comment by chamnit** [comment]
The WDT triggers an interrupt. It can be used anytime if the code is very lightweight. Although tread carefully because Grbl is highly tuned.
