### ISSUE TITLE
Missed steps at movement start

### ISSUE THREAD

**Issue by toktuff** [gnea/grbl#522]
I would like to check if there is some way to work around this issue I'm having.

I'm running my CNC with external drivers (DM542T from stepper online to be exact). At the very start of the motion (or with short motions, like 1mm jogs) it loses some steps.

After some testing I figured out that if I let the steppers be powered up all the time ($1=255) then this wasn't an issue.

It would seem to me that these drivers would like to have a delay between being enabled and the first step signals.

Is this something that is possible to configure?

**Comment by lnelson214** [comment]
I don't think there is an initial delay setting, but is there some problem with leaving them enabled all the time?

**Comment by toktuff** [comment]
The problem is that they will be getting high current from the controllers and generating heat. It feels unnecessary the have the steppers hot when idle.

My Z axis is a bit extra problematic since it needs full current all the time. (The other axes can use a "half current when idle" feature available on the drivers).

**Comment by toktuff** [comment]
I'll keep my current configuration.
