### ISSUE TITLE
HY inverter PWM and spindle enable

### ISSUE THREAD

**Issue by jschoch** [gnea/grbl#528]
I'm hooking up a HY inverter and it appears that it needs an analog 0-5v speed signal (VI pin) AND the FOR (24V) pin pulled down to it's digital reference ground.   I've tried M3S0 but the inverter does not interpret the low voltage on the speed signal pin as disable.

I can hook up a 3v relay and just rely on the PWM signal to also activate the relay and hope the ranges are ok.   

I'd prefer to have a digital signal driving the enable relay and keep the PWM signal connected to the VI (0-5v) input.  Is this possible?  

Is it a bad idea to rely on the PWM signal to drive the enable 3v relay?  My min speed is 7200 RPM which is about 1.9v PWM.  Do I need to add a low pass filter or something?

**Comment by biasedlogic** [comment]
"HY inverter" is not enough to identify what you've got there

**Comment by jschoch** [comment]
i believe the model number is: USTS15220V

it is a 1.5kw huanyang 220 inverter and an 800w spindle.

**Comment by biasedlogic** [comment]
Use the spindle enable output from grbl to drive an NpN transistor to control the FOR input of the inverter (either directly or via a relay)

**Comment by jschoch** [comment]
Thanks for the feedback.

From my research it seems that grbl-Mega is also a decent option since it has the enable pin separated.

**Comment by biasedlogic** [comment]
For all i know, so is it with Arduino Uno as well...

**Comment by Harvie** [comment]
Now there seems to be quite elegant solution integrating Huanyang RS485 communication directly to GRBL, i would be happy if you can help with testing:
https://github.com/terjeio/grblHAL/issues/68
