### ISSUE TITLE
Need some help with project "Multiaxis Stepping Coprocessor"

### ISSUE THREAD

**Issue by jsb1** [gnea/grbl#53]
@chamnit 
#46 is part of it. And I got some good hints from You. Would You like to discuss a little?

The idea is to make a cnc controller board a simple coprocessor executing steps. It gets prepared line segments over a simple binary protocol and executes them. Primary target is existing hardware with old and slow AVR processors. Think of having grbl main code running on raspberry pi (or something else) sending line segments to something which does the timer ISR. (Yes, there is a lot of trouble with peripherals like endstops etc. - Just let me try :-) )

Currently implemented is a communication protocol over serial and 8-Bit bresenham, doing more than 70000 steps/s on six axis - all at full speed. With some timing delays for stepper drivers (1-2 us) and running serial communication it is still more than 60000 (on 16 MHz 328p). That looks promising.

One open item is step timing. Ranade does not work well as I understand. Maybe linear timer advance per line segment could to the job.
Another problem is a bit tricky: how to initialize the bresenham error value on each line segment? Than means: Should I position slow axis pulses at be beginning, the middle or the end? Make it random? Or track an initial value on host and send it?
(Random is interesting. It distributes aliasing effects over a wider spectrum. Did anyone try that?) 
AMASS is good - but "fine tuning". Or would it help me with bresenham issue?
Homing and probing is a bigger problem. The host processor is not realtime.

I can try all those things.

What I'm asking You:
What is You general opinion about this idea?
Do You have some hints how to generate those stepping line segments in grbl? They have to be shorter than 128 steps but not too short at high speeds (limit is about 500-1000 segments/s). 

It is not important to have my "experiments" in grbl main project. And 'im not asking You to make any changes. Just give me a bit of Your experience! :-)

**Comment by chamnit** [comment]
@jsb1 : I have also toyed with this idea in the past a few times, but ultimately dismissed it. G-code streaming is a very clear and independent boundary for GUIs to interface with a motion controller. No other dependencies or off-site real-time processes required. However, if you'd like to talk about it some more, please email me offline.
