### ISSUE TITLE
prescaler 256 in cpu_map.h

### ISSUE THREAD

**Issue by kolemjdouci** [gnea/grbl#539]
Hello, would it be possible to add a line for 256 prescaler in cpu_map.h? I would like to use it to control my ESC.

 // Prescaled, 8-bit Fast PWM mode.
  #define SPINDLE_TCCRA_INIT_MASK   ((1<<WGM20) | (1<<WGM21))  // Configures fast PWM mode.
  // #define SPINDLE_TCCRB_INIT_MASK   (1<<CS20)               // Disable prescaler -> 62.5kHz
  // #define SPINDLE_TCCRB_INIT_MASK   (1<<CS21)               // 1/8 prescaler -> 7.8kHz (Used in v0.9)
  // #define SPINDLE_TCCRB_INIT_MASK   ((1<<CS21) | (1<<CS20)) // 1/32 prescaler -> 1.96kHz
  #define SPINDLE_TCCRB_INIT_MASK      (1<<CS22)               // 1/64 prescaler -> 0.98kHz (J-tech laser)

I'm new to arduino and I'm not sure how to do that.

Thank you

Kamil

**Comment by RunnyBore604** [comment]
#define SPINDLE_TCCRB_INIT_MASK      ((1<<CS22) | (1<<CS21)) // 1/256 prescaler -> 244.140625Hz

**Comment by kolemjdouci** [comment]
Thank you for your help

**Comment by kolemjdouci** [comment]
Hello, If I would like to set frequency 490hz, I should set 1/128 prescaler?

Like this:

#define SPINDLE_TCCRB_INIT_MASK ((1<<CS22) | (1<<CS20)) // 1/128 prescaler -> 488.28125Hz
