### ISSUE TITLE
Ability to set the Current Working/Machine position

### ISSUE THREAD

**Issue by DanRegalia** [gnea/grbl#544]
Is there a code in GRBL currently that allows you to set the current working/machine position?  The system I'm using requires the ability to zero on a piece of stock and set the Z Axis to a specific height.  

If there isn't a command that does that, how hard is it to throw one in there.  

Thanks

**Comment by langwadt** [comment]
http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g10-l20

**Comment by langwadt** [comment]
use G92 if you want to change machine coordinates, though I don't see why you would want to

**Comment by chamnit** [comment]
Machine position is set by homing or a power cycle. There is not explicit command to alter machine position to force users to use work positions.
