### ISSUE TITLE
Typo in gcode.c

### ISSUE THREAD

**Issue by bdring** [gnea/grbl#556]
Is line number 856 in gcode.c correct?

`if (command_words & ~(bit(MODAL_GROUP_G3) | bit(MODAL_GROUP_G6 | bit(MODAL_GROUP_G0))) ) { FAIL(STATUS_INVALID_JOG_COMMAND) };`

Should there be a closing parenthesis after MODAL_GROUP_G6?

**Comment by chamnit** [comment]
There sure is. Thanks Bart!

**Comment by bdurbrow** [comment]
This needs to be applied to the grbl-mega repository as well.
