### ISSUE TITLE
Parsing incoming messages from GRBL

### ISSUE THREAD

**Issue by MeJasonT** [gnea/grbl#558]
I was wondering if some kind person could write a basic parse routine for me to run on another Arduino which would sniff the data from the PC/Grbl communication Link,  By using a second arduino i can receive the return messages from the grbl TX pin - This is not affecting the operation of the pc/grbl control.
Im currently able to read the return string and output it via the arduino IDE serial monitor.

I would like to be able to parse the data into an array (block) so i can manipulate the values returned for Spindle speed and the operation of suds/coolant pump and the spindle direction.  I am attempting to make an interface between grbl and my milling machine motors variable frequency drive.  To cut a long story short - the high frequency noise from the VFD upsets the grbl operation, im wanting to transmit the commands over RS485 between the board sniffing the signals and the VFD.  The return message has the beauty of telling me when a function has been performed and not when its being queued which is what i would get from the other side of the comms link. 
Being able to do this would also benefit those wishing to build a torch height controller for a plasma table or any other project where reporting would be an advantage as its not possible to provide any further resources from grbl to transmit from a second serial port due to the maxed out memory especially on the UNO variant.

 I can see its possible and have the ability to do everything apart from parsing the message string,  any help would be most appreciated.

**Comment by chamnit** [comment]
@MeJasonT : Since this isn't a direct Grbl issue, I'm closing this thread, but people can still respond to your request.

**Comment by MeJasonT** [comment]
Thanks Sonny

**Comment by MeJasonT** [comment]
On a side note - When are us clankys going to get a point and click version of GRBL for M0, its still cloak and dagger amongst the programming fraternity.

**Comment by MeJasonT** [comment]
For anyone interested.
uses Nick Gammon's RS485 sketch and library

`//====================================================================
// parseGRBLRS485.ino
// Original GRBL Parse code with RS485 comms added
// Parse code for GRBL CNC
// 13/11/2018
// Ver 1.0
//====================================================================

#include "RS485_protocol.h"
#include <SoftwareSerial.h>

//  RS485 Communication variables /////////////////////////////////////

SoftwareSerial rs485 (2, 3);  // receive pin, transmit pin
 
const byte ENABLE_PIN = 4;
int channel = 0;
int deviceID = 0;
int function = 2;
int data = 0;

const byte LED_PIN = 13;

// Parsing GRBL message variables  ///////////////////////////////////////////

const byte numChars =71;
char receivedChars[numChars];
char tempChars[numChars];        // temporary array for use when parsing

//Feed and Speed variables
char FSMsgGRBL[12];
int FS_FeedMsg = 0;
int FS_SpeedMsg = 0;

//Overide variables
bool OvMsg = false; //Ov message being transmitted
int CmdCoolant = 0;
int CmdSpindleCW = 0;

// Variables to hold Message blocks

char GRBL_msg1 [numChars] = {0};
char GRBL_msg2 [numChars] = {0};
char GRBL_msg3 [numChars] = {0};
char GRBL_msg4 [numChars] = {0};
char GRBL_msg5 [numChars] = {0};
char GRBL_msg6 [numChars] = {0};


boolean newData = false;

//============================================================================

// callback routines RS485 Comms
  
void fWrite (const byte what)

      {
      rs485.write (what);  
      }
      
    int fAvailable ()
      {
      return rs485.available ();  
      }
    
    int fRead ()
      {
      return rs485.read ();  
      }


void setup() {
    
    
    Serial.begin(115200);
    rs485.begin (28800);
    pinMode (ENABLE_PIN, OUTPUT);  // RS485 IC driver output enable
    pinMode (LED_PIN, OUTPUT);  // built-in LED - lights on transmission error

}  // end of setup

//============

void loop() {

  byte level = (data);
  
    recvWithStartEndMarkers();
    if (newData == true) {
        strcpy(tempChars, receivedChars);
            // this temporary copy is necessary to protect the original data
            //   because strtok() used in parseData() replaces the commas with \0
        parseData();
        outputParsedData();
        newData = false;
        
        
    }
}  // End of loop

//============

void recvWithStartEndMarkers() {
    static boolean recvInProgress = false;
    static byte ndx = 0;
    char startMarker = '<';
    char endMarker = '>';
    char rc;

    while (Serial.available() > 0 && newData == false) {
        rc = Serial.read();

        if (recvInProgress == true) {
            if (rc != endMarker) {
                receivedChars[ndx] = rc;
                ndx++;
                if (ndx >= numChars) {
                    ndx = numChars - 1;
                }
            }
            else {
                receivedChars[ndx] = '\0'; // terminate the string
                recvInProgress = false;
                ndx = 0;
                newData = true;
            }
        }

        else if (rc == startMarker) {
            recvInProgress = true;
        }
    }
}// End of recvWithStartEndMarkers

//============

void parseData() {      // split the data into its parts

    char * strtokIndx; // this is used by strtok() as an index

  //Parse into Blocks based on "|" Delimiter
  
        // machine state
            strtokIndx = strtok(tempChars,"|"); // Find first part of string (Machine State Idle, Run, Alarm) 
            strcpy(GRBL_msg1, strtokIndx);      // write characters from string to machine state variable
            
        // machine position   
            strtokIndx = strtok(NULL,"|"); // look for next data block in string  
            strcpy(GRBL_msg2, strtokIndx); // write characters from string to machine position variable 
             
        // BF god knows - alarms ?
            strtokIndx = strtok(NULL,"|"); // look for next data block in string      
            strcpy(GRBL_msg3, strtokIndx); // write characters from string to BF variable  
            
        // feed and spindle speed
            strtokIndx = strtok(NULL,"|"); // look for next data block in string     
            strcpy(GRBL_msg4, strtokIndx); // write characters from string to Feed&Speed variable 
             
        //Ov Overides 1% to 200%
            strtokIndx = strtok(NULL,"|"); // look for next data block in string  
            strcpy(GRBL_msg5, strtokIndx); // write characters from string to Overide variable 
             
        //machine command status
            strtokIndx = strtok(NULL,"|"); // look for next data block in string  
            strcpy(GRBL_msg6, strtokIndx); // write characters from string to machine command status variable 
            
        //anything else
   
} //End of parseData

 
//============

void outputParsedData() 
     {
  
          ParseFS (); // Parse feed and speed values from FS Block
          ParseOv_A (); //Reads first character in buffer looking for "O" then knows commands follow "A:" (A:SF Buffer) 


                   // comment out on completion - sending serial messages not required, debug only 
                   Serial.print("Spindle Speed ");
                   Serial.print(FS_SpeedMsg);
                   Serial.print(" Spindle ");
                   Serial.print(CmdSpindleCW);
                   Serial.print("  Coolant ");
                   Serial.println(CmdCoolant); 
                     
         DoBusComs ();//Transmit values over RS485 link - Order of presidence goes here as parse has to happen first  

    }//end of outputParsedData


//Feeds and speeds  FS Message GRBL /////////////////////////////////////////////////////////


void ParseFS ()
{
  
//GRBL_msg4 array containing Feed & Speed message characters
   
    char * partOfString; // this is used by strtok_r() as an index
    
    partOfString = strtok (GRBL_msg4,":"); // get the first part - the string
    strcpy(FSMsgGRBL, partOfString);     // copy it to inputCsvString
    
    partOfString = strtok (NULL, ","); // this continues where the previous call left off
    FS_FeedMsg = atoi(partOfString);     // convert this part to an integer
    
    partOfString = strtok (NULL, ","); // this continues where the previous call left off
    FS_SpeedMsg = atoi(partOfString);   // convert this part to a float// actually an int
 
}//End of ParseFS

// Parse Overide Ov Message GRBL ////////////////////////////////////////////////////////////

void ParseOv_A ()
{
  //GRBL_msg5 array containing Overide message characters  
   
      if (GRBL_msg5[0] == 'O')// Ov statement when true check machine command instructions
      
      {
              if (GRBL_msg6[0] == 'A')
               {
                
              Serial.print("Got A ");
              Serial.println(GRBL_msg6);
              
                      
              if (GRBL_msg6[2] == 'S')
                    {
                    CmdSpindleCW =1;
                 
                    }
              if(GRBL_msg6[2] == 'C')
                    {
                    CmdSpindleCW = 0;
                            
                    }
                    
         
                if (GRBL_msg6[2] == 'F'|(GRBL_msg6[3] == 'F'))
                    {
                    CmdCoolant = 1;           
                    }                                                    
                else
                   {
                   (CmdCoolant = 0);      
                                          
                   }
                                                         
              }//End - seeking "A" in GRBL_msg6
              
              if(strlen(GRBL_msg6) == 0) // makes sure spindle direction and coolant conditions are off woth no signal present
              {
              CmdSpindleCW = 0;  
              CmdCoolant = 0;  
              }                                
      }
      
} // end of ParseOv_A 

// RS485 Communication command structure ////////////////////////////////////////////

void DoBusComs ()
  {
        
    // assemble message - what to send to Variable Frequency Drive /Spindle Drive
    byte msg [] = { 
       deviceID,     // device 1
       function,     // Used to expand future messages fixed at 2 (currently type 2 = master transmit message - future could be type 3 ask for analogue response etc)
       FS_SpeedMsg,  // spindle speed
       CmdSpindleCW, // spindle direction
       CmdCoolant,   // activate suds pump
       data          // Spare data block
    };
  
    // send to slave  
    digitalWrite (ENABLE_PIN, HIGH);  // enable sending
    sendMsg (fWrite, msg, sizeof msg);
    //delayMicroseconds (660);
    digitalWrite (ENABLE_PIN, LOW);  // disable sending
    
// Receive message from slave device // not interested - one way comms only
// blocking grbl receive, cant use it
// causes stray 128 value on receive FS_SpeedMsg
 
    // receive response  
    //byte buf2 [20];
    //byte received = recvMsg (fAvailable, fRead, buf2, sizeof (buf2) - 1); 
   
    
      // only send once per successful change
    //if (received)
         //{
//                  if (buf2 [0] != 0)//0 is master
//                    return;  // not my device
//                    
//                  //if (buf2 [1] != Cmd)
//                    //return;  // unknown command
//                  
//              byte msg2 [] = {
//                     0,  // device 0 (master)
//                     //RXFunc,
//                     //RXdata1,
//                    // RXdata2,
//                      
//               };
               
              //delay (10);  // give the master a moment to prepare to receive 
              ////Serial.println(buf2[2]);   
              //digitalWrite (LED_PIN, received == 0);  // turn on LED if error
              //
              //        if (buf [1] >= 20){
              //        
              //               InputDevice= buf2 [1];
              //               Inputvalue = buf2 [2];// write coil value to a variable
              //               Serial.print ("A"); Serial.print (InputDevice); Serial.print (","); Serial.print (Inputvalue);Serial.println ("!");
              //        }
              //
              //   // old_level = data;
          
          
         // }  
  
  }// End of DoBusComs
  
`

**Comment by MeJasonT** [comment]
I have no idea why it displayed the code like this, but its all there - unlike me

**Comment by MeJasonT** [comment]
Follow link here
[https://forum.arduino.cc/index.php?topic=578683.0](url)

**Comment by jschoch** [comment]
I used some existing work and put it in an arduino library

It puts the data into a handy struct.  You just need to pass it the string from serial.

https://github.com/jschoch/grbl_chat
