### ISSUE TITLE
grbl 1.1f on Uno R3 low mem warning?

### ISSUE THREAD

**Issue by Psyc0Flyer** [gnea/grbl#559]
I am trying to upload 1.1f onto my Uno R3 for a "K40" laser build and I keep getting this warning. Is this normal as I have not changed the code at all? Is it safe to continue and use with LightBurn?

> 
Sketch uses 30204 bytes (93%) of program storage space. Maximum is 32256 bytes.
Global variables use 1633 bytes (79%) of dynamic memory, leaving 415 bytes for local variables. Maximum is 2048 bytes.
Low memory available, stability problems may occur.
>

**Comment by DenisShelema** [comment]
https://github.com/gnea/grbl/wiki/Frequently-Asked-Questions
