### ISSUE TITLE
arduino err

### ISSUE THREAD

**Issue by asigraph** [gnea/grbl#56]
hi all
the compiler err say
Sketch uses 30,284 bytes (98%) of program storage space. Maximum is 30,720 bytes.
Global variables use 1,631 bytes (79%) of dynamic memory, leaving 417 bytes for local variables. Maximum is 2,048 bytes.
Low memory available, stability problems may occur.
 thes is ok or not?
thanks asi

**Comment by chamnit** [comment]
@asigraph : It's not an error, but a low memory warning. It's ok.

**Comment by asigraph** [comment]
i thenk u chamnit
