### ISSUE TITLE
G92.1 vs G92.2

### ISSUE THREAD

**Issue by Harvie** [gnea/grbl#564]
Is there difference between G92.1 vs G92.2 on GRBL? I understand that on Linux-CNC it makes difference in how G92 is saved, but i don't see how this could work on GRBL. Is there any difference between them?

I am working on bCNC and i want to do GRBL cleanup after job is finished.
Is it good idea to send G92.1 or G92.2 after each job, to make sure that there is no G92 setting left from g-code? or is it better to leave G92 set in GRBL between jobs?

**Comment by chamnit** [comment]
@Harvie : Grbl doesn't support G92.2. Just G92 and G92.1. 

Standard practice for machine operation is to issue an M2 or M30 to automatically reset the g-code parser. Or issue a soft-reset, which will do essentially the same thing. It's not recommended to ever leave a G92 offset active. This can cause unexpected behavior and crashes.
