### ISSUE TITLE
repeating code

### ISSUE THREAD

**Issue by cjren92** [gnea/grbl#568]
is there any simple way to repeat a code X number of times?
I have a simple Gcode that i would like to repeat X number of times, how would i write this into the python script?
my g code is only two lines long would there be any other way to do this?

**Comment by chamnit** [comment]
Copy and paste. Use a for-loop. Theres lots of ways. If you mean by g-code, not with Grbl's supported g-code commands. There is one in full g-code implementations. Grbl doesn't have the room and can't do it due to how it streams.
