### ISSUE TITLE
Jog Motion

### ISSUE THREAD

**Issue by quangvi** [gnea/grbl#58]
Hi @chamnit , in jog motion feedrate override not accept ,  can you fix problem and  add buton Feed/Rapid , if the buton is on , axis can move with Rapid. the buton is off ,axis can move with Feedrate

**Comment by chamnit** [comment]
@quangvi : This is intentional. Feedrate override do not work with jog motions.

**Comment by quangvi** [comment]
no , Hi @chamnit  Feedrate override do not work with jog motions, but problem is happen, if the axis had move slow speed , i want to change fast speed , i only press stop or reset,
