### ISSUE TITLE
Warning in eeprom.c 

### ISSUE THREAD

**Issue by quangvi** [gnea/grbl#581]
Hi @chamnit, in my compliler warning is line 133 and 144:
    checksum = (checksum << 1) | (checksum >> 7);
may be correct:
    checksum = (checksum << 1) || (checksum >> 7);
do you think about it, Thanks you.

**Comment by chamnit** [comment]
The EEPROM checksum is a known bug. It's been there since the beginning, well before I started working on this project. The conclusion was that it shouldn't be touched because if a fix was put in, everyone's EEPROM would automatically be wiped.
