### ISSUE TITLE
adjust speed and power

### ISSUE THREAD

**Issue by Frittella** [gnea/grbl#591]
good day sorry I'm new in the use of grbl I downloaded the latest version and I have EleksLaser-A3 Pro 2500mW Laser but I can not understand how to change the speed and power of the laser in real time I saw that in some previous version could be changed to the corner of the page of grbl but in version 1.1 there is not and I can not set it except in the creation of the job
if you can help me thank you so much

**Comment by Harvie** [comment]
I guess that you are asking in the wrong place. This is GRBL firmware that runs on your control board.
You need to use some software on your PC to send commands to it. Some might have such feature. Some might not. Personaly i use bCNC and it has GUI for applying such realtime overrides:

![image](https://user-images.githubusercontent.com/276504/51004561-816a6c80-153b-11e9-9afd-6c1f88e3990c.png)

**Comment by chamnit** [comment]
You will need a GUI that supports Grbl's spindle speed overrides.
