### ISSUE TITLE
woodpecker cnc jogging and limit switch query

### ISSUE THREAD

**Issue by BlakusSenior** [gnea/grbl#596]
On a Woodpecker controller (Same as pictured on the pin diagram here) ,
With both Z limit switch pins shorted I can still jog the axis with Grbl jog arrows. Is that normal? I wouild think that the limit switches should function at all times but I'm still at the setup stage.

**Comment by chamnit** [comment]
Grbl will allow motions if you don't have it setup for hard limits. Otherwise Grbl just uses the limits for homing.
