### ISSUE TITLE
Newbie - Help Needed

### ISSUE THREAD

**Issue by PCPayne** [gnea/grbl#599]
Hi All, im a newbie in cnc engraveing.
I have a arduino uno and x2 TB6560 Drivers. 
For some reason the motors turn but dont seem to go smoothly and are all over the place.
I have the connections as follows:
A+=Red / A-=Green / B+=Blue / B-=Black
CLK+ = Pin2
CW+ = Pin5

I had this sort of working a long time ago but ive lost all my notes etc, i have already uploaded the latest hex file. Would appretiate any help you can give please.

**Comment by HuubBuis** [comment]
For just checking the motor turns, you only need to connect the stepper pulse pjn(s) (CLK+ and CLK-). You have connected CLK+ **but you also need to connect CLK-**. Connect CLK- to ground!

If this works, connect the direction signal (CW+) to Pin5 and (CW-) to Ground.

If this works, connect the enable signal (EN+) to Pin8 and (EN-) to Ground.

**As always, start by trying stepping at a very slow rate (1 mm /min), the current at half the max current of the stepper and exitation (micro stepping) at full step. You should see the step led on the TB6560 board blink!**
