### ISSUE TITLE
Reason for sleep option?

### ISSUE THREAD

**Issue by jahnj0584** [gnea/grbl#6]
Just curious. What's the benefit of just powering down your machine? Does it hold over the temporary g92 info?

**Comment by chamnit** [comment]
@jahnj0584 :  Allows a user to disable their stepper drivers without altering the settings. Useful for end of job automated shutdown. See documentation for more reasons.

**Comment by jahnj0584** [comment]
OH, like automation or when you're cutting without being in the room.
Gotcha
