### ISSUE TITLE
Wiki image low quality / hard to read (Page: Connecting Grbl)

### ISSUE THREAD

**Issue by MidnaRinku** [gnea/grbl#601]
Can you please update the image on the "Connecting Grbl" wiki page? The labels on the board don't match the pins and that makes it kinda hard to read. I've made some high quality images in Inkscape, if you want to use that. Cheers!

![arduino uno grbl](https://user-images.githubusercontent.com/7835161/52511952-bfbe7e80-2c02-11e9-8dd1-7624243ef2a2.png)
![arduino nano grbl](https://user-images.githubusercontent.com/7835161/52511957-c3520580-2c02-11e9-863d-b60dda0d1a5f.png)
![arduino uno](https://user-images.githubusercontent.com/7835161/52511958-c51bc900-2c02-11e9-916f-ac832c3f069b.png)
![arduino nano](https://user-images.githubusercontent.com/7835161/52511960-c64cf600-2c02-11e9-991f-0745f4797f5d.png)

**Comment by 109JB** [comment]
The wiki ages aren't locked from editing, so feel free to update the wiki page yourself.

**Comment by MidnaRinku** [comment]
Oh I didn't know that. This was my first post ever on github as well, still have no idea how things work around here. I'd prefer if someone else would put it on the wiki, I don't want to screw things up lol.
