### ISSUE TITLE
Problem after flashing grbl_v1.1f.20170801.hex PLEASE HELP

### ISSUE THREAD

**Issue by kapalevan** [gnea/grbl#610]
Hello,

I flash my laser with grbl_v1.1f.20170801.hex

After flashing laser always turned on, and not functioning. 

I can't use it with with any engraving software anymore.

Please help.

**Comment by notsolowki** [comment]
depending on the type of control board your using you may need to change the cpu_map.h file to reassign the pins

**Comment by chamnit** [comment]
Check your pin configuration is compatible with v1.1. Also make sure your settings are correct.

**Comment by kapalevan** [comment]
Thank you I will try.
