### ISSUE TITLE
GRBL stalls with "Bf:14,0"

### ISSUE THREAD

**Issue by Elmi77** [gnea/grbl#614]
Working with the most recent version from GIT I stumble upon a strange problem. I'm quite sure I'm doing something wrong but have no clue what it could be. I stream my G-code to GRBL and check regularly the buffer fill level by sending a "?" and evaluating the result in order to avoid overflows. Then my code ensures the command queue never becomes full. But at some point I get back a

Bf:14,0

which means one command is in queue and the serial buffer is filled up completely. Amazingly at this point the serial buffer is not processed any more, no matter what I do I do not get rid of this state and have to restart my hardware.

So...any idea what could cause the serial buffer to lock when it is filled completely?

Regarding my environment: I neither use a standard Arduino nor a GUI, I'm streaming the data via a direct serial connection to the MCU using an own application.

Thanks!

**Comment by chamnit** [comment]
Closing due to being a duplicate on the older site.
