### ISSUE TITLE
Mega 2560 will not connect

### ISSUE THREAD

**Issue by mrtwizta** [gnea/grbl#632]
I get this error when trying to open with Gbrl Controller
No data from COM port after connect. Expecting Gbrl version string

I ran the Uno shield and had no issues with hardware, all motors working, loaded a file and executed no issues.

**Comment by mrtwizta** [comment]
Is there a Version of gbrl that has been tested on 2560 with out issues?

**Comment by akrpkv** [comment]
https://github.com/gnea/grbl-Mega

**Comment by mrtwizta** [comment]
tried the At mega 2560 and and MKS Gen2-Z (2560 chip)
"No data from COM port after connection.Expecting Grbl version string."
So I loaded A Marlin printer sketch i use for my 3Dprinter and it works fine, obviously till the heater hardware reports an error.
Just to confirm/prove the hardware and wiring is correct, i can move and home all axis without problems
so it seems the devs need to do some soul searching there?

**Comment by mrtwizta** [comment]
> https://github.com/gnea/grbl-Mega

There is no response from any of the 2560 builds? they all unresponsive or error prone
most report gbrl no finished loading or no data from com port
why dont they just take a Marlin by the tail and mod it work with gbrl?
has all the bells, even the display part for jogging works?

**Comment by matonym** [comment]
I'm running GRBL on the Mega 2560 without any problems.
Have you tried connecting with a terminal program to the COM-port (115200 baud) ?

**Comment by mrtwizta** [comment]
how do i do that? noob here

**Comment by matonym** [comment]
There's plenty of software. If you are on Windows you might try Putty (https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)

Example
![putty1](https://user-images.githubusercontent.com/25170057/55224088-021e3800-5210-11e9-8244-170859cf224d.png)

Settings. Make sure you have the right COM-port etc.

![putty2](https://user-images.githubusercontent.com/25170057/55224099-077b8280-5210-11e9-8a4b-793144525b0f.png)

Result (Hopefully)

**Comment by mrtwizta** [comment]
hi
thanks for the mail, it is appreciated.
i followed that eg. and the terminal just shows a green cursor with no text

Regards

Michae lk
michael k (under cover matter-control pimp)
+27 63 185 0233

3rdzeropoint@gmail.com <michaelkruis58@gmail.com>

**Comment by matonym** [comment]
Are you sure it's the right COM-port selected?
If not sure, double-check it in the device manager.

**Comment by MeJasonT** [comment]
From your earlier post it sounds like you mat not have actually installed GRBL.
in the Arduino IDE under Tools tab see if you mega is connected, under the same (Tools) tab check that the board you have selected is The Genuine mega.  Go back into Tools menu and select Serial Monitor - when it opens check the baud rate is set for 115200 in the bottom left corner of monitor screen, if not use the drop down to select it.  GRBL should have responded if not in the command bar at the top enter $$ and press the send key to the right.  If you get no response then the program on the board is not GRBL.  in that case close monitor window and go to File - Examples and open Basics - Analogue ReadSerial, load it to your board.  Open the monitor window again change the baud rate to 9600 and you should see a list of values being printed.  Your board is working and communicating if this works.
If you have installed the GRBL library on your machine go to File tab- open examples again and look for GRBL once open upload it to your mega.  open the serial monitor again, set baud rate to 115200 and see if the board responds if not try sending $$ again.  It is possible to blow up the micro or the FTDI IC but the steps above should give you some confidence that your board is working.

**Comment by mrtwizta** [comment]
yes its the right one, as i said i loaded a marlin sketch that works on the
same port, used matter control to move and check works fine with matter
control and marlin
i can connect to the port with the software but gives those errors no data
or not gbrl finished loading
Regards

Michae lk
michael k (under cover matter-control pimp)
+27 63 185 0233

3rdzeropoint@gmail.com <michaelkruis58@gmail.com>

**Comment by MeJasonT** [comment]
Have you installed the GRBL library correctly ?

**Comment by MeJasonT** [comment]
If you click on grbl outside of the library folder it opens and looks like it should, however when you go to upload firmware it will tell you lies as it cant find any of the associated files and will fail to upload.

**Comment by mrtwizta** [comment]
Regards

Michae lk
michael k (under cover matter-control pimp)
+27 63 185 0233

3rdzeropoint@gmail.com <michaelkruis58@gmail.com>

**Comment by MeJasonT** [comment]
?
have you fixed it, if so please close this issue.

**Comment by mrtwizta** [comment]
Be patient please i am still trying to go through your mail
Regards

Michae lk
michael k (under cover matter-control pimp)
+27 63 185 0233

3rdzeropoint@gmail.com <michaelkruis58@gmail.com>

**Comment by MeJasonT** [comment]
Sorry buddy you responded with just Regards, it sounded positive.

**Comment by mrtwizta** [comment]
NP
ok i did the AnalogRead and i see lots of 0, apearing

**Comment by MeJasonT** [comment]
your board is communicating so no hardware fault, It looks like you are not getting the GRBL firmware loaded properly.  What machine are you wanting to use with grbl 3 axis ?

**Comment by mrtwizta** [comment]
ok i did this and found the gbrlUpload under examples which is the one i have been using,
but i get nul output on serial mon
If you have installed the GRBL library on your machine go to File tab- open examples again and look for GRBL once open upload it to your mega. open the serial monitor again, set baud rate to 115200 and see if the board responds if not try sending $$ again. It is possible to blow up the micro or the FTDI IC but the steps above should give you some confidence that your board is working.

**Comment by MeJasonT** [comment]
Do you want me to talk you through the install

**Comment by mrtwizta** [comment]
yes please

**Comment by mrtwizta** [comment]
i wish they would allow team viewer in these situations

**Comment by mrtwizta** [comment]
yes please
i am in git as well i can reply there if you like?

Regards

Michae lk
michael k (under cover matter-control pimp)
+27 63 185 0233

3rdzeropoint@gmail.com <michaelkruis58@gmail.com>

**Comment by MeJasonT** [comment]
Ok, 
have you located the arduino library folder
do you have any versions of grbl in your arduino library folder if so delete them, lets start from scratch.
You have two options of uploading the file by using the arduino ide to upload the program or by uploading the hex file directly using Xloader - which are you happiest using.

**Comment by mrtwizta** [comment]
ok

**Comment by mrtwizta** [comment]
i have a hex and i di do that but let me delete from the lib

**Comment by MeJasonT** [comment]
i was going to suggest a link you beat me to it. send the link you used to download the master

**Comment by mrtwizta** [comment]
https://github.com/gnea

**Comment by MeJasonT** [comment]
OK tops

**Comment by MeJasonT** [comment]
So you have chosen to download the GRBL program via the download zip, correct.

**Comment by mrtwizta** [comment]
C:\Program Files (x86)\Arduino\libraries
is this the correct place for the library?

**Comment by mrtwizta** [comment]
yes

**Comment by MeJasonT** [comment]
Ummm what version of arduino IDE are you using. the latest versions save the library to another location - by default its in your document folder

**Comment by mrtwizta** [comment]
1.8.9

**Comment by mrtwizta** [comment]
you want to connect to my pc with team viewer?

**Comment by MeJasonT** [comment]
1% newer than mine, i'm still on 1.8.8
would prefer not to use team viewer if its all the same, we have dodgy companies here in uk trying to gain access to users machines, best to stay away from it.

**Comment by mrtwizta** [comment]
ok

**Comment by MeJasonT** [comment]
do you have a folder like C:\Users\Your Computer\Documents\Arduino\libraries

**Comment by mrtwizta** [comment]
yes

**Comment by MeJasonT** [comment]
Ok is the grbl folder the top level or does it contain a folder called grbl inside it

**Comment by mrtwizta** [comment]
its top, i see all the c and h files init

**Comment by MeJasonT** [comment]
you are a star, now open the ide and open grbl from the examples tab

**Comment by MeJasonT** [comment]
It will open just one page, but it now knows where to find the other code segments

**Comment by mrtwizta** [comment]
i only see grblUload there, but its done

**Comment by MeJasonT** [comment]
you should now be ready to go.  open the serial monitor window in the ide baud 115200 and send $$

**Comment by mrtwizta** [comment]
done but still no response

**Comment by MeJasonT** [comment]
NO!, did you get any errors when you uploaded to the board

**Comment by mrtwizta** [comment]
no

**Comment by MeJasonT** [comment]
im going to the workshop for an mega board, give me 10 mins

**Comment by mrtwizta** [comment]
i need a brew....

**Comment by mrtwizta** [comment]
ok
mine is not a Genuine arduino a clone but atm i have the other MKS Gen2 wich is a mega based board? must i try again with the Mega clone?

**Comment by MeJasonT** [comment]
I have a clone as well

**Comment by mrtwizta** [comment]
i have no issues with them, i run my printers on them

**Comment by MeJasonT** [comment]
Do you have folders inside your grbl folder saying  build, docs, grbl 
The marlin has been written to display the full folder hierarchy grbl has a .h file which fetches all the sub files into the application

**Comment by mrtwizta** [comment]
no, but i know what you talking about, i have seen that in other versions

**Comment by MeJasonT** [comment]
I have just loaded my ide/grbl and it was missing after just telling you.

**Comment by mrtwizta** [comment]
there are 4 files there 1 COPYING, 2 Makefile, 3 .gitignore 4 README

**Comment by mrtwizta** [comment]
so the file in git is incomplete?

**Comment by MeJasonT** [comment]
ok.  The zip will have contained the full project in the folder there is a folder called grbl inside it has all the .c and .h files. this is the only folder which should be in side your library not the rest of the guff

**Comment by MeJasonT** [comment]
if you have more than one folder with the same name inside the library the ide tries to open two versions of the sketches and achieves nothing.  best to completely remove grbl from both the c arduino library folder and the documents library folder and start from scratch.  I have just uploaded the same mega version we are both using and it is working like a treat

**Comment by mrtwizta** [comment]
ok busy doing it

**Comment by MeJasonT** [comment]
you should end up with this

![Untitled](https://user-images.githubusercontent.com/21656956/55244011-3c9bcb00-5238-11e9-8475-95447bb3d2cc.png)

I will wait to see how you get on

Or try it another way download xloader http://xloader.russemotto.com/
and hex from here https://github.com/gnea/grbl-Mega/releases

**Comment by mrtwizta** [comment]
i deleted and re unzipped the downloaded file and looks the same as yours, uploading now

**Comment by mrtwizta** [comment]
should those C and H file be in the gbrlUpload folder under examples?

**Comment by MeJasonT** [comment]
the folder should appear in examples as "grbl" in the folder there will only be one entry showing the grblUpload

**Comment by mrtwizta** [comment]
i see that ... i did the Xloader hex thing and was successful will check the monitor now

**Comment by mrtwizta** [comment]
yes that's what i see too

**Comment by mrtwizta** [comment]
TaDA ............... yaay!

**Comment by MeJasonT** [comment]
Don't keep me in suspense

**Comment by mrtwizta** [comment]
full string in monitor

**Comment by MeJasonT** [comment]
Message crossed, what program are you going to use

**Comment by mrtwizta** [comment]
thats what i am unsure of? any sugestions i have downloaded lots? was trying ugsplatform64

**Comment by MeJasonT** [comment]
i would hold you to it- if you were in UK, where you at.

**Comment by mrtwizta** [comment]
In South Africa... 
you have a link
well the jog controls are now available so if i connect all up to the mach it should move hopefully
just a sec while i do that
a million thanks....

**Comment by mrtwizta** [comment]
https://github.com/gerritv/Grbl-Panel/releases

**Comment by MeJasonT** [comment]
[https://github.com/gerritv/Grbl-Panel/releases](url) yep
another useful prog
[https://camotics.org/download.html](url)

Ive worked in cape town, durban & luderitz

**Comment by mrtwizta** [comment]
Nice diamonds? :)

**Comment by mrtwizta** [comment]
the place is a mess atm i need to get out

**Comment by MeJasonT** [comment]
I have to admit to vacuuming the sea bed. 
yeah its a shame i loved it.

**Comment by mrtwizta** [comment]
ok the MKS board is un responsive, goung to put the mega clone that took the sketch back on
My uncle was a PVt diver for debeers many years ago had his own dive barge, Bill Monk...

**Comment by MeJasonT** [comment]
we had an ROV with a huge nu-nu on the front

**Comment by mrtwizta** [comment]
sent mail

**Comment by mrtwizta** [comment]
> we had an ROV with a huge nu-nu on the front
nice.. big suckers them things

**Comment by mrtwizta** [comment]
This is Billy from Cape Town

https://www.google.com/search?q=billy+monk&rlz=1C1MSIM_enZA839ZA839&oq=billy+monk&aqs=chrome..69i57j0l5.7103j1j7&sourceid=chrome&ie=UTF-8

**Comment by mrtwizta** [comment]
thank you for your help
much appreciated

**Comment by mrtwizta** [comment]
> your board is communicating so no hardware fault, It looks like you are not getting the GRBL firmware loaded properly. What machine are you wanting to use with grbl 3 axis ?

I have buit a Desktop CNC and the plan is to add a 3rd axis on the y Table to use as a simple rotary axis.
