### ISSUE TITLE
Both MPos and WPos reported when $10=3

### ISSUE THREAD

**Issue by Harvie** [gnea/grbl#635]
Hello,
i have report from user https://github.com/vlachoudis/bCNC/issues/1205
who claims that when he sets `$10=3` in GRBL v1.1f he gets status reports containing both WPos and MPos... Is that even possible?

```
<Idle,MPos:0.0000,0.0000,0.0000,WPos:-4.0000,1.0000,3.0000>
<Idle,MPos:0.0000,0.0000,0.0000,WPos:-4.0000,1.0000,3.0000>
<Idle,MPos:0.0000,0.0000,0.0000,WPos:-4.0000,1.0000,3.0000>
```

**Comment by chamnit** [comment]
Not possible. The user is not using v1.1. The status report is not separated by ‘|’ delimiters, which was instituted when v1.1 was released.
