### ISSUE TITLE
WIKI note error

### ISSUE THREAD

**Issue by 109JB** [gnea/grbl#64]
This is just a minuscule issue.  On the main WIKI page it states that there two deviations from written g-code standard with one noted as follows.:

G0 and G1 are accepted with no axis words to set the motion mode and feed rate. Common on industrial machines. 

This is not technically correct. G0 and G1 in Grbl respond exactly as they do in LinuxCNC. In linuxCNC all axis words are optional in both G0 and G1. G0 can always be used by itself, and G1 only needs a defined feed rate. If a feed rate has already been defined in a previous line then G1 can be on a line by itself. In this sense I see no difference in the operation of G0 or G1 in Grbl versus LinuxCNC, or many other controls.

Am I missing something?

**Comment by chamnit** [comment]
@109JB : Yep. You're right. Even checking their older documentation, it shows that no axis words is allow for both G0 and G1. Looked at my NIST g-code document, it says right there that it's an error if there are no axis words. Either LinuxCNC altered their older docs (not likely), or I forgot that G0 and G1 allowed axis words in LinuxCNC and read the NIST doc more recently (more likely). I'll update parts of the wiki that talks about that stuff.
