### ISSUE TITLE
G92 does not work?

### ISSUE THREAD

**Issue by mikemaikaefer** [gnea/grbl#646]
Hi,

following situation with a GRBL in default mode (all done directly via terminal and with default parameters):

I send a "?" which returns some coordinates

I send a "G92X10Y20" which returns with "ok".

I send an other "?" and would have expected the coordinate values for X and y which are returned now are at 10 and at 20 - but I still get the same values like from previous call to "?".

What am I doing wrong? Are there any preconditions to be met in order to set the current position to a new value?

Thanks!

**Comment by chamnit** [comment]
Grbl v1.1 reports machine position by default. Not work position. Look for the WCO offset update in the status report instead. Or just change the default reports to output work position.
