### ISSUE TITLE
Invert individual limit switch

### ISSUE THREAD

**Issue by schwittlick** [gnea/grbl#655]
I'm using two normally closed limit switches for X and Y direction. And a normally open limit switch for Z direction. Is there a way to invert the pins individually? The $5 command inverts all switches, but I only want to invert Z..

Thanks for any leads!!

**Comment by 109JB** [comment]
Yes. In config.h look for the #define INVERT_LIMIT_PIN_MASK line and uncomment and set as appropriate

**Comment by schwittlick** [comment]
Ah!! I should have inspected that file completely before. Amazing, thanks!
