### ISSUE TITLE
additional spindle control 

### ISSUE THREAD

**Issue by JamieAKing** [gnea/grbl#657]
my vfd has analog input for spindle speed which works fine but the enable function requires a 15v pin to be pulled to ground. I can do this through a relay but will need a spindle enable pin at 5v on the Arduino to trigger the relay. 
I can see in spindle.c something that looks very much like a solution but not sure of the changes needed. is anyone willing to point at exactly which lines of code and the changes required to use spindle direction(d13) as a seperate spindle enable while keeping the Pwm speed control on pin 11

**Comment by Harvie** [comment]
Now there seems to be quite elegant solution integrating Huanyang RS485 communication directly to GRBL, i would be happy if you can help with testing:
https://github.com/terjeio/grblHAL/issues/68
