### ISSUE TITLE
Homing and laser control don't work on bachin  maker 2 axis board

### ISSUE THREAD

**Issue by kryts** [gnea/grbl#659]
I have a Bachin maker engraving board. it is running grbl 1.1z
with this version of grbl the jog commands do not work. it will accept the commands but nothing happens.
so i compiled and uploaded the latest version of grbl. This allows the jog commands to work. however now the laser control and auto home don't work.

**Comment by 109JB** [comment]
Since the current official version of grbl is 1.1g, the 1.1z version must be a custom version. Perhaps by the maker if your machine. Sounds like the complaint should be placed there.

**Comment by kryts** [comment]
I did send them a email. I put it here more as if some one else has this board and knows of a fix. example maybe there is a change you need to make in config.h to make it work or one of the other files, then they could chime in. I totally agree with you that it is a custom version.

**Comment by kryts** [comment]
![image](https://user-images.githubusercontent.com/13613821/57415696-20d20000-71ba-11e9-8cf7-5e76ba40505e.png)

**Comment by kryts** [comment]
well I received a reply from the board manufacture and they are going to see if they can make a version for me that will work. I will let you know how it goes.

**Comment by kryts** [comment]
They asked for pictures of the board to verify what one it was. The response I got back was that it is using the standard grbl pins. so i'm not sure where to go from here.

**Comment by kryts** [comment]
ok got it compiled again and re-uploaded. it was an error on my side. i was editing the wrong config.h file
