### ISSUE TITLE
 i need your suggestions

### ISSUE THREAD

**Issue by samehherit** [gnea/grbl#676]
Hi every body 

 i need your suggestions about an electronic or mechanical tool which i can install it on the (x ) axis to scans the 3d models as an input data to transfer it to artcam or any apps which i can engrave this model later
It just a dream and i hope to become true

**Comment by MeJasonT** [comment]
https://www.david-3d.com/en/support/downloads
use meshcam or blender to create your dxf for production of job file.
Its based on a camera image scan, if the camera was mounted so it moved across the object like a paper scanner this would produce a 3d image of the object beneath all be it not the side sitting on the machine bed.   There is a demo version that works with a webcam.

**Comment by samehherit** [comment]
That is so good 
Thanx a lot for your helping 😊
