### ISSUE TITLE
Universal Gcode Sender Machine status

### ISSUE THREAD

**Issue by Marco70cn** [gnea/grbl#68]
Why using the last version 1.1e, Universal Gcode Sender Machine status not working?
Is it my setting wrong?
![20161216140105](https://cloud.githubusercontent.com/assets/24539514/21253312/8e28a4b0-c398-11e6-8656-60783674f6c4.jpg)

**Comment by winder** [comment]
@Marco70cn you turned off the status reports, re-enable them with `$10=1`

**Comment by Marco70cn** [comment]
Thanks for your help, but also with $10=1 still the status not working.
