### ISSUE TITLE
Z-Axis inverted

### ISSUE THREAD

**Issue by replaysMike** [gnea/grbl#680]
Hey all.

I have a CronosMaker board (china 3018 pro) running the latest `grbl_v1.1f.20170801` and for some reason the z-axis only is inverted. I'm not sure if this is a wiring issue or a control issue, but I've seen others report it as well just can't find a solution.

Worth building from source and fixing or is there another simpler solution?

**Comment by JBSchueler** [comment]
Can simple inverted by configuration of GRBL [$3 – Direction port invert, mask](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#3--direction-port-invert-mask)

`$3=4` would do the job.

**Comment by replaysMike** [comment]
Brilliant - that worked perfectly!
