### ISSUE TITLE
GRBL 1.1 decativation "Default Lock" on Startup with autohoming

### ISSUE THREAD

**Issue by raindancer2204** [gnea/grbl#683]
Hi,

I have the version GRBL 1.1 on my Woodpeaker Board.

I have now attached to my CNC 3018 switch for the postion.

These were also activated and functioning via the autohoming software.

Now to my problem:
I read that by default after starting the CNC the machine must be unlocked before working.

But I have a remote controller on my Woodpeaker Board 3.3.

Unfortunately, I can not unlock the remote controller, which I can do with the normal PC software.

Is there a way to use autohoming and disable the default lock?

Thank you
raini

**Comment by chamnit** [comment]
Grbl is auto-locked upon power up by default when homing is enabled. You can disable it in config.h with commenting HOMING_INIT_LOCK or just run a homing cycle. I don't recommend disabling it.
