### ISSUE TITLE
Spindle speed factor

### ISSUE THREAD

**Issue by graphtjb** [gnea/grbl#686]
I am having a problem with the spindle speed. If i seem to set the spindle speed the out on the machine is roughly ten time higher. I am not using the original manufactures board or spindle. I would like to use what i have but change the code. I have down loaded your original could and would like to scale the pwm signal control the board so as to more closely match the desired rpm for other programs like eagle cad or flat cam. Do you need more information? What would you suggest and how would you like me to proceed?

I have looked at the wiki.
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#30---max-spindle-speed-rpm

**Comment by dxgldotorg** [comment]
Set your max RPM to whatever the spindle spins at when at full power.  This will give an approximation of speed scaling.

S commands are simply telling the control what percentage duty cycle for the PWM, and variable $30 tells the control what S number corresponds to 100% on.
