### ISSUE TITLE
sys.state: bit map or enumeration?

### ISSUE THREAD

**Issue by bdurbrow** [gnea/grbl#689]
In most places in the codebase, sys.state seems to be treated as an informal enumeration. However, occasionally something like this pops up:

if ((sys.state & (STATE_CYCLE | STATE_HOMING | STATE_JOG)) ||

... where individual bits are being tested. Also, the values are defined as bit() values in system.h.

What's the cannonical approach to sys.state supposed to be? Can I assume that only one bit can ever be set in sys.state? Or should I assume that any possible combination of bits could occur?

**Comment by terjeio** [comment]
Only one bit or none, states cannot be combined.

**Comment by bdurbrow** [comment]
Thanks... then I was doing it right.
