### ISSUE TITLE
Is arduino v3 cnc shield compatible with  Arduino UNO R3 D1 R32 wifi development board

### ISSUE THREAD

**Issue by manojprasanga** [gnea/grbl#693]
Can i use ESP32  Arduino UNO R3 D1 R32 wifi development board to cnc shield as Arduino v3 CNC shield

![cnc-shield01](https://user-images.githubusercontent.com/52038093/61935725-bc4c6300-afa8-11e9-9112-91e7b2c431c9.jpg)
![FS06XU2JIAJN9X8 LARGE](https://user-images.githubusercontent.com/52038093/61935726-bce4f980-afa8-11e9-9373-a762a22ba8d7.jpg)

**Comment by m0n5t3r** [comment]
probably yes (with the esp32 grbl port and a bit of fumbling), but it's a waste of I/O; better get one of the breakouts with all esp32 pins exposed and either design your own board, get the design files and build it yourself, or order the thing readily assembled from https://www.tindie.com/products/33366583/grbl_esp32-cnc-development-board-v35/ (so far there are no decently priced Chinese clones available, they're all in the "esp32 with camera" bandwagon at the moment)
