### ISSUE TITLE
Error trasfering data

### ISSUE THREAD

**Issue by Brayan120V** [gnea/grbl#694]
Sorry for my bad English.

I was making a 3d model and from one moment to another the X axis ended up in unwanted places damaging the model (I really don't know what happened because it left the machine running and I was going to do other things) this happened with version 0.9 of grbl, now I changed to version 1.1 that when compiling in the Arduino IDE an alert appeared with little available space in the memory and added to this I tried to make the model but the machine stopped without any reason and did not complete 5% of the model. Is there a debbuger to see where the error is ?, will it be an arduino card problem (UNO) ?, problems with the compatibility of the cnc shield card (v3.0) ?. All controlled with an intel core i3 PC, 8GB RAM, SSD disk and Lubuntu distribution, Universal G-code Sender Platform 2.0 nightly.

![Captura de pantalla de 2019-07-26 12-45-07](https://user-images.githubusercontent.com/43918768/61970893-5c06f280-afa3-11e9-9230-7cfeea1eb264.png)

**Comment by chamnit** [comment]
This is a hardware problem. Likely lost steps. Not a firmware issue.
