### ISSUE TITLE
Over ride over applies

### ISSUE THREAD

**Issue by jahnj0584** [gnea/grbl#7]
original post: https://github.com/winder/Universal-G-Code-Sender/issues/503

Lets say your max speed is 600, and the program is at 500. If I apply +20%, it'll max out. I can still click through, adding up to +100% (1000 total) but the machine will still move 600. The issue is, when you go to lower the value there is no real world speed effect until you are again at 20% or lower (so 8-80 clicks of no effect and potential damage). Not sure how you can limit this, but it's something that should be done. Cheers

**Comment by chamnit** [comment]
I've already answered this question. There is no problem and overrides should not be limited.  It applies to all feed rates, including ones that come later that may be much lower. They need to be correctly applied too.
