### ISSUE TITLE
Maybe a typo

### ISSUE THREAD

**Issue by DiSlord** [gnea/grbl#70]
In file
gcode.c line 394

if ((gc_block.modal.motion != MOTION_MODE_NONE) || (gc_block.modal.motion != MOTION_MODE_SEEK)) 

Result always true

**Comment by chamnit** [comment]
@DiSlord : Ok thanks. Fortunately not many people use inverse time mode.

**Comment by chamnit** [comment]
This will be in the next push. So I'm closing this issue.

**Comment by dunaevai135** [comment]
still not corrected 
gcode.c line 423

**Comment by chamnit** [comment]
@dunaevai135 : Are you absolutely sure about that? What version of Grbl are you using?

**Comment by dunaevai135** [comment]
@chamnit I apologize. I used the wrong version
