### ISSUE TITLE
Spindle spin problem. My grbl it`s crazy

### ISSUE THREAD

**Issue by arrancameeloro2** [gnea/grbl#703]
I have been testing the grbl without spindle, it moves well and I have already configured it, so far I have not had problems.
I have 2 power supplies on, but the spindle potentiometer is at a minimum, when the machine is moving and I turn the revolutions with the potentiometer, many faults appear in GCodeSender.
And the parameters are unconfigured.

He estado probrando el grbl sin spindle, se mueve bien y ya lo he configurado, hasta aquí no he tenido problemas.
Tengo 2 fuentes de alimentación encendidas, pero el potenciometro del spindle esta en el mínimo, cuando la maquina se está moviendo y subo las revoluciones con el potenciometro, aparecen muchos fallos en GCodeSender.
Y se desconfiguran los parámetros.

**Comment by chamnit** [comment]
This is not a firmware issue, but an electrical issue with your setup. Closing.
