### ISSUE TITLE
Stop UART transmission in Linux conflict whith modem-manager package

### ISSUE THREAD

**Issue by bogdano830** [gnea/grbl#704]
I use grbl1.1f with atmel 328 P (arduino nano) based board from aliexpress with ubuntu 18.04 lts.
When i send gcode to ty board UART transition stop in random time. Fixed for me with  removing modem-manager package.

**Comment by bdurbrow** [comment]
Umm... I think that's not a grbl problem but rather it's a Linux problem?

It's not surprising though... anything that scans serial ports, could, in principal, cause a conflict.

If you aren't on dial-up internet; removing a modem manager shouldn't be a problem?
