### ISSUE TITLE
Error when activating the new double motor function on Y axis in version 1.1.h

### ISSUE THREAD

**Issue by cguerrero1205** [gnea/grbl#712]
Hello, I want to report an error that is generated when I try to activate the double motors on the Y axis, when compiling in Arduino, it shows me the following error:

D:\Documents\Arduino\libraries\grbl\report.c: In function 'report_realtime_status':

D:\Documents\Arduino\libraries\grbl\report.c:654:1: error: expected declaration or statement at end of input

 }

This is because in the report.c library, the closing bracket "}" is missing on line 581: 

`if (bit_istrue(lim_pin_state,bit(X_AXIS))) { serial_write('X') ;`

Adding it solves the problem.

Thanks for all your work.

**Comment by chamnit** [comment]
@cguerrero1205 : Thanks for the bug report! Fixed.
