### ISSUE TITLE
Would it be possible for GRBL to support the "R" in G10 L2 P1 R<angle>?

### ISSUE THREAD

**Issue by BernardG** [gnea/grbl#723]
As the subject says, I wonder if it would be possible to implement this angle correction to the WCS? Maybe in the future 32 bits version, if not now?

**Comment by chamnit** [comment]
No Grbl does not currently support The R word in G10. I’ll make a note to support it in the future. It’s relatively easy to add but will require a faster processor to do the math constantly, which is one reason it’s not supported on the AVR.

**Comment by BernardG** [comment]
Thanks, Sonny. I thought that was the reason for not supporting it now, so it makes another good reason to be impatiently waiting for the future 32 bits release..... ;-)
