### ISSUE TITLE
mm vs Inch

### ISSUE THREAD

**Issue by patgadget** [gnea/grbl#74]
Hi, thanks for GRBL,
i have a setup that use 0.2 inch timing belt and 200 step Motor.
my question is : does GRBL step/mm parameter could be set in Step/Inch?
i get a perfect value in inch and an awkward one in mm.
is there a parameter switch or is GRBL always in mm?
Thanks for all the developement in GRBL.

Pat Gadget

**Comment by chamnit** [comment]
@patgadget : Settings are always in mm. I don't plan on altering the unit type in them. It would just cause more confusion. Besides, you typically have to slightly adjust the step/mm based on actual travel, rather than computed. Belt tension can alter step/mm very slightly.
