### ISSUE TITLE
What could produce such inconsistent feed rate ?

### ISSUE THREAD

**Issue by AndKe** [gnea/grbl#742]
video: https://drive.google.com/open?id=146zUXQiXzWz17eFsPrZEz-iBbYyVMPiL
gcode: https://drive.google.com/open?id=1V9ICB_uboEyxod5E013hcrVUTK-k5zoZ

GRBL1.1h

**Comment by AndKe** [comment]
does that give good milling /engraving results ?
I am most familiar with 3D printing, and Marlin does everything like look ahead and more to maintain a smooth movement.
Maybe that is not important for CNC ?

**Comment by chamnit** [comment]
Your acceleration settings are likely very low. Grbl is slowing things down along the path to not exceed those settings.

**Comment by AndKe** [comment]
G64 P0 was the reason.
