### ISSUE TITLE
GIT site related

### ISSUE THREAD

**Issue by MeJasonT** [gnea/grbl#744]
Why cant i upload images using google chrome to this forum
keep getting
"something went really wrong, and we cant process that file"
which annoys me on three counts.

I cant post images to help people
It was only a 40k jpeg 
and whats worse they put a comma before the and in the error message

any clue as to why GIT is being a git.

**Comment by winder** [comment]
Unfortunately the only thing you can do is try a different browser and ignore offensive grammar.

**Comment by MeJasonT** [comment]
Cheers Winder
one is easier than the other the browser i can cope with.

**Comment by MeJasonT** [comment]
I used DuckDuckGo it obviously works
thanks again winder

![MV5BZTBlZTNjYWUtOTA1ZC00NmZiLWI1NmQtODM4NTkyOWM5NDhiXkEyXkFqcGdeQXVyNzYyMzEyNjk@ _V1_](https://user-images.githubusercontent.com/21656956/67415740-77db5e00-f5bd-11e9-8e2b-c45936fdf7ed.jpg)
