### ISSUE TITLE
Mechanical End Stops configuration question.

### ISSUE THREAD

**Issue by maxoutny** [gnea/grbl#75]
Is it possible to implement the following: 
Mechanical end stop switches installed on all 3 axis in order
Z+     Z Maximum
X-      X Minimum
Y-      Y Minimum
Wires connected to NO pare. I am using CNC Shield V.3,0 with Arduino UNO.
If it possible to use such connection, can you advise which configuration changes I have to make to enable
homing in such order Z Max, X-Y Min.

**Comment by chamnit** [comment]
@maxoutny : Your question may be answered in the configuration wiki page. See the homing direction mask to configure your homing cycle to search in the negative direction.
