### ISSUE TITLE
Steppers do not move after upgrade to grbl 1.1

### ISSUE THREAD

**Issue by iivoilov** [gnea/grbl#758]
My CNC machine came about 1 year ago but I started to use it now, It came with grbl 0.8 and was working. When I started to use it I run into the problem that after running to the first position everything is shifted the same way, i.e. it looks that the 1st move is done always shorter than it should be but further moves are correct. When I issue commands manually in terminal this problem does not appear, all moves are correct. I tried to reduce max rate and max acceleration but it did not help.

So I suspected that such problem is solved in the latest version of grbl. I installed it on a new Arduino Nano and replaced the it in CNC machine. Got a proper prompt "< Grbl 1.1h ['$' for help]", put the same $$ settings like on the old grbl 0.8, but unfortunately only spindle is working. Steppers do not move.  I played with $0 value - no luck.

Please advise which settings may affect steppers

I added image of the control board of my CNC machine
![IMG_20191109_154505__01](https://user-images.githubusercontent.com/15819507/68529570-bcc6fa80-0308-11ea-90de-671d3d172948.jpg)

**Comment by iivoilov** [comment]
Arduino Nano on my board has CH340G chip which has the known issue. Does this issue appears in such way?

**Comment by iivoilov** [comment]
Found the problem. The board has different wiring than default CPU_MAP_ATMEGA328P.
So I changed XYZ step and direction pins, recompiled and uploaded the new version of grbl.
Checked the problem with short move on the first motion - gone.

**Comment by shreekant-sureliya** [comment]
i also tried this and it worked thanks for info.
