### ISSUE TITLE
Just a curiosity about GRBL and ESP32S

### ISSUE THREAD

**Issue by Marco70cn** [gnea/grbl#77]
Is there a chance to use GRBL on ESP32S?
If not compatible (as i suppose), will be difficult try to adapt?
I think use an ESP32S instead of Arduino should be 1000% better :-)

**Comment by chamnit** [comment]
@Marco70cn : I haven't looked into ESP32's that much, so I can't say what the hardware limitations are. But, as far as I know, the compilers and toolchains are still not ready for general use, while Atmel and other major MCU manufacturers' toolchains have been around for a significantly longer time.

**Comment by mkeyno** [comment]
@chamnit  how about now ? ESP32 is on the edge and FreeRTOS work very well now , it could easily assign  core for specific task,  it would be good idea to dedicate one core for GRBL core and another for user interface with nice webhost , even laserweb4 easily could uploaded on it
