### ISSUE TITLE
S curve motion add in GRBL

### ISSUE THREAD

**Issue by quangvi** [gnea/grbl#79]
Dear @chamnit , Do you think about s-curve velocity vs trapezoidal velocity ? in future post in GRBL,thank

**Comment by chamnit** [comment]
Yes. Higher order motion control is planned, and has been for a very long time now.

**Comment by quangvi** [comment]
thank @chamnit , I thought you to be angry about my stupid question day before

**Comment by Harvie** [comment]
Do you think this would be possible for 8bit atmega version?
