### ISSUE TITLE
NC probe sensor: $6=0 & G38.4 or $6=1 & G38.2 ?

### ISSUE THREAD

**Issue by auhopu** [gnea/grbl#791]
I've been using a NO probe sensor for Z zeroing with $6=0 and G38.2 for several years. 

After researching bCNC's tool changing capabilities, I will be getting a NC sensor to use both for Z probing and tool length setting.

In order to test it, I faked my NO as NC by holding the crocodile on the sensor top and confirmed working in both combinations of the subject. i.e.:

- $6=0 (normally high, low when triggered) and G38.4 (stop on loss of contact, else error)
- $6=1 (normally low, high when triggered) and G38.2 (stop on contact, else error)

Is there a benefit in choosing one over the other?

**Comment by doppelhub** [comment]
Just depends on what you're trying to accomplish.  In a noisy system, having a low impedance path to ground/VCC during the normal run state is better.  If both states are low impedance it doesn't make any difference.
