### ISSUE TITLE
Can automatic reporting be turned off?

### ISSUE THREAD

**Issue by arminlinder** [gnea/grbl#795]
I'd like a status report when and only when I send a "?". No messages, no alarms, no nothing. Can this be achieved through configuration? Thnx, Armin.

**Comment by zeevy** [comment]
There is no automated report, 
grbl sends status only after receiving "?"

**Comment by arminlinder** [comment]
"No messages, no alarms, no nothing. "

:-)

**Comment by arminlinder** [comment]
And btw, why doesn't "?" work through a homing cycle?

**Comment by zeevy** [comment]
"?" does not work during homing, because grbl don't know the position of the machine for sure.

**Comment by arminlinder** [comment]
I see. 

Thanks for the clarification!

Armin.

**Comment by langwadt** [comment]
I think "?" during homing has been discussed before, afair it was a simple oversight that it isn't there, but it was left as is in case someone expected it

**Comment by arminlinder** [comment]
If so, I strongly encourage that the problem is fixed. I'd rather see false coordinates on my computer screen while homing than nothing at all, so in case something mechanical goes very, very wrong I can see that GRBL has tried. After all, if false corrdinates bother me, I can always ignore the corrdinates during homing, but use their (relative) change to display a kind of progress indicator.
