### ISSUE TITLE
ALARM2 and MAX TRAVEL 

### ISSUE THREAD

**Issue by sadezohdi** [gnea/grbl#801]
Hi...
 I set  $20 =1(soft limit enabled)  and  $22 =1(homing enabled)  and  $130=100(max travel axis x is 100) .
If I send for example the "G01 X-50 F500" command it will run correctly. But if I send the "G01 X+50 F500" command, the GRLB will send the message "ALARM2" !! 
I have not exceeded the maximum travel ! What is the problem???

**Comment by langwadt** [comment]
by default all of the machine is in negative space. 0,0 is in the upper right corner and all coordinates are negative. so with a max travel = 100 your x can be between -100 and 0

**Comment by sadezohdi** [comment]
thanks @langwadt
