### ISSUE TITLE
Discussing GRBL issues ... is there a user forum?

### ISSUE THREAD

**Issue by arminlinder** [gnea/grbl#808]
Is there? I feel unsure whether it is appropriate to post all problems I run into here. IMHO only (suspected) bugs should be posted on Git, so the developers aren't permanently busy wading through beginner's issues like mine. 

Is there any other recommended forum where the knowledgeable people meet, and where beginners can ask for advice?

Thnx, Armin.

**Comment by PicEngraver** [comment]
Try groups on Facebook.

**Comment by abdset** [comment]
You can go here :
https://github.com/gnea/grbl/issues

**Comment by arminlinder** [comment]
Thanks, I'll be happy to do so.
