### ISSUE TITLE
Sometimes missing <Carriage return> in grbl responses

### ISSUE THREAD

**Issue by JaanisK** [gnea/grbl#81]
Is it OK that sometimes missing 'CR' in grbl responses?
I'm trying to write sender program, but now I have problems with OK response counting,
sometimes it is at the end of status line when status line has no 'CR' at end,
or sometimes there is OKOK response. Using original Arduino Duemilanove.
Should I wait for 'CR' or 'CR LF'?
Tested with simple serial watcher program, same problem.
What software are you using to send to grbl?
Thanks :)

**Comment by chamnit** [comment]
@JaanisK : No it's not ok to be missing grbl responses. Make sure you don't have a Chinese Arduino clone with a CH380 USB-serial chip. These are known to have communication problems. Also, try using the stream.py Python program in the /doc folder of the repo. This shows the basic streaming protocol to send a program to Grbl. If it doesn't work, then its something with your Arduino or your host PC. 

Finally, Grbl v1.1 barely fits on an Arduino Duemilanove. Certain compile-time options in the config.h file can exceed the flash limit if they are enabled.
