### ISSUE TITLE
ST, EN and DIR Sink instead of Source

### ISSUE THREAD

**Issue by brosoft-dev** [gnea/grbl#855]
I'm trying to integrate with the Geckodrive GR214V, but it appears to want a sink input.

[Page 5, https://www.geckodrive.com/amfile/file/download/file_id/32/product_id/49/]
![image](https://user-images.githubusercontent.com/10651270/80230227-fad89080-8694-11ea-886d-d0f3c5cc340f.png)

Is it possible to include a build flag that changes the DIO mode of the step, enable and direction pins to assume an external pullup exists, and in turn sink current when output = HIGH?

**Comment by langwadt** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#2--step-port-invert-mask
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#3--direction-port-invert-mask
