### ISSUE TITLE
cancel jog not responding

### ISSUE THREAD

**Issue by bflorac** [gnea/grbl#864]
I'm trying to implement the cancel jog real-time command and it does not respond to it. In fact, it can mess up the next command with an error 1.  Everything else seems to be working fine. Other 8 bit commands like coolant (0xa0) work fine.  I can cancel the jog with a pause (!) but 0x85 fails. Running grbl 1.1h with compiled Z option (Homing force origin enabled).

**Comment by terjeio** [comment]
It should work, albeit somewhat intermittently so cannot be relied upon. See issue #95 (and [others](https://github.com/gnea/grbl/issues?q=is%3Aissue+jog+cancel)).

**Comment by bflorac** [comment]
Fixed problem. My bug. wide char vs char issue..
