### ISSUE TITLE
just got latest version 1.1h, but my arduino say 0.9j !!

### ISSUE THREAD

**Issue by OZ2CPU-thomas** [gnea/grbl#867]
so it is not the lates ??

**Comment by neilferreri** [comment]
You have to flash the new firmware to the Arduino. How did you do that?

**Comment by OZ2CPU-thomas** [comment]
downloaded the new zip, went into its folder for programming, its was an ino file, so it opened my arduino, then then I hit program, it compile, ok, uploads, and I go to serial monitor,
and it is version 0.9j i got..

**Comment by neilferreri** [comment]
You need to replace the grbl folder in your libraries folder with the new one that you extract from the zip.

**Comment by OZ2CPU-thomas** [comment]
oh, i did not do that.. bummer..

**Comment by neilferreri** [comment]
Don't forget, your $$ settings will be overwritten.  Make a backup.

**Comment by OZ2CPU-thomas** [comment]
i did make a back up, of my $$ setting, 
in fact I took a brand new arduino, just to be sure
so I can run them in parallel. thanks mate, lets call this one closed, i was a but jerk :-)
