### ISSUE TITLE
How to keep stepping motor always on all the time?

### ISSUE THREAD

**Issue by kaka-cnc** [gnea/grbl#875]
I use grbl serial port to control a 2-axis system. When I enter gcode, the motor starts to move, but after the movement, it will fall back due to gravity.  So I want to keep the motor on all the time so as to ensure that the system can fulfill my requirements.  But how to modify, can anyone help?

**Comment by peter76** [comment]
Hi, set grbl $1 value to 255, see here:

https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration

Good luck

**Comment by kaka-cnc** [comment]
Thank you, it worked very well.
