### ISSUE TITLE
New User and Arduino serial monitor - how?

### ISSUE THREAD

**Issue by cvhorie** [gnea/grbl#879]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface
"You just need to connect your Arduino to your computer with a USB cable. Use any standard serial terminal program to connect to Grbl, such as: the Arduino IDE serial monitor"
So I did that, and it didn't.
I had to run a sketch (BareMinimum) on the Arduino to enable me to open the serial monitor. 
I put into the Send box, $<enter>, then $$<enter> - nothing happened.

Connection is fine using the UGS (GUI ), so obviously I am missing a vital step.  My aim is to write a Python program to control the machine using the GRBL, Arduino and gShield.

"Just" is a bit of an exaggeration.
I am running a Arduino Uno with a gShield and GRBL 1.1.  The baud rate and COM seem to match OK.

**Comment by bdurbrow** [comment]
Something is not right with your setup. I'm having no problems with serial I/O.

**Comment by cvhorie** [comment]
Thank you
