### ISSUE TITLE
Cannot flash grbl on uno

### ISSUE THREAD

**Issue by mp3llll** [gnea/grbl#881]
Hey, I broke my USB of Arduino nano, I buy a new one, I try to install the Fw on the new Arduino nano, I use this 
https://github.com/gnea/grbl with Arduino software, all pass fine, after I try to check it with the serial monitor I got only a few  
"??" and enter $$ not give any info.

Does anyone have idea what I miss here?

**Comment by dungjk** [comment]
Make sure you choose correct COM port and Baud Rate. By default, Baud Rate is 115200.

**Comment by mp3llll** [comment]
Hey,
yes im with Com3 and 115200 , all pass fine, no error but still not few add :(
