### ISSUE TITLE
work position of y axis starts at 10mm when connected

### ISSUE THREAD

**Issue by Kruze17** [gnea/grbl#886]
Greetings and thank you for taking time to read this problem i am encountering.
Whenever i connect my grbl loaded(1.1) arduino nano to UGS it connects but the work position is always at positive 10mm.
I tried to find what is making this happen but no success. Any kind of help, tip or suggestion is appreciated.
I have attached a capture of the UGS.

Thanks in advance.
![issueworkpos1](https://user-images.githubusercontent.com/40540237/86476427-23030080-bd64-11ea-94b6-daba7cacfbd6.PNG)

**Comment by langwadt** [comment]
work offsets are persistent, try reset y axis

**Comment by Kruze17** [comment]
> work offsets are persistent, try reset y axis

Thanks for the suggestion... Resetting the y axis works for me.
