### ISSUE TITLE
Typo Error in cpu_map.h COOLANT_MIST_BIT

### ISSUE THREAD

**Issue by zeevy** [gnea/grbl#89]
// Define flood and mist coolant enable output pins.
  #define COOLANT_FLOOD_DDR   DDRC
  #define COOLANT_FLOOD_PORT  PORTC
  #define COOLANT_FLOOD_BIT   3  // **Uno Analog Pin 3**
  #define COOLANT_MIST_DDR   DDRC
  #define COOLANT_MIST_PORT  PORTC
#define COOLANT_MIST_BIT 4 // **Uno Analog Pin 3**

**Comment by chamnit** [comment]
Thanks
