### ISSUE TITLE
Plain GRBL and tool change (beginner question)

### ISSUE THREAD

**Issue by JensHauser** [gnea/grbl#895]
Hi,

for some time I´ve been working with a X/Y/Z edge finder like this and it worked

![1](https://user-images.githubusercontent.com/44340656/88464955-12572d80-cebf-11ea-8545-5d8781342674.JPG)

Now I bought this little thing in order to be able to change a tool during machining a job.

![88403932-78638800-cdcd-11ea-975d-122af5827a54](https://user-images.githubusercontent.com/44340656/88464956-15521e00-cebf-11ea-988b-c2da11fc86e8.JPG)

Seems "G43.1 Dynamic tool length offset" is a subject here. In other forums they use some scripting language to calculate "old" and "new" offset and tell GRBL to use the difference. But with a simple GRBL G code sender without interaction features?

I just can trigger special and static(!) G code in case "M6" command comes up. Fusion 360 offers tool changes like "T1 M6" so theoretically it should have a chance.

It´d be nice to

* home X/Y/Z
* use a the aluminum plate to find G54
* start with tool #1
 (works until here)
* move to tool change position
 (triggered by M6, works)
* measure (whatever that means) the new tool
* go on with machining

Or am I on the wrong track?

The basic procedure after fixing the work piece would also be helpful.

Thanks in advance

**Comment by neilferreri** [comment]
Sorry for the upcoming short response...Check out CNCjs and these [macros](https://github.com/cncjs/CNCjs-Macros) .
I'd avoid G43.1.
Let me know if you have questions... I'll have more time later.

**Comment by JensHauser** [comment]
I‘ll have a look, thanks.
In parallel, I‘m still curious to use plain GRBL G code, if possible.

**Comment by Schildkroet** [comment]
Take a look at my STM32 Port. I does exactly what you want. After M6 the head moves up and you can change tools. Then it probes the new length (with Tool length sensor) and continues the program.

**Comment by neilferreri** [comment]
> I‘m still curious to use plain GRBL G code, if possible.

"Plain" grbl does not handle the M6.

**Comment by JensHauser** [comment]
Plain with the exception of the first post.

But independent of that: what is the typical procedure?

**Comment by MARIOBASZ** [comment]
I am using bcnc, you can see there how it handles the tool change when receiving M6 (that I know grbl does not recognize M6)

**Comment by JensHauser** [comment]
Ok, got it. Thanks a lot to all
