### ISSUE TITLE
Improving Jog command

### ISSUE THREAD

**Issue by luben111** [gnea/grbl#90]
The existing in v1.1 jog functionality works well but it's possible to simplify significantly the support of jogging from the main program by adding one small feature.

At the moment the jogging works in the following way (a simplified example for moving on X axis when pressing X+ button for longer than 500ms):
1. The program sends several commands $J=G91 X1.0 F1000 to keep the buffer semi filled    (relative move of the head on 1mm with feed rate 1000mm/min )
2. When the X+ button was depressed the program sends immediately CMD_JOG_CANCEL  (code 0x85) which aborts the movement and also clears the buffer (history)

Notice that the program should feed all the time the GRBL buffer with new jog commands.

One other approach is to send a single command for jog movement to some far away point instead of multiple small segmented movements and abort the movement when jog ended. For example when pressing X+ button longer than 500ms we could send 
1.  $J=X600.0 F1000  (X600 is the end of the working area of the machine). The head will keep moving against the far end of the working area with the desired feed rate and there is no need for sending new jog commands.
2. When X+ button depressed we send CMD_JOG_CANCEL  (code 0x85) which aborts the movement immediately

When we go in opposite direction (X- button pressed for more than 500ms)  we can send  $J=X0 F1000 in similar way.

This approach works well (if not desired accelerating jogging speed) but there is one place where it's not perfect - if while moving in X+ direction the user presses Y+ button (by still keeping pressed the X+ button) the head should stop first with CMD_JOG_CANCEL  and then to start moving to the new target. This "hiccup" could be removed by adding a new command - skip current jog operation (CMD_JOG_SKIP) which will force the current movement to complete. If the user sent before the CMD_JOG_SKIP a new jog command the change in the movement will be smooth. For example:

1. User pressed X+ for more than 500ms :
 - send  $J=X600.0 F1000

2. User presses Y+ while X+ still pressed:
  - send  $J=X600.0 Y400 F1000
  - send CMD_JOG_SKIP  which will skip the currently executed jog command and force the GRBL to start executing the new $J=X600.0 Y400 F1000 ASAP
 
3. And of course when both keys were depressed - send CMD_JOG_CANCEL  

So the request is for adding a new command to force the completion of the currently executed jog command.

BTW one question - when sending cancel command (CMD_JOG_CANCEL) does the movement abort immediately (just stop moving the head) or it uses the deceleration profile for the steppers (which prevents losing of steps)? 

Thank you

**Comment by chamnit** [comment]
@luben111 : Thanks for your thoughts, but I will not be altering the jogging implementation for Grbl on the Arduino Uno. As stated in the jogging document, it's not ideal and the result of not having anymore flash and RAM available on the Uno.
