### ISSUE TITLE
Axis lenght off by 2 mm

### ISSUE THREAD

**Issue by arminlinder** [gnea/grbl#911]
My machine has an X axis travel length of 350mm.
I set the X-axis length in config:
$130=350.000
but when I issue G0X-350 I get Alarm:2: G-code motion target exceeds machine travel. Ok, I thought it may be an "off by one" problem, and sent the machine to G0X-349, but got the same error. G0X-348 worked. It seems I must set the axis limit to the actutal length +2mm.

Why this !?

**Comment by neilferreri** [comment]
Your homing pull-off ($27) is 2mm.

**Comment by arminlinder** [comment]
Thanks a lot, that explains the issue.
