### ISSUE TITLE
Missing X real time status report per second

### ISSUE THREAD

**Issue by amoineau** [gnea/grbl#942]
Hello,

Thank you for your excellent work on this project. 
I'm using GRBL paired with GRBL-plotter and I often get a message saying that we are missing real time status report. I wanted to know how badly does this affect the system and what could cause this problem ?
For information I am not using an arduino board but one designed by a co-worker. Apart from this, everything seems to be working just fine.

Thank you for your help.

**Comment by svenhb** [comment]
Which version are you using? In an older version was bug in character-counting which could mess-up the controller...
But now,I don't think this is really a problem. Note: I figured out, during homing no response happens, so I suppress the message during homing.
Perhaps your computer is a bit overwhelmed - did you try with slower poll frequency for the status-report?
![image](https://user-images.githubusercontent.com/19973251/96914744-b09a6580-14a5-11eb-912b-cba85c694acc.png)

**Comment by amoineau** [comment]
Hi,
I'm using version 1.1 of grbl and v1.5.0.5 of GRBL-plotter. I'll try to lower the frequency as soon as I can and get back to you.
I'm note sure I understand what you mean by "I suppress the message during homing".
Thank you for your help, it's highly appreciated.
Regards,
Antoine.

**Comment by svenhb** [comment]
>I'm note sure I understand what you mean by "I suppress the message during homing".  
  
During Homing I stop counting the missing reports.
Yesterday I released 1.5.2.1, perhaps problem is solved then.
Regards
Sven

**Comment by amoineau** [comment]
Ok you meant "in a new release", I thought so but I wasn't sure. I can't access the machine right now but I will test both fixes as soon as I can. Thank you for being so reactive.

**Comment by amoineau** [comment]
Hello,
Sorry for the long delay. I tried using the new release but I can't launch the source code. I downloaded the zip, extracted, opened the solution and pressed F5. I didn't alter anything and I got the following result :

![image](https://user-images.githubusercontent.com/72978966/98918326-c364f080-24cd-11eb-8216-575135e5eaa8.png)

**Comment by amoineau** [comment]
Damn I forgot my VS was in french on this computer... Do you want the error in english ?

**Comment by amoineau** [comment]
![image](https://user-images.githubusercontent.com/72978966/98919385-04a9d000-24cf-11eb-99e2-c054c7a9cebc.png)

**Comment by svenhb** [comment]
I forgot to upload the settings files, check here: https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/Properties
Better open an issue at GRBL-Plotter: https://github.com/svenhb/GRBL-Plotter/issues

**Comment by amoineau** [comment]
Ok I opened an issue on GRBL-Plotter. What file should I add from  https://github.com/svenhb/GRBL-Plotter/tree/master/GRBL-Plotter/Properties ?

**Comment by svenhb** [comment]
Just the the files from 9 days ago

**Comment by amoineau** [comment]
Ok thanks !

**Comment by amoineau** [comment]
I was able to play around with the machine and the latest release of GRBL-plotter and I didn't get a single "Missing real time status report". However, it will take more time to be sure that the problem is solved. In the meantime, do you want to close the issue ?

**Comment by amoineau** [comment]
Ok, the problem did not occur since the update so I guess problem's solved.
