### ISSUE TITLE
G04 min value

### ISSUE THREAD

**Issue by Arcadium47** [gnea/grbl#960]
Hello,

I have a grbl 1.1f, I want to use G04 command and I figured out if I send G04 P1 - it is delay for 1 second. I need milliseconds so I send values from 0.0012 to 0.2500.

The problem is that I notice only 5 or 4 different delay times, as if it interprets only in 50 ms increments (I used sound scope and it clearly shows 5 layer graduation). Is this due to grbl or hardware?
Maybe some advice how can I achieve 1ms(or even better 0.1ms) dwell times?

Simas

**Comment by terjeio** [comment]
https://github.com/gnea/grbl/blob/eefe2bb95bb7b21ec2bb87e6ab6e20747e1626c4/grbl/config.h#L409-L414

**Comment by Arcadium47** [comment]
Thank you very much
