### ISSUE TITLE
Probing switch debounce delay

### ISSUE THREAD

**Issue by arlimbad222** [gnea/grbl#966]
Hello forks 

Need advice can i set debounce delay for probe pin like home switch? $26 for homing debounce delay like that .

i made 6mm touch probe but its not working accuratly so i think its debounce delay problem .

thankyou .

**Comment by ZASto** [comment]
You could use NC switch(es) in your probe. With NC there is no bouncing of contacts.

**Comment by arlimbad222** [comment]
Oh thanks I try it tomorrow then get back here & share results .
