### ISSUE TITLE
Spindle pause

### ISSUE THREAD

**Issue by MARIOBASZ** [gnea/grbl#977]
It is practical for me to add an immediate action command pause spindle together with pause, for example to clean the tool with material stuck in the middle of multiple holes, and other inmediate  action activate spindle and then continúe work

**Comment by MeJasonT** [comment]
use the door overide, it pauses the job, retracts the tool and stops the spindle. you can resume by clearing the alarm and pressing cycle strat - the program continues from where it left off.  You dont need to have a safety door, you can use a switch on the program pause connection (as you would wire in an external pause button) but enable the door function which will add a full retract and stop.  Pro machines leave the tool engaged in the work but reduce the spindle speed down to a slow rpm say 200.  I actually prefer the grbl method

**Comment by MeJasonT** [comment]
Happy New Year

**Comment by MARIOBASZ** [comment]
Thanks!!!!  I did not know it

**Comment by harryberlin** [comment]
Does grbl understand the M0 command?

**Comment by MARIOBASZ** [comment]
the goal is to interrupt briefly in the middle of work and then continue. I'm going to take the advice and try open-door interruption.

**Comment by MeJasonT** [comment]
using a progrmmed code option would mean that you intended to do a clean on a regular basis and not a random choice as and when required
